apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-data
  namespace: syncthing
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd-hdd-r2
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-netbird
  namespace: syncthing
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd-hdd-r2
  resources:
    requests:
      storage: 100Mi
