apiVersion: v1
kind: Secret
metadata:
    name: syncthing-netbird-secrets
    namespace: syncthing
type: Opaque
stringData:
    NB_SETUP_KEY: ENC[AES256_GCM,data:rM6tGBD+Wi7MwGsfRYbYjLRQ4mAxsJ/F4CRxuPc7ipDywYbM,iv:4aJAW1YzoMJkg49TssmdvTOF4UposgMkvsxRW8Bphx8=,tag:DK9R+j2iQw5+7MmHM9itUg==,type:str]
    NB_MANAGEMENT_URL: ENC[AES256_GCM,data:E0A0ooNBdgOWBboinlZ5LLaVeA==,iv:kuGdVYLrVsnhZ/08qVOKTdOXuZX8586vIh/c1k1DY9Q=,tag:+uLO+lBXr0jsOsEyI3dM8A==,type:str]
    NB_EXTRA_DNS_LABELS: ENC[AES256_GCM,data:y0eSZUMTfBXMiH4Sv1aE1Ks/9g==,iv:ruqB2dkMT5HGatY8S/9NIE74g1UZhFWeqGtKgHbZ6XM=,tag:u0a7LxB6lS7VgoVbV/KnRg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBySnJJeGVoL3kraVV5azVW
            UEtRSkVTZGJ6Q0Jmd2NKYmRnRDlER1hLSjNjCjM2cUpQSmZUOGJlNFhHYUpYc2ha
            SWlCVVZmcTBWMXZFT3hhUnlhOEdreG8KLS0tIEhoN2xKTnJ1WjlpcGhFZG83bkdo
            TVlBbWo3L3Y5OU9Sbk5KbHFEaFJVVEEKgZm5kXlo3pgduGHxle++6iAqhAV3rXob
            js3dWQcRw/tnJd8XTn4s2U7fm/jWY/GqZIhT4pM4vh7eCOr1F/lmpg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    lastmodified: "2026-09-03T17:19:19Z"
    mac: ENC[AES256_GCM,data:3g1wPk+puM8fC0bgqeaHcd8XT/n7SmsmcCbg9+oeO1hBO3hJfpIgnA3hPig/rUOCBM0fayQDKV+Ye2HeI5KBReB0Q0dH00G1bjq4eKDcICR2BtK3MXcFAutk2YFhzKVdHhB5LRs0wxbdU+kh0DRs3T3AC1stx4vXsjHXYkuu+Bo=,iv:uOvZAkCQpteF0RM2RojlWyTpg5LLZ5gtM5Y9VKGqAek=,tag:hRfeOvq086yBFYkMqtTC9w==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: syncthing-config-volsync-secret
    namespace: syncthing
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:pF87tJAEo21ee7ViPJHnolGrYY4SV7VX246eX1LwSK53E0J5jrD07qSrcZsGGxktm56uXcn59ayvY9vstAmD,iv:xHOz6hdEBZlLu976nrxz/FRiOP7KYDEs9g7eDjkn0KM=,tag:rRND4U19FvurAJcH5ShHWw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:j9rPp+YWozKJCrxMra5aH1Rpc6NPJXaGHbZI6oqE8iLRd8sq3t0AMKwtrwFQ7jgMzSw=,iv:kzMexX8z2S9/BbbFcggkaojo6jvIaIiPT0Bl6tajnz8=,tag:0eBv1PxNDq1RuME9tSsOlA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Dn249mMFck5nObjyrfjJHg==,iv:/07Wa8PE0zkyfen9Xv/sSPCgYzoczsKSWj0GUkhpRc4=,tag:+FjBcz8gUT67kPmJqPz2Xw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:LhhoeNTRZLDuQCfd/kLaRM7WxRXmT7eYrncI2O8YlyLXFoNJjBwT6Jy61XyQL5w4xPY=,iv:8ASPGDjWXyC83Zw7pVO8p0fBxVtZFYx1C+nIgcqrKaU=,tag:GLaYhc5ip3xquBAvaZpDvw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBySnJJeGVoL3kraVV5azVW
            UEtRSkVTZGJ6Q0Jmd2NKYmRnRDlER1hLSjNjCjM2cUpQSmZUOGJlNFhHYUpYc2ha
            SWlCVVZmcTBWMXZFT3hhUnlhOEdreG8KLS0tIEhoN2xKTnJ1WjlpcGhFZG83bkdo
            TVlBbWo3L3Y5OU9Sbk5KbHFEaFJVVEEKgZm5kXlo3pgduGHxle++6iAqhAV3rXob
            js3dWQcRw/tnJd8XTn4s2U7fm/jWY/GqZIhT4pM4vh7eCOr1F/lmpg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    lastmodified: "2026-09-03T17:19:19Z"
    mac: ENC[AES256_GCM,data:3g1wPk+puM8fC0bgqeaHcd8XT/n7SmsmcCbg9+oeO1hBO3hJfpIgnA3hPig/rUOCBM0fayQDKV+Ye2HeI5KBReB0Q0dH00G1bjq4eKDcICR2BtK3MXcFAutk2YFhzKVdHhB5LRs0wxbdU+kh0DRs3T3AC1stx4vXsjHXYkuu+Bo=,iv:uOvZAkCQpteF0RM2RojlWyTpg5LLZ5gtM5Y9VKGqAek=,tag:hRfeOvq086yBFYkMqtTC9w==,type:str]
    version: 3.13.3
