apiVersion: apps/v1
kind: Deployment
metadata:
  name: samba
  namespace: samba
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: samba
  template:
    metadata:
      labels:
        app: samba
    spec:
      priorityClassName: medium-priority
      automountServiceAccountToken: false
      initContainers:
        - name: fix-permissions
          image: alpine:latest
          resources:
            requests:
              cpu: "10m"
              memory: "32Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
          command:
            - sh
            - -c
            - |
              chmod 777 /mnt/nas
              chmod 777 /mnt/tm-claes-hedlund
              chmod 777 /mnt/backup-johanna-hedlund
              chmod 777 /mnt/svtplay-dl
          volumeMounts:
            - name: vol-nas
              mountPath: /mnt/nas
            - name: vol-tm-claes-hedlund
              mountPath: /mnt/tm-claes-hedlund
            - name: vol-backup-johanna-hedlund
              mountPath: /mnt/backup-johanna-hedlund
            - name: vol-svtplay-dl
              mountPath: /mnt/svtplay-dl
      containers:
        - name: samba
          image: dperson/samba:latest
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "512Mi"
          env:
            - name: PASS_ANDREAS_HEDLUND_NAS
              valueFrom:
                secretKeyRef:
                  name: samba-auth
                  key: pass_andreas_hedlund_nas
            - name: PASS_CLAES_HEDLUND_TM
              valueFrom:
                secretKeyRef:
                  name: samba-auth
                  key: pass_claes_hedlund_tm
            - name: PASS_JOHANNA_HEDLUND
              valueFrom:
                secretKeyRef:
                  name: samba-auth
                  key: pass_johanna_hedlund
            - name: KUBERNETES_MEMORY_LIMIT
              valueFrom:
                resourceFieldRef:
                  containerName: samba
                  resource: limits.memory
          args:
            # Användare (Format: "användarnamn;lösenord")
            - "-u"
            - "andreas_hedlund_nas;${PASS_ANDREAS_HEDLUND_NAS}"
            - "-u"
            - "claes_hedlund_tm;${PASS_CLAES_HEDLUND_TM}"
            - "-u"
            - "johanna_hedlund;${PASS_JOHANNA_HEDLUND}"

            # Delade mappar (Format: "ShareNamn;Sökväg;Browsable;ReadOnly;Guest;Users")
            - "-s"
            - "NAS;/mnt/nas;yes;no;no;andreas_hedlund_nas"
            - "-s"
            - "TM-Claes-Hedlund;/mnt/tm-claes-hedlund;yes;no;no;claes_hedlund_tm"
            - "-s"
            - "Backup-Johanna-Hedlund;/mnt/backup-johanna-hedlund;yes;no;no;johanna_hedlund"
            - "-s"
            - "SVTPlay-DL;/mnt/svtplay-dl;yes;no;no;andreas_hedlund_nas"
            
            # Globala Apple/Time Machine-inställningar
            - "-g"
            - "vfs objects = fruit streams_xattr"
            - "-g"
            - "fruit:aapl = yes"
            - "-g"
            - "fruit:time machine = yes"
          ports:
            - containerPort: 445
              name: smb
          volumeMounts:
            - name: vol-nas
              mountPath: /mnt/nas
            - name: vol-tm-claes-hedlund
              mountPath: /mnt/tm-claes-hedlund
            - name: vol-backup-johanna-hedlund
              mountPath: /mnt/backup-johanna-hedlund
            - name: vol-svtplay-dl
              mountPath: /mnt/svtplay-dl
      volumes:
        - name: vol-nas
          persistentVolumeClaim:
            claimName: nas
        - name: vol-tm-claes-hedlund
          persistentVolumeClaim:
            claimName: tm-claes-hedlund
        - name: vol-backup-johanna-hedlund
          persistentVolumeClaim:
            claimName: backup-johanna-hedlund
        - name: vol-svtplay-dl
          persistentVolumeClaim:
            claimName: svtplay-dl-samba