apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: samba
  namespace: samba
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    defaultPodOptions:
      automountServiceAccountToken: false
      priorityClassName: medium-priority
      terminationGracePeriodSeconds: 60

    controllers:
      main:
        type: deployment
        strategy: Recreate
        
        initContainers:
          fix-permissions:
            image:
              repository: alpine
              tag: latest
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                cpu: 100m
                memory: 128Mi
            command:
              - sh
              - -c
              - |
                chmod 777 /mnt/nas \
                          /mnt/backup-andreas-hedlund-m-fe \
                          /mnt/backup-andreas-hedlund-mac-mini \
                          /mnt/tm-claes-hedlund \
                          /mnt/backup-johanna-hedlund-macbook \
                          /mnt/svtplay-dl \
                          /mnt/backup-ha-lahalla

        containers:
          main:
            image:
              repository: ghcr.io/servercontainers/samba
              tag: latest
            securityContext:
              capabilities:
                add:
                  - NET_ADMIN
            resources:
              requests:
                cpu: 50m
                memory: 256Mi
              limits:
                cpu: 1000m
                memory: 2Gi
            env:
              SAMBA_CONF_WORKGROUP: "WORKGROUP"
              SAMBA_CONF_SERVER_STRING: "Samba-s1-main01"
              SAMBA_CONF_MAP_TO_GUEST: "Bad User"
              SAMBA_CONF_LOG_LEVEL: "1"
              ACCOUNT_andreas_hedlund:
                valueFrom:
                  secretKeyRef:
                    name: samba-auth
                    key: pass_andreas_hedlund
              ACCOUNT_claes_hedlund_tm:
                valueFrom:
                  secretKeyRef:
                    name: samba-auth
                    key: pass_claes_hedlund
              ACCOUNT_johanna_hedlund:
                valueFrom:
                  secretKeyRef:
                    name: samba-auth
                    key: pass_johanna_hedlund
              ACCOUNT_ha_lahalla:
                valueFrom:
                  secretKeyRef:
                    name: samba-auth
                    key: pass_ha_lahalla
            ports:
              - name: smb
                containerPort: 445

          netbird:
            image:
              repository: netbirdio/netbird
              tag: 0.77.0
            env:
              NB_HOSTNAME: samba-s1-main01
            envFrom:
              - secretRef:
                  name: samba-netbird-secrets
            securityContext:
              capabilities:
                add:
                  - NET_ADMIN

    service:
      main:
        controller: main
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: "192.168.201.101"
        ports:
          smb:
            port: 445
            protocol: TCP

    configMaps:
      samba-config:
        enabled: true
        data:
          smb.conf: |
            [global]
               workgroup = WORKGROUP
               netbios name = SAMBA-NAS
               server string = Samba-s1-main01
               server role = standalone server
               log level = 1
               map to guest = Bad User
               usershare allow guests = no

               # Globala Apple / macOS / VFS Fruit-optimeringar
               vfs objects = fruit streams_xattr
               fruit:aapl = yes
               fruit:time machine = yes
               fruit:model = Macpro
               fruit:metadata = stream
               fruit:posix_rename = yes
               fruit:zero_file_id = yes
               fruit:wipe_intentionally_left_blank_rfork = yes
               fruit:delete_empty_adfiles = yes

            [NAS]
               path = /mnt/nas
               browseable = yes
               read only = no
               valid users = andreas_hedlund

            [backup-andreas-hedlund-m-fe]
               path = /mnt/backup-andreas-hedlund-m-fe
               browseable = yes
               read only = no
               valid users = andreas_hedlund

            [backup-andreas-hedlund-mac-mini]
               path = /mnt/backup-andreas-hedlund-mac-mini
               browseable = yes
               read only = no
               valid users = andreas_hedlund

            [TM-Claes-Hedlund]
               path = /mnt/tm-claes-hedlund
               browseable = yes
               read only = no
               valid users = claes_hedlund_tm

            [backup-johanna-hedlund-macbook]
               path = /mnt/backup-johanna-hedlund-macbook
               browseable = yes
               read only = no
               valid users = johanna_hedlund

            [SVTPlay-DL]
               path = /mnt/svtplay-dl
               browseable = yes
               read only = no
               valid users = andreas_hedlund

            [Backup-HA-Lahalla]
               path = /mnt/backup-ha-lahalla
               browseable = yes
               read only = no
               valid users = ha_lahalla

    persistence:
      config:
        type: configMap
        name: samba-samba-config
        advancedMounts:
          main:
            main:
              - path: /container/config/samba/smb.conf
                subPath: smb.conf
      netbird-state:
        existingClaim: samba-netbird
        advancedMounts:
          main:
            netbird:
              - path: /var/lib/netbird

      vol-nas:
        type: persistentVolumeClaim
        existingClaim: nas
        globalMounts:
          - path: /mnt/nas
      vol-backup-andreas-hedlund-m-fe:
        type: persistentVolumeClaim
        existingClaim: backup-andreas-hedlund-m-fe
        globalMounts:
          - path: /mnt/backup-andreas-hedlund-m-fe
      vol-backup-andreas-hedlund-mac-mini:
        type: persistentVolumeClaim
        existingClaim: backup-andreas-hedlund-mac-mini
        globalMounts:
          - path: /mnt/backup-andreas-hedlund-mac-mini
      vol-tm-claes:
        type: persistentVolumeClaim
        existingClaim: tm-claes-hedlund
        globalMounts:
          - path: /mnt/tm-claes-hedlund
      vol-backup-johanna-hedlund-macbook:
        type: persistentVolumeClaim
        existingClaim: backup-johanna-hedlund-macbook
        globalMounts:
          - path: /mnt/backup-johanna-hedlund-macbook
      vol-svtplay:
        type: persistentVolumeClaim
        existingClaim: svtplay-dl-samba
        globalMounts:
          - path: /mnt/svtplay-dl
      vol-backup-ha:
        type: persistentVolumeClaim
        existingClaim: backup-ha-lahalla
        globalMounts:
          - path: /mnt/backup-ha-lahalla