---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas
  namespace: samba
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ceph-fs-hdd-r2
  resources:
    requests:
      storage: 500Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tm-claes-hedlund
  namespace: samba
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ceph-fs-hdd-r2
  resources:
    requests:
      storage: 300Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-andreas-hedlund
  namespace: samba
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ceph-fs-hdd-r2
  resources:
    requests:
      storage: 300Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-johanna-hedlund
  namespace: samba
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ceph-fs-hdd-r2
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: svtplay-dl-samba
  namespace: samba
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: svtplay-dl-pv-samba
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-ha-lahalla
  namespace: samba
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ceph-fs-hdd-r2
  resources:
    requests:
      storage: 300Gi