---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: samba-backup-andreas-hedlund-mac-mini-backup
  namespace: samba
spec:
  sourcePVC: backup-andreas-hedlund-mac-mini
  trigger:
    schedule: "0 3 * * *"
  restic:
    copyMethod: Snapshot
    volumeSnapshotClassName: csi-cephrbdplugin-snapclass
    repository: volsync-samba-backup-andreas-hedlund-mac-mini-secrets
    pruneIntervalDays: 14
    cacheAccessModes:
      - ReadWriteOnce
    cacheCapacity: 10Gi
    cacheStorageClassName: ceph-rbd-hdd-r2  # ceph-rbd-nvme-r1
    storageClassName: ceph-rbd-hdd-r2
    moverSecurityContext:
      fsGroupChangePolicy: OnRootMismatch
      runAsUser: 0
      runAsGroup: 0
    retain:
      last: "2"
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: samba-backup-ha-lahalla-backup
  namespace: samba
spec:
  sourcePVC: backup-ha-lahalla
  trigger:
    schedule: "15 3 * * *"
  restic:
    copyMethod: Snapshot
    volumeSnapshotClassName: csi-cephrbdplugin-snapclass
    repository: volsync-samba-backup-ha-lahalla-secrets
    pruneIntervalDays: 14
    cacheAccessModes:
      - ReadWriteOnce
    cacheCapacity: 10Gi
    cacheStorageClassName: ceph-rbd-hdd-r2  # ceph-rbd-nvme-r1
    storageClassName: ceph-rbd-hdd-r2
    moverSecurityContext:
      fsGroupChangePolicy: OnRootMismatch
      runAsUser: 0
      runAsGroup: 0
    retain:
      last: "2"
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: samba-backup-ha-johanna-backup
  namespace: samba
spec:
  sourcePVC: backup-ha-johanna
  trigger:
    schedule: "15 3 * * *"
  restic:
    copyMethod: Snapshot
    volumeSnapshotClassName: csi-cephrbdplugin-snapclass
    repository: volsync-samba-backup-ha-johanna-secrets
    pruneIntervalDays: 14
    cacheAccessModes:
      - ReadWriteOnce
    cacheCapacity: 10Gi
    cacheStorageClassName: ceph-rbd-hdd-r2  # ceph-rbd-nvme-r1
    storageClassName: ceph-rbd-hdd-r2
    moverSecurityContext:
      fsGroupChangePolicy: OnRootMismatch
      runAsUser: 0
      runAsGroup: 0
    retain:
      last: "2"
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: samba-backup-johanna-hedlund-macbook-backup
  namespace: samba
spec:
  sourcePVC: backup-johanna-hedlund-macbook
  trigger:
    schedule: "30 3 * * *"
  restic:
    copyMethod: Snapshot
    volumeSnapshotClassName: csi-cephrbdplugin-snapclass
    repository: volsync-samba-backup-johanna-hedlund-macbook-secrets
    pruneIntervalDays: 14
    cacheAccessModes:
      - ReadWriteOnce
    cacheCapacity: 15Gi
    cacheStorageClassName: ceph-rbd-hdd-r2  # ceph-rbd-nvme-r1
    storageClassName: ceph-rbd-hdd-r2
    moverSecurityContext:
      fsGroupChangePolicy: OnRootMismatch
      runAsUser: 0
      runAsGroup: 0
    retain:
      last: "2"

---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: samba-nas-backup
  namespace: samba
spec:
  sourcePVC: nas
  trigger:
    schedule: "45 3 * * *"
  restic:
    copyMethod: Snapshot
    volumeSnapshotClassName: csi-cephfsplugin-snapclass
    repository: volsync-samba-nas-secrets
    pruneIntervalDays: 28
    cacheAccessModes:
      - ReadWriteOnce
    cacheCapacity: 15Gi
    cacheStorageClassName: ceph-rbd-hdd-r2  # ceph-rbd-nvme-r1
    storageClassName: ceph-fs-hdd-r2
    moverSecurityContext:
      fsGroupChangePolicy: OnRootMismatch
      runAsUser: 0
      runAsGroup: 0
    retain:
      daily: 7
      weekly: 2
      monthly: 6

---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: samba-backup-claes-hedlund-macbook-backup
  namespace: samba
spec:
  sourcePVC: backup-claes-hedlund-macbook
  trigger:
    schedule: "0 4 * * *"
  restic:
    copyMethod: Snapshot
    volumeSnapshotClassName: csi-cephrbdplugin-snapclass
    repository: volsync-samba-backup-claes-hedlund-macbook-secrets
    pruneIntervalDays: 14
    cacheAccessModes:
      - ReadWriteOnce
    cacheCapacity: 10Gi
    cacheStorageClassName: ceph-rbd-hdd-r2  # ceph-rbd-nvme-r1
    storageClassName: ceph-rbd-hdd-r2
    moverSecurityContext:
      fsGroupChangePolicy: OnRootMismatch
      runAsUser: 0
      runAsGroup: 0
    retain:
      last: "2"
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: samba-backup-asa-hedlund-backup
  namespace: samba
spec:
  sourcePVC: backup-asa-hedlund-macbook
  trigger:
    schedule: "0 4 * * *"
  restic:
    copyMethod: Snapshot
    volumeSnapshotClassName: csi-cephrbdplugin-snapclass
    repository: volsync-samba-backup-asa-hedlund-secrets
    pruneIntervalDays: 14
    cacheAccessModes:
      - ReadWriteOnce
    cacheCapacity: 10Gi
    cacheStorageClassName: ceph-rbd-hdd-r2  # ceph-rbd-nvme-r1
    storageClassName: ceph-rbd-hdd-r2
    moverSecurityContext:
      fsGroupChangePolicy: OnRootMismatch
      runAsUser: 0
      runAsGroup: 0
    retain:
      last: "2"