apiVersion: v1
kind: Secret
metadata:
    name: samba-auth
    namespace: samba
type: Opaque
stringData:
    pass_andreas_hedlund: ENC[AES256_GCM,data:Z2oDYXCb2WXB2hf/EgljSJIdq+4HGbKDLrVqeZYesweHAB7nMYp43QMiqj7UVd3R9mk=,iv:HvMfw2FmgW++MVkdFtD7jmE6iGt4RZhL8PM5bhoYJrY=,tag:gmt3eeiZRmIROMKAnQi9hQ==,type:str]
    pass_claes_hedlund: ENC[AES256_GCM,data:5rwNO13GPnUz4l8XX33F8M+a35eQtw4yKlRfKAuq1brvQVB5IkbnxpFwQnNSWVimx+M=,iv:sY6ZZbchDfvciD6UYfBXHOPGzIuXRO5mkSBBJDyI01g=,tag:6W83MdPgYaeMVGzuWTP1Mw==,type:str]
    pass_johanna_hedlund: ENC[AES256_GCM,data:w96RIX5dhQGetL9aad06wqujIGQySa8xoI4GOyF5y1Ps1RpxDNHkXyZ1cTQg5iXavUg=,iv:OKueK/VJ+B6pL79p1ilxOFDQMqrCdigqcxZW7JDv0ws=,tag:etvEuGtQxKWw0KOHGrUicA==,type:str]
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxRS9EdDlKejdrakJXNmk1
            SmlnYTN6Y3grR0xiTStaWHRuaXdPa1ZUQWw0CkVOQ0pONWMxVWt5Y2xZaWZWNmwy
            aVF3ODBxWTNmSURvSk1JTWVXa0dsTUUKLS0tIGZWNmFVd0o5SG1ibk1ObnBEbFR5
            Y01HUDd3Ti9GMk84RHdFd0FhbEQ3eHMKPt/Uti5Vo0xvNzh8Htd+O+haOJ/t9m7Z
            s3D6wNknDdMOYWnM+EJA+g5bffX01ulfPZBbAcijiCOPxfWcabJHug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-24T19:38:37Z"
    mac: ENC[AES256_GCM,data:mccaaD2hn2EMHyfY+VzdAvSfV48EjvpGji6Px6idxim3r+8hsYsME6Ot6/uZVJi+3+jZqu/QLVuSJacjNMnfAVgm4N1MKeUDb1dWtYl7eMNDZjY/71+Isxi6vU90chOBJ9Ezp9/feW4JNUboCTpnoPKplivSVJrCr/RLqJ3vJFk=,iv:2Uw3fVQblUhv8gEvg0Im4HDb8JppzTUmYEB/3GOqxgk=,tag:ks4ju1BjY//9K3ew4ie14A==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    version: 3.12.2
