apiVersion: v1
kind: Secret
metadata:
    name: samba-auth
    namespace: samba
type: Opaque
stringData:
    pass_andreas_hedlund_nas: ENC[AES256_GCM,data:ntsDbj8m0AQ=,iv:ocns34WDMeEx25MCqVzkjKEuWRbe4CQj47BJwGLwvHI=,tag:G6I28lzToRkmu6CkDLKWAQ==,type:str]
    pass_claes_hedlund_tm: ENC[AES256_GCM,data:qU171i8+UTM=,iv:7oTvP+7W/xnoukqlVQVCv8QHIOLmqoQWPjTeFdi18BM=,tag:WLYHbKJFbunh2yvHZlbzDg==,type:str]
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxRS9EdDlKejdrakJXNmk1
            SmlnYTN6Y3grR0xiTStaWHRuaXdPa1ZUQWw0CkVOQ0pONWMxVWt5Y2xZaWZWNmwy
            aVF3ODBxWTNmSURvSk1JTWVXa0dsTUUKLS0tIGZWNmFVd0o5SG1ibk1ObnBEbFR5
            Y01HUDd3Ti9GMk84RHdFd0FhbEQ3eHMKPt/Uti5Vo0xvNzh8Htd+O+haOJ/t9m7Z
            s3D6wNknDdMOYWnM+EJA+g5bffX01ulfPZBbAcijiCOPxfWcabJHug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-07T12:23:13Z"
    mac: ENC[AES256_GCM,data:38+hPgAyb8C3EEoHFb9fBo8msj0SvBEEvQ7la5+ABoO0r2l4kvIoKpOSPWRQ0WWZkj7IiRg7XH4WQjJyVRVQ3m/GXkGsXqaHTvkNJVJdsy9Xw6BOokt2fKxFPitaBUllkqY6VqM8iK9RCHaxqp2GsgVbECT5znG3kAc+ITvNqFA=,iv:xSJAKOj5zEfAIHv+3gaw7myp/a6R0k+nlvxa0WTJVEk=,tag:EH13OG2lgyB6dMJRCUesJg==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    version: 3.12.2
