apiVersion: v1
kind: Secret
metadata:
    name: samba-netbird-secrets
    namespace: samba
type: Opaque
stringData:
    NB_SETUP_KEY: ENC[AES256_GCM,data:/xRDdd2CkBa+Il2pTA3Xy6K+SVXlVmPW7DqAThRmaseW9v1l,iv:eeI7sWIzkTAQOd8Kp9tFjcKxBuG9hwcWp2v0CYeaGxM=,tag:KlcJp1/hoPZwGbeVJ6g5EA==,type:str]
    NB_MANAGEMENT_URL: ENC[AES256_GCM,data:ekUHm0p4pLHy9x73Fz23j4blzg==,iv:8JMMxN6wyK/sm0rLtBiHH1K1cK+ptgQlcP4bWL6CIHg=,tag:1ODjJCk7HBjdY3GuFjmRxg==,type:str]
    NB_EXTRA_DNS_LABELS: ENC[AES256_GCM,data:s2S1yX4Pf6p9Ml9+dxPR,iv:qhI66fCE2KdCavyyPvNpVWzt9IzkHHqEVKPpT3zWsZM=,tag:wplvYwXVf4c7YJa5uKpBfQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtM0szdEkwbG00MGhUNzMx
            TUM3c0VWUkxaeG92WlZhdE00SGZkbSs3QTAwCnNmT21ia1BLU0pDTGl6OG4rOVBV
            dmZtemc1TFpmU0t1ODdNNjRGOENIVm8KLS0tIDhPUzBCU0tOclRiaDdPUUREamM0
            TjZQaW9oS0NsME9GbUxUOHBEWmtMSEUKxFqtGyMcJwSwRW4x7wdeaab9JuiyJ9cK
            rwCs+O1rMxiKntMMPc19LepbTvnUtdIUzMTOaa+uvsXevsiCpRVICg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    lastmodified: "2026-09-09T11:30:13Z"
    mac: ENC[AES256_GCM,data:1CdX8tYmjRRh8XzDO0o4+wXiwicTWNYgKc8WpQI+FF/tmWzM+HjVpvj4ZOQSUiucSzHhbW3to4quEPTjEfqT3FaH7hV+8xpmJurtgIhht1W6KkdR5NShxAW5TGXuCYKWJBVVYf5kuTxUUuoaCzyEY+NxwW0XUBptuCwwbJ6JCts=,iv:7iLHqjrPcsfGkNQasYaWQLRy/wClM4OeMzRVBJaDVyE=,tag:YpO2bFURD2QwqvTz+t9w7Q==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: samba-auth
    namespace: samba
type: Opaque
stringData:
    pass_andreas_hedlund: ENC[AES256_GCM,data:qw/gc4DJwWFzoRL2Ra+KzFVe4Nw7fGt4XrEe3VGguXYiGX6JzQPMO8Uz2DDicBuZT0k=,iv:5aGwkZ4RoV1FytOUTgBLK+Xh7bKiOX4eh0yOW8KXRnY=,tag:dTI2r8sfHo3pnwR5KfzTEg==,type:str]
    pass_andreas_hedlund_backup_mac_mini: ENC[AES256_GCM,data:kM43ZLhyl9ZJH79ke12OqygwP/b1B/5fJZPEZeLMtjE21AnqyvI8jp7YtxCMnuEp3YA=,iv:Nd0TPNWE4CQbqkDfStSn7lOAk7lpF5p6jkKO+HW8m0E=,tag:+DRDTFYh30g6XMYsuRV46g==,type:str]
    pass_claes_hedlund_backup_macbook: ENC[AES256_GCM,data:GzTI7rDJmxjvDONRQRkAoeiKHNu6zapWsLyL3EBS+SMnNq/BqZ5niurahqt5jhXhE7Q=,iv:EmrDGmC7ru8AEhe8zilE7Y4CjbBtgKsdWUnnGsGJ7Sc=,tag:B3pApK2nA6M3HRw113/A7g==,type:str]
    pass_johanna_hedlund: ENC[AES256_GCM,data:lTMtKIMtkIux2FnCVAE1fsyD69GK5wAdp9sqnkZ77G2iMiBw9X6PovFOYGo/Vzgl8xU=,iv:xIuYFxM8GBGHqEn8PbvYjcUlX3Gj6iHlPyLE+emmZcM=,tag:TjAKz9859eRuqpAkCLw+Kw==,type:str]
    pass_ha_lahalla: ENC[AES256_GCM,data:jahDaPVaZkJCgntxNpZ/aQ/hmnWqo/5W52s94RhtUZ6j2nw0URcWLrLMV0PNiD6/GJE=,iv:LcEPwhFFmvwGV/au4uuZyw4b9r3fzuky2A7KbQ6dpzc=,tag:PDGjx2/adpyLlWaoawfmOg==,type:str]
    pass_ha_johanna: ENC[AES256_GCM,data:NCaOaoLkx4r38rcYZXnhTVKU40nPrNUzfoCrrFX5dULQNi/Gx1YJsmyDMZqDTPR3eQg=,iv:MnVXtzbsrhLTQK2d4uDfngABBpG4lmXuo5hmm3iiaUw=,tag:viOjcbLDAlNXp5kSu2msZQ==,type:str]
    pass_asa_hedlund_backup_macbook: ENC[AES256_GCM,data:n5vBiY1x23zws2xWzrtpj3wRy8H7c6FyR7XbvfPwjEGJgXdHsclDA2TY7PzYGVNdHT0=,iv:NgHeZ+7inuPvICmwITGZZfcLK5i3vLea2AXAV0fOWl0=,tag:1RE6EHbw4/bHmctTUNe6NQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtM0szdEkwbG00MGhUNzMx
            TUM3c0VWUkxaeG92WlZhdE00SGZkbSs3QTAwCnNmT21ia1BLU0pDTGl6OG4rOVBV
            dmZtemc1TFpmU0t1ODdNNjRGOENIVm8KLS0tIDhPUzBCU0tOclRiaDdPUUREamM0
            TjZQaW9oS0NsME9GbUxUOHBEWmtMSEUKxFqtGyMcJwSwRW4x7wdeaab9JuiyJ9cK
            rwCs+O1rMxiKntMMPc19LepbTvnUtdIUzMTOaa+uvsXevsiCpRVICg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    lastmodified: "2026-09-09T11:30:13Z"
    mac: ENC[AES256_GCM,data:1CdX8tYmjRRh8XzDO0o4+wXiwicTWNYgKc8WpQI+FF/tmWzM+HjVpvj4ZOQSUiucSzHhbW3to4quEPTjEfqT3FaH7hV+8xpmJurtgIhht1W6KkdR5NShxAW5TGXuCYKWJBVVYf5kuTxUUuoaCzyEY+NxwW0XUBptuCwwbJ6JCts=,iv:7iLHqjrPcsfGkNQasYaWQLRy/wClM4OeMzRVBJaDVyE=,tag:YpO2bFURD2QwqvTz+t9w7Q==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: volsync-samba-backup-andreas-hedlund-mac-mini-secrets
    namespace: samba
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:u+Yx4uPJhBxRfk3PAL7Vz0p1E9t/8gUNA4wy3w0CPqgAcrq/iXRuEvez7HTkk0+VYMuaIoqpP3by0yLFSBHnD1fu82ymPNpLj14HRJph0GIihOYV,iv:h28MzAbVoEoNTsxN7ruKtXhQ61VfpYXbGUPj+H0DSR8=,tag:D4mfEMgOhbw/a3mpRVxejA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:iFN7xrrPONjKKteyTg9rWTiST6w1DdMyUdSgl8UQG7HB91jGrJAvz9Xt3AGSdxg6ez8=,iv:IUa6YO0Lw9Ap+xdQY6DYfi54e0fZvU6hEqacvLNOE58=,tag:rPXkozwj6cnI6+8cKx2A0w==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:IbG/zOL9KhIH8i/vASgkEg==,iv:kRs1Po6XvciywQFYEVHj2qSH+B4li8zenzty16m5OAo=,tag:870+xx61hsP6oaNTrFdsXA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ZQEYqG8vwD/xYblhY/r6fUah0qUXym0KurtXgs9w+QdDoWoZ+3Hn5ZLF63LtfHtBSbo=,iv:wMjqKQgOtswxIxPlcJz8lCMHZ4/DZ57aAAfKcbI+XlU=,tag:EP6x5YyjwNObUwAPEkkbWA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtM0szdEkwbG00MGhUNzMx
            TUM3c0VWUkxaeG92WlZhdE00SGZkbSs3QTAwCnNmT21ia1BLU0pDTGl6OG4rOVBV
            dmZtemc1TFpmU0t1ODdNNjRGOENIVm8KLS0tIDhPUzBCU0tOclRiaDdPUUREamM0
            TjZQaW9oS0NsME9GbUxUOHBEWmtMSEUKxFqtGyMcJwSwRW4x7wdeaab9JuiyJ9cK
            rwCs+O1rMxiKntMMPc19LepbTvnUtdIUzMTOaa+uvsXevsiCpRVICg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    lastmodified: "2026-09-09T11:30:13Z"
    mac: ENC[AES256_GCM,data:1CdX8tYmjRRh8XzDO0o4+wXiwicTWNYgKc8WpQI+FF/tmWzM+HjVpvj4ZOQSUiucSzHhbW3to4quEPTjEfqT3FaH7hV+8xpmJurtgIhht1W6KkdR5NShxAW5TGXuCYKWJBVVYf5kuTxUUuoaCzyEY+NxwW0XUBptuCwwbJ6JCts=,iv:7iLHqjrPcsfGkNQasYaWQLRy/wClM4OeMzRVBJaDVyE=,tag:YpO2bFURD2QwqvTz+t9w7Q==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: volsync-samba-backup-ha-lahalla-secrets
    namespace: samba
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:KgsntWVjJ86AWnu2D3Q6ZhyWMIHIbfe22miy8HpvWB7LiU/E97sulB/aE7p0bw19NND/bMNtx8bc79pH9UJJ84VcnIqHYQ==,iv:eHhxORvNn/fgLVd4518awrJl9JVFqrBw4tyqISZD2P0=,tag:YeLzcb9YOBFGmm6peFfgYA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:iFN7xrrPONjKKteyTg9rWTiST6w1DdMyUdSgl8UQG7HB91jGrJAvz9Xt3AGSdxg6ez8=,iv:IUa6YO0Lw9Ap+xdQY6DYfi54e0fZvU6hEqacvLNOE58=,tag:rPXkozwj6cnI6+8cKx2A0w==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:IbG/zOL9KhIH8i/vASgkEg==,iv:kRs1Po6XvciywQFYEVHj2qSH+B4li8zenzty16m5OAo=,tag:870+xx61hsP6oaNTrFdsXA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ZQEYqG8vwD/xYblhY/r6fUah0qUXym0KurtXgs9w+QdDoWoZ+3Hn5ZLF63LtfHtBSbo=,iv:wMjqKQgOtswxIxPlcJz8lCMHZ4/DZ57aAAfKcbI+XlU=,tag:EP6x5YyjwNObUwAPEkkbWA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtM0szdEkwbG00MGhUNzMx
            TUM3c0VWUkxaeG92WlZhdE00SGZkbSs3QTAwCnNmT21ia1BLU0pDTGl6OG4rOVBV
            dmZtemc1TFpmU0t1ODdNNjRGOENIVm8KLS0tIDhPUzBCU0tOclRiaDdPUUREamM0
            TjZQaW9oS0NsME9GbUxUOHBEWmtMSEUKxFqtGyMcJwSwRW4x7wdeaab9JuiyJ9cK
            rwCs+O1rMxiKntMMPc19LepbTvnUtdIUzMTOaa+uvsXevsiCpRVICg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    lastmodified: "2026-09-09T11:30:13Z"
    mac: ENC[AES256_GCM,data:1CdX8tYmjRRh8XzDO0o4+wXiwicTWNYgKc8WpQI+FF/tmWzM+HjVpvj4ZOQSUiucSzHhbW3to4quEPTjEfqT3FaH7hV+8xpmJurtgIhht1W6KkdR5NShxAW5TGXuCYKWJBVVYf5kuTxUUuoaCzyEY+NxwW0XUBptuCwwbJ6JCts=,iv:7iLHqjrPcsfGkNQasYaWQLRy/wClM4OeMzRVBJaDVyE=,tag:YpO2bFURD2QwqvTz+t9w7Q==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: volsync-samba-backup-ha-johanna-secrets
    namespace: samba
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:9CP93ZKBgWKUFZmUsFsgO45ptc2JIebpW3ZL3rB7QUxk0VW9qulSkm476pQZEICeG+ojA50dTaP0j9ooF4hTiG5Lv6oAuA==,iv:cZV7ACYsO/3RN7/F5ed6xLKkY0DO9tON6PIujrA/XdM=,tag:cN+ZqGC2FEhI6NvY8HQKRA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:iFN7xrrPONjKKteyTg9rWTiST6w1DdMyUdSgl8UQG7HB91jGrJAvz9Xt3AGSdxg6ez8=,iv:IUa6YO0Lw9Ap+xdQY6DYfi54e0fZvU6hEqacvLNOE58=,tag:rPXkozwj6cnI6+8cKx2A0w==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:IbG/zOL9KhIH8i/vASgkEg==,iv:kRs1Po6XvciywQFYEVHj2qSH+B4li8zenzty16m5OAo=,tag:870+xx61hsP6oaNTrFdsXA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ZQEYqG8vwD/xYblhY/r6fUah0qUXym0KurtXgs9w+QdDoWoZ+3Hn5ZLF63LtfHtBSbo=,iv:wMjqKQgOtswxIxPlcJz8lCMHZ4/DZ57aAAfKcbI+XlU=,tag:EP6x5YyjwNObUwAPEkkbWA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtM0szdEkwbG00MGhUNzMx
            TUM3c0VWUkxaeG92WlZhdE00SGZkbSs3QTAwCnNmT21ia1BLU0pDTGl6OG4rOVBV
            dmZtemc1TFpmU0t1ODdNNjRGOENIVm8KLS0tIDhPUzBCU0tOclRiaDdPUUREamM0
            TjZQaW9oS0NsME9GbUxUOHBEWmtMSEUKxFqtGyMcJwSwRW4x7wdeaab9JuiyJ9cK
            rwCs+O1rMxiKntMMPc19LepbTvnUtdIUzMTOaa+uvsXevsiCpRVICg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    lastmodified: "2026-09-09T11:30:13Z"
    mac: ENC[AES256_GCM,data:1CdX8tYmjRRh8XzDO0o4+wXiwicTWNYgKc8WpQI+FF/tmWzM+HjVpvj4ZOQSUiucSzHhbW3to4quEPTjEfqT3FaH7hV+8xpmJurtgIhht1W6KkdR5NShxAW5TGXuCYKWJBVVYf5kuTxUUuoaCzyEY+NxwW0XUBptuCwwbJ6JCts=,iv:7iLHqjrPcsfGkNQasYaWQLRy/wClM4OeMzRVBJaDVyE=,tag:YpO2bFURD2QwqvTz+t9w7Q==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: volsync-samba-backup-johanna-hedlund-macbook-secrets
    namespace: samba
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:jrO2LeA2DXN590SLkPbykQaVwtUKrjEv7uB0jgOjGsIyHiPq+42+MYZ86HJVqqeRlRvCebP63kFfkjaycpQU1T+cFNp1Nu49VDFNhQYbkwjTEeA=,iv:wdgFsQW9H6v2KxTRQig5xFtW+yG6Hj65FSrDYdBGpvc=,tag:wiFPO6B2lGL3rOWc6V40dg==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:iFN7xrrPONjKKteyTg9rWTiST6w1DdMyUdSgl8UQG7HB91jGrJAvz9Xt3AGSdxg6ez8=,iv:IUa6YO0Lw9Ap+xdQY6DYfi54e0fZvU6hEqacvLNOE58=,tag:rPXkozwj6cnI6+8cKx2A0w==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:IbG/zOL9KhIH8i/vASgkEg==,iv:kRs1Po6XvciywQFYEVHj2qSH+B4li8zenzty16m5OAo=,tag:870+xx61hsP6oaNTrFdsXA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ZQEYqG8vwD/xYblhY/r6fUah0qUXym0KurtXgs9w+QdDoWoZ+3Hn5ZLF63LtfHtBSbo=,iv:wMjqKQgOtswxIxPlcJz8lCMHZ4/DZ57aAAfKcbI+XlU=,tag:EP6x5YyjwNObUwAPEkkbWA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtM0szdEkwbG00MGhUNzMx
            TUM3c0VWUkxaeG92WlZhdE00SGZkbSs3QTAwCnNmT21ia1BLU0pDTGl6OG4rOVBV
            dmZtemc1TFpmU0t1ODdNNjRGOENIVm8KLS0tIDhPUzBCU0tOclRiaDdPUUREamM0
            TjZQaW9oS0NsME9GbUxUOHBEWmtMSEUKxFqtGyMcJwSwRW4x7wdeaab9JuiyJ9cK
            rwCs+O1rMxiKntMMPc19LepbTvnUtdIUzMTOaa+uvsXevsiCpRVICg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    lastmodified: "2026-09-09T11:30:13Z"
    mac: ENC[AES256_GCM,data:1CdX8tYmjRRh8XzDO0o4+wXiwicTWNYgKc8WpQI+FF/tmWzM+HjVpvj4ZOQSUiucSzHhbW3to4quEPTjEfqT3FaH7hV+8xpmJurtgIhht1W6KkdR5NShxAW5TGXuCYKWJBVVYf5kuTxUUuoaCzyEY+NxwW0XUBptuCwwbJ6JCts=,iv:7iLHqjrPcsfGkNQasYaWQLRy/wClM4OeMzRVBJaDVyE=,tag:YpO2bFURD2QwqvTz+t9w7Q==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: volsync-samba-nas-secrets
    namespace: samba
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:ik8/34xHJ3iyo3RIitd81wQ2sJM0LA9ITxDlXSa3ZUACjtrp9v4T9xgWuj2R0V4TtFGoK79XBF4=,iv:gTnDcufYP7R2lTQ2bCpd5xq6z0qMwIAg+5kz+yzQZwE=,tag:YMTYIyh6m+Znbva9OrpAog==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:iFN7xrrPONjKKteyTg9rWTiST6w1DdMyUdSgl8UQG7HB91jGrJAvz9Xt3AGSdxg6ez8=,iv:IUa6YO0Lw9Ap+xdQY6DYfi54e0fZvU6hEqacvLNOE58=,tag:rPXkozwj6cnI6+8cKx2A0w==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:IbG/zOL9KhIH8i/vASgkEg==,iv:kRs1Po6XvciywQFYEVHj2qSH+B4li8zenzty16m5OAo=,tag:870+xx61hsP6oaNTrFdsXA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ZQEYqG8vwD/xYblhY/r6fUah0qUXym0KurtXgs9w+QdDoWoZ+3Hn5ZLF63LtfHtBSbo=,iv:wMjqKQgOtswxIxPlcJz8lCMHZ4/DZ57aAAfKcbI+XlU=,tag:EP6x5YyjwNObUwAPEkkbWA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtM0szdEkwbG00MGhUNzMx
            TUM3c0VWUkxaeG92WlZhdE00SGZkbSs3QTAwCnNmT21ia1BLU0pDTGl6OG4rOVBV
            dmZtemc1TFpmU0t1ODdNNjRGOENIVm8KLS0tIDhPUzBCU0tOclRiaDdPUUREamM0
            TjZQaW9oS0NsME9GbUxUOHBEWmtMSEUKxFqtGyMcJwSwRW4x7wdeaab9JuiyJ9cK
            rwCs+O1rMxiKntMMPc19LepbTvnUtdIUzMTOaa+uvsXevsiCpRVICg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    lastmodified: "2026-09-09T11:30:13Z"
    mac: ENC[AES256_GCM,data:1CdX8tYmjRRh8XzDO0o4+wXiwicTWNYgKc8WpQI+FF/tmWzM+HjVpvj4ZOQSUiucSzHhbW3to4quEPTjEfqT3FaH7hV+8xpmJurtgIhht1W6KkdR5NShxAW5TGXuCYKWJBVVYf5kuTxUUuoaCzyEY+NxwW0XUBptuCwwbJ6JCts=,iv:7iLHqjrPcsfGkNQasYaWQLRy/wClM4OeMzRVBJaDVyE=,tag:YpO2bFURD2QwqvTz+t9w7Q==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: volsync-samba-backup-claes-hedlund-macbook-secrets
    namespace: samba
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:TGekGpoAVtnxNXl8K3sJuzdOBfAVYBMcOmqOtLAZXPsE4+DdFufPzhOKIxdkXemSRPq1Y6b432GxJFfhD1z6gOJmV6x3m6yy3yJchrqxK8KT,iv:R14ewMfKLDccF+VM5qMR8d4K29dSS+mgBQsaLMcdaLY=,tag:7wS4W0S1vHnxCEznu48sQg==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:iFN7xrrPONjKKteyTg9rWTiST6w1DdMyUdSgl8UQG7HB91jGrJAvz9Xt3AGSdxg6ez8=,iv:IUa6YO0Lw9Ap+xdQY6DYfi54e0fZvU6hEqacvLNOE58=,tag:rPXkozwj6cnI6+8cKx2A0w==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:IbG/zOL9KhIH8i/vASgkEg==,iv:kRs1Po6XvciywQFYEVHj2qSH+B4li8zenzty16m5OAo=,tag:870+xx61hsP6oaNTrFdsXA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ZQEYqG8vwD/xYblhY/r6fUah0qUXym0KurtXgs9w+QdDoWoZ+3Hn5ZLF63LtfHtBSbo=,iv:wMjqKQgOtswxIxPlcJz8lCMHZ4/DZ57aAAfKcbI+XlU=,tag:EP6x5YyjwNObUwAPEkkbWA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtM0szdEkwbG00MGhUNzMx
            TUM3c0VWUkxaeG92WlZhdE00SGZkbSs3QTAwCnNmT21ia1BLU0pDTGl6OG4rOVBV
            dmZtemc1TFpmU0t1ODdNNjRGOENIVm8KLS0tIDhPUzBCU0tOclRiaDdPUUREamM0
            TjZQaW9oS0NsME9GbUxUOHBEWmtMSEUKxFqtGyMcJwSwRW4x7wdeaab9JuiyJ9cK
            rwCs+O1rMxiKntMMPc19LepbTvnUtdIUzMTOaa+uvsXevsiCpRVICg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    lastmodified: "2026-09-09T11:30:13Z"
    mac: ENC[AES256_GCM,data:1CdX8tYmjRRh8XzDO0o4+wXiwicTWNYgKc8WpQI+FF/tmWzM+HjVpvj4ZOQSUiucSzHhbW3to4quEPTjEfqT3FaH7hV+8xpmJurtgIhht1W6KkdR5NShxAW5TGXuCYKWJBVVYf5kuTxUUuoaCzyEY+NxwW0XUBptuCwwbJ6JCts=,iv:7iLHqjrPcsfGkNQasYaWQLRy/wClM4OeMzRVBJaDVyE=,tag:YpO2bFURD2QwqvTz+t9w7Q==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: volsync-samba-backup-asa-hedlund-secrets
    namespace: samba
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:RCscYA+nTUTcB5q4OhLaeHAMA6KYJJyX2TJvY+uInj+jL+tsCKHFo9Yo//0aM0ChLYr5XyduZ32U4NuNcMdI47QSg7r5wUE=,iv:1mtEGNJDZ3cUfygzuKkeFXG5cv9PloM02Wx7+QOybPY=,tag:UuzpEIbJYJEu4FpLml6ejQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:iFN7xrrPONjKKteyTg9rWTiST6w1DdMyUdSgl8UQG7HB91jGrJAvz9Xt3AGSdxg6ez8=,iv:IUa6YO0Lw9Ap+xdQY6DYfi54e0fZvU6hEqacvLNOE58=,tag:rPXkozwj6cnI6+8cKx2A0w==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:IbG/zOL9KhIH8i/vASgkEg==,iv:kRs1Po6XvciywQFYEVHj2qSH+B4li8zenzty16m5OAo=,tag:870+xx61hsP6oaNTrFdsXA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ZQEYqG8vwD/xYblhY/r6fUah0qUXym0KurtXgs9w+QdDoWoZ+3Hn5ZLF63LtfHtBSbo=,iv:wMjqKQgOtswxIxPlcJz8lCMHZ4/DZ57aAAfKcbI+XlU=,tag:EP6x5YyjwNObUwAPEkkbWA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtM0szdEkwbG00MGhUNzMx
            TUM3c0VWUkxaeG92WlZhdE00SGZkbSs3QTAwCnNmT21ia1BLU0pDTGl6OG4rOVBV
            dmZtemc1TFpmU0t1ODdNNjRGOENIVm8KLS0tIDhPUzBCU0tOclRiaDdPUUREamM0
            TjZQaW9oS0NsME9GbUxUOHBEWmtMSEUKxFqtGyMcJwSwRW4x7wdeaab9JuiyJ9cK
            rwCs+O1rMxiKntMMPc19LepbTvnUtdIUzMTOaa+uvsXevsiCpRVICg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    lastmodified: "2026-09-09T11:30:13Z"
    mac: ENC[AES256_GCM,data:1CdX8tYmjRRh8XzDO0o4+wXiwicTWNYgKc8WpQI+FF/tmWzM+HjVpvj4ZOQSUiucSzHhbW3to4quEPTjEfqT3FaH7hV+8xpmJurtgIhht1W6KkdR5NShxAW5TGXuCYKWJBVVYf5kuTxUUuoaCzyEY+NxwW0XUBptuCwwbJ6JCts=,iv:7iLHqjrPcsfGkNQasYaWQLRy/wClM4OeMzRVBJaDVyE=,tag:YpO2bFURD2QwqvTz+t9w7Q==,type:str]
    version: 3.13.3
