apiVersion: v1
kind: Secret
metadata:
    name: samba-netbird-secrets
    namespace: samba
type: Opaque
stringData:
    NB_SETUP_KEY: ENC[AES256_GCM,data:/xRDdd2CkBa+Il2pTA3Xy6K+SVXlVmPW7DqAThRmaseW9v1l,iv:eeI7sWIzkTAQOd8Kp9tFjcKxBuG9hwcWp2v0CYeaGxM=,tag:KlcJp1/hoPZwGbeVJ6g5EA==,type:str]
    NB_MANAGEMENT_URL: ENC[AES256_GCM,data:ekUHm0p4pLHy9x73Fz23j4blzg==,iv:8JMMxN6wyK/sm0rLtBiHH1K1cK+ptgQlcP4bWL6CIHg=,tag:1ODjJCk7HBjdY3GuFjmRxg==,type:str]
    NB_EXTRA_DNS_LABELS: ENC[AES256_GCM,data:s2S1yX4Pf6p9Ml9+dxPR,iv:qhI66fCE2KdCavyyPvNpVWzt9IzkHHqEVKPpT3zWsZM=,tag:wplvYwXVf4c7YJa5uKpBfQ==,type:str]
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtM0szdEkwbG00MGhUNzMx
            TUM3c0VWUkxaeG92WlZhdE00SGZkbSs3QTAwCnNmT21ia1BLU0pDTGl6OG4rOVBV
            dmZtemc1TFpmU0t1ODdNNjRGOENIVm8KLS0tIDhPUzBCU0tOclRiaDdPUUREamM0
            TjZQaW9oS0NsME9GbUxUOHBEWmtMSEUKxFqtGyMcJwSwRW4x7wdeaab9JuiyJ9cK
            rwCs+O1rMxiKntMMPc19LepbTvnUtdIUzMTOaa+uvsXevsiCpRVICg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-14T18:15:34Z"
    mac: ENC[AES256_GCM,data:UZ0rM6oAG4cRNYT3lHoWAk4vv8qkIFKsLEu4uKd0fv7XKtaMfboWDJ/5ku9GvPkQkvo7GH2v3e0H63mxjcEPNJKVtV3LY84ggvVW7mSG7G9lnIMmtv3p9HHXTC0LXNj6K/rrmeJ9NQLCUmfLigFuRaXASpER7XljSTljDOvatTw=,iv:PIWravGEKFq5/awfLkyzNgbisOAms6clE4zgjxy8WXM=,tag:Nk23JvRRslY6tnnWgj3Y5Q==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: samba-auth
    namespace: samba
type: Opaque
stringData:
    pass_andreas_hedlund: ENC[AES256_GCM,data:qw/gc4DJwWFzoRL2Ra+KzFVe4Nw7fGt4XrEe3VGguXYiGX6JzQPMO8Uz2DDicBuZT0k=,iv:5aGwkZ4RoV1FytOUTgBLK+Xh7bKiOX4eh0yOW8KXRnY=,tag:dTI2r8sfHo3pnwR5KfzTEg==,type:str]
    pass_claes_hedlund: ENC[AES256_GCM,data:AfXbBMuF1E2mPpJtp0KFfgOHJvopxTQNJ6qD7+k6utirxWDG6WBzio6MivIN0j4dZRs=,iv:j1KMJrOYjmcXGSGZQ0kte8yK5/RvfSsIWz2ICttggdY=,tag:VRxS1nmXtIMCEVQMwGuOYg==,type:str]
    pass_johanna_hedlund: ENC[AES256_GCM,data:lTMtKIMtkIux2FnCVAE1fsyD69GK5wAdp9sqnkZ77G2iMiBw9X6PovFOYGo/Vzgl8xU=,iv:xIuYFxM8GBGHqEn8PbvYjcUlX3Gj6iHlPyLE+emmZcM=,tag:TjAKz9859eRuqpAkCLw+Kw==,type:str]
    pass_ha_lahalla: ENC[AES256_GCM,data:jahDaPVaZkJCgntxNpZ/aQ/hmnWqo/5W52s94RhtUZ6j2nw0URcWLrLMV0PNiD6/GJE=,iv:LcEPwhFFmvwGV/au4uuZyw4b9r3fzuky2A7KbQ6dpzc=,tag:PDGjx2/adpyLlWaoawfmOg==,type:str]
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtM0szdEkwbG00MGhUNzMx
            TUM3c0VWUkxaeG92WlZhdE00SGZkbSs3QTAwCnNmT21ia1BLU0pDTGl6OG4rOVBV
            dmZtemc1TFpmU0t1ODdNNjRGOENIVm8KLS0tIDhPUzBCU0tOclRiaDdPUUREamM0
            TjZQaW9oS0NsME9GbUxUOHBEWmtMSEUKxFqtGyMcJwSwRW4x7wdeaab9JuiyJ9cK
            rwCs+O1rMxiKntMMPc19LepbTvnUtdIUzMTOaa+uvsXevsiCpRVICg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-14T18:15:34Z"
    mac: ENC[AES256_GCM,data:UZ0rM6oAG4cRNYT3lHoWAk4vv8qkIFKsLEu4uKd0fv7XKtaMfboWDJ/5ku9GvPkQkvo7GH2v3e0H63mxjcEPNJKVtV3LY84ggvVW7mSG7G9lnIMmtv3p9HHXTC0LXNj6K/rrmeJ9NQLCUmfLigFuRaXASpER7XljSTljDOvatTw=,iv:PIWravGEKFq5/awfLkyzNgbisOAms6clE4zgjxy8WXM=,tag:Nk23JvRRslY6tnnWgj3Y5Q==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: volsync-svtplay-dl-secrets
    namespace: svtplay-dl
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:YhLZL1TNs/veiztMGKbxs8hoVR+/LdJZsNPAzk31twaEaTei40szN4IQKc9Y+BAEQBVLbdU+SKMD,iv:YOQFTIcrRki5QvhtpkNGxZq8fnxoEcCXg3kZ+Db5byc=,tag:4eTWICcBsr387bz+zlPTQQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:iFN7xrrPONjKKteyTg9rWTiST6w1DdMyUdSgl8UQG7HB91jGrJAvz9Xt3AGSdxg6ez8=,iv:IUa6YO0Lw9Ap+xdQY6DYfi54e0fZvU6hEqacvLNOE58=,tag:rPXkozwj6cnI6+8cKx2A0w==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:IbG/zOL9KhIH8i/vASgkEg==,iv:kRs1Po6XvciywQFYEVHj2qSH+B4li8zenzty16m5OAo=,tag:870+xx61hsP6oaNTrFdsXA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ZQEYqG8vwD/xYblhY/r6fUah0qUXym0KurtXgs9w+QdDoWoZ+3Hn5ZLF63LtfHtBSbo=,iv:wMjqKQgOtswxIxPlcJz8lCMHZ4/DZ57aAAfKcbI+XlU=,tag:EP6x5YyjwNObUwAPEkkbWA==,type:str]
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtM0szdEkwbG00MGhUNzMx
            TUM3c0VWUkxaeG92WlZhdE00SGZkbSs3QTAwCnNmT21ia1BLU0pDTGl6OG4rOVBV
            dmZtemc1TFpmU0t1ODdNNjRGOENIVm8KLS0tIDhPUzBCU0tOclRiaDdPUUREamM0
            TjZQaW9oS0NsME9GbUxUOHBEWmtMSEUKxFqtGyMcJwSwRW4x7wdeaab9JuiyJ9cK
            rwCs+O1rMxiKntMMPc19LepbTvnUtdIUzMTOaa+uvsXevsiCpRVICg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-14T18:15:34Z"
    mac: ENC[AES256_GCM,data:UZ0rM6oAG4cRNYT3lHoWAk4vv8qkIFKsLEu4uKd0fv7XKtaMfboWDJ/5ku9GvPkQkvo7GH2v3e0H63mxjcEPNJKVtV3LY84ggvVW7mSG7G9lnIMmtv3p9HHXTC0LXNj6K/rrmeJ9NQLCUmfLigFuRaXASpER7XljSTljDOvatTw=,iv:PIWravGEKFq5/awfLkyzNgbisOAms6clE4zgjxy8WXM=,tag:Nk23JvRRslY6tnnWgj3Y5Q==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: volsync-samba-backup-andreas-hedlund-m-fe-secrets
    namespace: samba
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:Ph235ZViggoVr4zsQySNgtDhWzY4hPkRR/uNlO6LvDESBtX0E4HEk+T0N+02kXME+P9232J8OZTHhtrl70+dtutwCTu/6H5+4wIM2kcMfuM=,iv:5uZoJzz4DWe248pkRQX2WjKftPAI9xTA4T/fmqZDMz4=,tag:uFpEEHaaDFZuSeyZ7jrRaQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:iFN7xrrPONjKKteyTg9rWTiST6w1DdMyUdSgl8UQG7HB91jGrJAvz9Xt3AGSdxg6ez8=,iv:IUa6YO0Lw9Ap+xdQY6DYfi54e0fZvU6hEqacvLNOE58=,tag:rPXkozwj6cnI6+8cKx2A0w==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:IbG/zOL9KhIH8i/vASgkEg==,iv:kRs1Po6XvciywQFYEVHj2qSH+B4li8zenzty16m5OAo=,tag:870+xx61hsP6oaNTrFdsXA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ZQEYqG8vwD/xYblhY/r6fUah0qUXym0KurtXgs9w+QdDoWoZ+3Hn5ZLF63LtfHtBSbo=,iv:wMjqKQgOtswxIxPlcJz8lCMHZ4/DZ57aAAfKcbI+XlU=,tag:EP6x5YyjwNObUwAPEkkbWA==,type:str]
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtM0szdEkwbG00MGhUNzMx
            TUM3c0VWUkxaeG92WlZhdE00SGZkbSs3QTAwCnNmT21ia1BLU0pDTGl6OG4rOVBV
            dmZtemc1TFpmU0t1ODdNNjRGOENIVm8KLS0tIDhPUzBCU0tOclRiaDdPUUREamM0
            TjZQaW9oS0NsME9GbUxUOHBEWmtMSEUKxFqtGyMcJwSwRW4x7wdeaab9JuiyJ9cK
            rwCs+O1rMxiKntMMPc19LepbTvnUtdIUzMTOaa+uvsXevsiCpRVICg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-14T18:15:34Z"
    mac: ENC[AES256_GCM,data:UZ0rM6oAG4cRNYT3lHoWAk4vv8qkIFKsLEu4uKd0fv7XKtaMfboWDJ/5ku9GvPkQkvo7GH2v3e0H63mxjcEPNJKVtV3LY84ggvVW7mSG7G9lnIMmtv3p9HHXTC0LXNj6K/rrmeJ9NQLCUmfLigFuRaXASpER7XljSTljDOvatTw=,iv:PIWravGEKFq5/awfLkyzNgbisOAms6clE4zgjxy8WXM=,tag:Nk23JvRRslY6tnnWgj3Y5Q==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: volsync-samba-backup-ha-lahalla-secrets
    namespace: samba
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:KgsntWVjJ86AWnu2D3Q6ZhyWMIHIbfe22miy8HpvWB7LiU/E97sulB/aE7p0bw19NND/bMNtx8bc79pH9UJJ84VcnIqHYQ==,iv:eHhxORvNn/fgLVd4518awrJl9JVFqrBw4tyqISZD2P0=,tag:YeLzcb9YOBFGmm6peFfgYA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:iFN7xrrPONjKKteyTg9rWTiST6w1DdMyUdSgl8UQG7HB91jGrJAvz9Xt3AGSdxg6ez8=,iv:IUa6YO0Lw9Ap+xdQY6DYfi54e0fZvU6hEqacvLNOE58=,tag:rPXkozwj6cnI6+8cKx2A0w==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:IbG/zOL9KhIH8i/vASgkEg==,iv:kRs1Po6XvciywQFYEVHj2qSH+B4li8zenzty16m5OAo=,tag:870+xx61hsP6oaNTrFdsXA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ZQEYqG8vwD/xYblhY/r6fUah0qUXym0KurtXgs9w+QdDoWoZ+3Hn5ZLF63LtfHtBSbo=,iv:wMjqKQgOtswxIxPlcJz8lCMHZ4/DZ57aAAfKcbI+XlU=,tag:EP6x5YyjwNObUwAPEkkbWA==,type:str]
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtM0szdEkwbG00MGhUNzMx
            TUM3c0VWUkxaeG92WlZhdE00SGZkbSs3QTAwCnNmT21ia1BLU0pDTGl6OG4rOVBV
            dmZtemc1TFpmU0t1ODdNNjRGOENIVm8KLS0tIDhPUzBCU0tOclRiaDdPUUREamM0
            TjZQaW9oS0NsME9GbUxUOHBEWmtMSEUKxFqtGyMcJwSwRW4x7wdeaab9JuiyJ9cK
            rwCs+O1rMxiKntMMPc19LepbTvnUtdIUzMTOaa+uvsXevsiCpRVICg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-14T18:15:34Z"
    mac: ENC[AES256_GCM,data:UZ0rM6oAG4cRNYT3lHoWAk4vv8qkIFKsLEu4uKd0fv7XKtaMfboWDJ/5ku9GvPkQkvo7GH2v3e0H63mxjcEPNJKVtV3LY84ggvVW7mSG7G9lnIMmtv3p9HHXTC0LXNj6K/rrmeJ9NQLCUmfLigFuRaXASpER7XljSTljDOvatTw=,iv:PIWravGEKFq5/awfLkyzNgbisOAms6clE4zgjxy8WXM=,tag:Nk23JvRRslY6tnnWgj3Y5Q==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: volsync-samba-backup-johanna-hedlund-secrets
    namespace: samba
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:OfyDjGx5We7gDPvmIOpCdhqUyff5utbS+ZRNMzsD88k6M5fAtxm+dBWrLV6ZRjAfzYmafLNLESb1fjZ/COqJBSyUs+3VV+g4pUNx,iv:fXK4n9i7ElRtBy+HZuHUSt4k/Zwf/i77xEKb5TU5Tuo=,tag:9J2Thbzt/crDyxjTNK6WYA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:iFN7xrrPONjKKteyTg9rWTiST6w1DdMyUdSgl8UQG7HB91jGrJAvz9Xt3AGSdxg6ez8=,iv:IUa6YO0Lw9Ap+xdQY6DYfi54e0fZvU6hEqacvLNOE58=,tag:rPXkozwj6cnI6+8cKx2A0w==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:IbG/zOL9KhIH8i/vASgkEg==,iv:kRs1Po6XvciywQFYEVHj2qSH+B4li8zenzty16m5OAo=,tag:870+xx61hsP6oaNTrFdsXA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ZQEYqG8vwD/xYblhY/r6fUah0qUXym0KurtXgs9w+QdDoWoZ+3Hn5ZLF63LtfHtBSbo=,iv:wMjqKQgOtswxIxPlcJz8lCMHZ4/DZ57aAAfKcbI+XlU=,tag:EP6x5YyjwNObUwAPEkkbWA==,type:str]
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtM0szdEkwbG00MGhUNzMx
            TUM3c0VWUkxaeG92WlZhdE00SGZkbSs3QTAwCnNmT21ia1BLU0pDTGl6OG4rOVBV
            dmZtemc1TFpmU0t1ODdNNjRGOENIVm8KLS0tIDhPUzBCU0tOclRiaDdPUUREamM0
            TjZQaW9oS0NsME9GbUxUOHBEWmtMSEUKxFqtGyMcJwSwRW4x7wdeaab9JuiyJ9cK
            rwCs+O1rMxiKntMMPc19LepbTvnUtdIUzMTOaa+uvsXevsiCpRVICg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-14T18:15:34Z"
    mac: ENC[AES256_GCM,data:UZ0rM6oAG4cRNYT3lHoWAk4vv8qkIFKsLEu4uKd0fv7XKtaMfboWDJ/5ku9GvPkQkvo7GH2v3e0H63mxjcEPNJKVtV3LY84ggvVW7mSG7G9lnIMmtv3p9HHXTC0LXNj6K/rrmeJ9NQLCUmfLigFuRaXASpER7XljSTljDOvatTw=,iv:PIWravGEKFq5/awfLkyzNgbisOAms6clE4zgjxy8WXM=,tag:Nk23JvRRslY6tnnWgj3Y5Q==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: volsync-samba-nas-secrets
    namespace: samba
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:ik8/34xHJ3iyo3RIitd81wQ2sJM0LA9ITxDlXSa3ZUACjtrp9v4T9xgWuj2R0V4TtFGoK79XBF4=,iv:gTnDcufYP7R2lTQ2bCpd5xq6z0qMwIAg+5kz+yzQZwE=,tag:YMTYIyh6m+Znbva9OrpAog==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:iFN7xrrPONjKKteyTg9rWTiST6w1DdMyUdSgl8UQG7HB91jGrJAvz9Xt3AGSdxg6ez8=,iv:IUa6YO0Lw9Ap+xdQY6DYfi54e0fZvU6hEqacvLNOE58=,tag:rPXkozwj6cnI6+8cKx2A0w==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:IbG/zOL9KhIH8i/vASgkEg==,iv:kRs1Po6XvciywQFYEVHj2qSH+B4li8zenzty16m5OAo=,tag:870+xx61hsP6oaNTrFdsXA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ZQEYqG8vwD/xYblhY/r6fUah0qUXym0KurtXgs9w+QdDoWoZ+3Hn5ZLF63LtfHtBSbo=,iv:wMjqKQgOtswxIxPlcJz8lCMHZ4/DZ57aAAfKcbI+XlU=,tag:EP6x5YyjwNObUwAPEkkbWA==,type:str]
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtM0szdEkwbG00MGhUNzMx
            TUM3c0VWUkxaeG92WlZhdE00SGZkbSs3QTAwCnNmT21ia1BLU0pDTGl6OG4rOVBV
            dmZtemc1TFpmU0t1ODdNNjRGOENIVm8KLS0tIDhPUzBCU0tOclRiaDdPUUREamM0
            TjZQaW9oS0NsME9GbUxUOHBEWmtMSEUKxFqtGyMcJwSwRW4x7wdeaab9JuiyJ9cK
            rwCs+O1rMxiKntMMPc19LepbTvnUtdIUzMTOaa+uvsXevsiCpRVICg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-14T18:15:34Z"
    mac: ENC[AES256_GCM,data:UZ0rM6oAG4cRNYT3lHoWAk4vv8qkIFKsLEu4uKd0fv7XKtaMfboWDJ/5ku9GvPkQkvo7GH2v3e0H63mxjcEPNJKVtV3LY84ggvVW7mSG7G9lnIMmtv3p9HHXTC0LXNj6K/rrmeJ9NQLCUmfLigFuRaXASpER7XljSTljDOvatTw=,iv:PIWravGEKFq5/awfLkyzNgbisOAms6clE4zgjxy8WXM=,tag:Nk23JvRRslY6tnnWgj3Y5Q==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: volsync-samba-backup-claes-hedlund-secrets
    namespace: samba
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:foePjomuMvWLXsmhyJgwkEPPd7FiFzQibTH7CfDtukQYMtor7/2k98q0bsy39+1AcUggpsqMnJufNHGSzDjjlrM31TxR9JcHng==,iv:9m9JNvkhtP5CaZFW/Ta7EklEJtWa9lbSepHVqUipbGw=,tag:if0yk3ggUB9GkJJKxKgoSQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:iFN7xrrPONjKKteyTg9rWTiST6w1DdMyUdSgl8UQG7HB91jGrJAvz9Xt3AGSdxg6ez8=,iv:IUa6YO0Lw9Ap+xdQY6DYfi54e0fZvU6hEqacvLNOE58=,tag:rPXkozwj6cnI6+8cKx2A0w==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:IbG/zOL9KhIH8i/vASgkEg==,iv:kRs1Po6XvciywQFYEVHj2qSH+B4li8zenzty16m5OAo=,tag:870+xx61hsP6oaNTrFdsXA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ZQEYqG8vwD/xYblhY/r6fUah0qUXym0KurtXgs9w+QdDoWoZ+3Hn5ZLF63LtfHtBSbo=,iv:wMjqKQgOtswxIxPlcJz8lCMHZ4/DZ57aAAfKcbI+XlU=,tag:EP6x5YyjwNObUwAPEkkbWA==,type:str]
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtM0szdEkwbG00MGhUNzMx
            TUM3c0VWUkxaeG92WlZhdE00SGZkbSs3QTAwCnNmT21ia1BLU0pDTGl6OG4rOVBV
            dmZtemc1TFpmU0t1ODdNNjRGOENIVm8KLS0tIDhPUzBCU0tOclRiaDdPUUREamM0
            TjZQaW9oS0NsME9GbUxUOHBEWmtMSEUKxFqtGyMcJwSwRW4x7wdeaab9JuiyJ9cK
            rwCs+O1rMxiKntMMPc19LepbTvnUtdIUzMTOaa+uvsXevsiCpRVICg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-14T18:15:34Z"
    mac: ENC[AES256_GCM,data:UZ0rM6oAG4cRNYT3lHoWAk4vv8qkIFKsLEu4uKd0fv7XKtaMfboWDJ/5ku9GvPkQkvo7GH2v3e0H63mxjcEPNJKVtV3LY84ggvVW7mSG7G9lnIMmtv3p9HHXTC0LXNj6K/rrmeJ9NQLCUmfLigFuRaXASpER7XljSTljDOvatTw=,iv:PIWravGEKFq5/awfLkyzNgbisOAms6clE4zgjxy8WXM=,tag:Nk23JvRRslY6tnnWgj3Y5Q==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    version: 3.12.2
