---
apiVersion: v1
kind: Service
metadata:
  name: samba
  namespace: samba
  annotations:
    io.cilium/lb-ipam-ips: "192.168.201.101"
spec:
  type: LoadBalancer
  selector:
    app: samba
  ports:
    - port: 445
      targetPort: 445
      name: smb
      protocol: TCP