---
apiVersion: cilium.io/v2
kind: CiliumEgressGatewayPolicy
metadata:
  name: exit-node-egress-path
spec:
  selectors:
    - podSelector:
        matchLabels:
          routing: vlan30-egress
          io.kubernetes.pod.namespace: tailscale-exit
  destinationCIDRs:
    - "0.0.0.0/0"
  excludedCIDRs:
    - "100.64.0.0/10"
    - "10.0.0.0/8"
    - "172.16.0.0/12"
    - "192.168.0.0/16"
  egressGateway:
    nodeSelector:
      matchLabels:
        egress-vlan30: "true"
    interface: enp0s20f0u8