---
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: exit-node
  namespace: tailscale-exit
spec:
  exitNode: true
  hostnamePrefix: s1-exit-node
  podTemplate:
    spec:
      containers:
        - name: tailscale
          env:
            - name: TS_DEBUG_FIREWALL_MODE
              value: "nftables"