---
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: exit-node
  namespace: tailscale-exit
spec:
  exitNode: true
  proxyClassName: infra-node-allowed
  hostnamePrefix: s1-exit-node