---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: iperf3-server
resources:
  - namespace.yaml
  - secrets.enc.yaml
  - pvc.yaml
  - helmrepository.yaml
  - helmrelease.yaml