---
apiVersion: netbird.io/v1alpha1
kind: NetworkResource
metadata:
  name: iperf3-s1-main01
  namespace: iperf3-server
spec:
  networkRouterRef:
    name: s1-main01
    namespace: netbird
  groups:
    - name: exit-node-s1-main01
      exitNode: true
  serviceRef:
    name: iperf3