apiVersion: v1
kind: Secret
metadata:
    name: iperf3-secrets
    namespace: iperf3-server
type: Opaque
stringData:
    NB_SETUP_KEY: ENC[AES256_GCM,data:4SqAVFYZZ8+yy5HzG3ahYCRwaLEwQ8lLzoCT5qgX4gcM1B0Z,iv:9Vr4mOGw8wyj/VrxfnJUDE5FMyDWy6N/3Vshh7F0ETU=,tag:FnmE5v9TDi68PwXpqVluuw==,type:str]
    NB_MANAGEMENT_URL: ENC[AES256_GCM,data:FkINPM0YL2pH87qg7i1BAfvZeg==,iv:80E6gkns573HPJw4uCzIopsxjyRznHurDbDO2AxLCtM=,tag:DhbAcxZRkw9Fl2ZFczlifw==,type:str]
    NB_EXTRA_DNS_LABELS: ENC[AES256_GCM,data:L0XcfE4oF4ju5UQ5zb6bvQ==,iv:wmW3ACm+fu0li99z7j8KhtSO9/LHPn5pyO43Ll6ebU0=,tag:6+VLZMt+VAsH4RBVJvrPQw==,type:str]
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvK1lYV2haZkF1a3c4c0Y2
            dFkzd3g5YXFzeDVLNkdSTElrdVEvQmorVlU4CmVJQkwxZlpxYjdDenFzOVVIT1FG
            U1JjbGRTTHIzUzBrN3drbkZVTkNBVGMKLS0tIG9rR2RaQnJuSkdTbTdtYlVGVTY4
            TnJKbUdaVTAxdzdXMEVIV0YwTDdvNGsKoQ5C//F/PTcu1coMWeX125MRMAquPYFb
            SicqCNaZCYiBd9kTs9PsvSEzNUsAd4mUY1QzwROCY0cr19pXEhqxRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-31T10:04:04Z"
    mac: ENC[AES256_GCM,data:utiWFW7Jeyu8SxLcnTodAYuOWmfTb1fIQyOeAWFhFVb0keGsXkr1SWvqSYDGDGuXmzOeOAKGznpyPca1Bu0wNG/Out1suRPMlJq3M8TE0N+KQIO3y3MN4iReglDgt/NiAZvZoGU6Qp8M+DcWweqOH54WaqlzEJo73BaMk4+/8hc=,iv:t/RQ84sgPOZZBxPzpKsZ67y1BHhpVgFo7BJdj4fJdEU=,tag:SV2eRyzgbCYXnIh3/42IHg==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    version: 3.12.2
