apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: svtplay-dl
  namespace: streaming
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ceph-fs-hdd-r2
  resources:
    requests:
      storage: 300Gi