apiVersion: v1
kind: Secret
metadata:
    name: volsync-svtplay-dl-secrets
    namespace: streaming
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:YhLZL1TNs/veiztMGKbxs8hoVR+/LdJZsNPAzk31twaEaTei40szN4IQKc9Y+BAEQBVLbdU+SKMD,iv:YOQFTIcrRki5QvhtpkNGxZq8fnxoEcCXg3kZ+Db5byc=,tag:4eTWICcBsr387bz+zlPTQQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:iFN7xrrPONjKKteyTg9rWTiST6w1DdMyUdSgl8UQG7HB91jGrJAvz9Xt3AGSdxg6ez8=,iv:IUa6YO0Lw9Ap+xdQY6DYfi54e0fZvU6hEqacvLNOE58=,tag:rPXkozwj6cnI6+8cKx2A0w==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:IbG/zOL9KhIH8i/vASgkEg==,iv:kRs1Po6XvciywQFYEVHj2qSH+B4li8zenzty16m5OAo=,tag:870+xx61hsP6oaNTrFdsXA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ZQEYqG8vwD/xYblhY/r6fUah0qUXym0KurtXgs9w+QdDoWoZ+3Hn5ZLF63LtfHtBSbo=,iv:wMjqKQgOtswxIxPlcJz8lCMHZ4/DZ57aAAfKcbI+XlU=,tag:EP6x5YyjwNObUwAPEkkbWA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtM0szdEkwbG00MGhUNzMx
            TUM3c0VWUkxaeG92WlZhdE00SGZkbSs3QTAwCnNmT21ia1BLU0pDTGl6OG4rOVBV
            dmZtemc1TFpmU0t1ODdNNjRGOENIVm8KLS0tIDhPUzBCU0tOclRiaDdPUUREamM0
            TjZQaW9oS0NsME9GbUxUOHBEWmtMSEUKxFqtGyMcJwSwRW4x7wdeaab9JuiyJ9cK
            rwCs+O1rMxiKntMMPc19LepbTvnUtdIUzMTOaa+uvsXevsiCpRVICg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    lastmodified: "2026-09-05T12:30:43Z"
    mac: ENC[AES256_GCM,data:cvK5grAt3UlN/9e6KyfOUg/55jBeZNmOOTQO1aZMYvFAA1EbG0JIoDSab4gB88fpR3wHOmYYZsKhUYDpmIJHctOzDj2/WdqvxoYAukj8JW2APMYnsquOQHFpHcc1QipHMly4dvyxfUaa60vtmqojQU50YdlaW3KAS3WGwt/j8K0=,iv:12vqKJmqXxZQCy8MbJe/NmhYg8Vgcd2NBG9viek7VHo=,tag:nVPZxpvU/va/OR54TKgPGg==,type:str]
    version: 3.13.3
