---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-universal-crush-rule
  namespace: rook-ceph
spec:
  template:
    spec:
      serviceAccountName: rook-ceph-osd
      containers:
      - name: ceph-cli
        image: rook/ceph:v1.19.5
        command: ["/bin/bash", "-c"]
        args:
          - |
            mkdir -p /etc/ceph
            CLEAN_MONS=$(cat /etc/rook/data | sed 's/[a-z]=//g')
            cat <<EOF > /etc/ceph/ceph.conf
            [global]
            mon_host = $CLEAN_MONS
            EOF
            ceph -n client.admin -k /etc/ceph/keyring-store/keyring osd crush rule create-replicated all_devices_osd_rule default osd
        volumeMounts:
        - name: ceph-config
          mountPath: /etc/ceph
        - name: mon-endpoint-volume
          mountPath: /etc/rook
        - name: admin-keyring
          mountPath: /etc/ceph/keyring-store
      restartPolicy: OnFailure
      volumes:
      - name: ceph-config
        emptyDir: {}
      - name: mon-endpoint-volume
        configMap:
          name: rook-ceph-mon-endpoints
          items:
          - key: data
            path: data
      - name: admin-keyring
        secret:
          secretName: rook-ceph-admin-keyring
---
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: builtin-mgr
  namespace: rook-ceph
spec:
  name: .mgr
  failureDomain: osd
  replicated:
    size: 3
    requireSafeReplicaSize: false
    targetSizeRatio: .01
  parameters:
    crush_rule: all_devices_osd_rule