---
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: quay.io/ceph/ceph:v19.2.3
    allowUnsupported: false
  dataDirHostPath: /var/lib/rook
  priorityClassNames:
    mon: high-priority
    osd: low-priority
    prepareosd: low-priority
    mgr: high-priority
    crashcollector: low-priority
    exporter: low-priority
  cephConfig:
    global:
      osd_pool_default_size: "2"
      osd_pool_default_min_size: "1"
#      osd_crush_chooseleaf_type: "0"
      osd_pool_default_crush_rule: "0"
      osd_memory_target: "1073741824"
      osd_memory_base: "268435456"
      osd_memory_cache_min: "134217728"
      bluestore_cache_size: "536870912"
  mon:
    count: 1
    allowMultiplePerNode: true
  mgr:
    count: 1
    allowMultiplePerNode: true
  dashboard:
    enabled: true
    ssl: false
  storage:
    useAllNodes: false
    useAllDevices: false
    config:
        encryptedDevice: "true"
    nodes:
      - name: s1-main01-cpwr01
        devices:
          - name: /dev/disk/by-id/wwn-0x50014ee217016a21
          - name: /dev/disk/by-id/wwn-0x5000039da8d00a9a
          - name: /dev/disk/by-id/nvme-eui.001b448b4b44c26c