---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cephcluster.yaml
  - builtin-pools.yaml
  - cephblockpool.yaml
  - cephobjectstore.yaml
  - cephfilesystem.yaml
  - cephnfs.yaml
  - toolbox.yaml