apiVersion: v1
kind: LimitRange
metadata:
  name: rook-ceph-default-limits
  namespace: rook-ceph
spec:
  limits:
  - default:
      cpu: 300m
      memory: 256Mi
    defaultRequest:
      cpu: 50m
      memory: 56Mi
    type: Container