apiVersion: v1
data:
    mon_host: ENC[AES256_GCM,data:rR2gNQ1Q7IjsA2ke+EqvVGGcKiPnmPBqo6Ie/h42lWtOehDQBR3o8J0+CzuRUMllDrqptXkw9KcYVDCIkHM2dA==,iv:3ONpomgC21nmLFNGL74KetNNlkWm7IYF56rwk8cb9Yo=,tag:O3CiqBFfh+wZsMFRh2yHOw==,type:str]
    mon_initial_members: ENC[AES256_GCM,data:6jvPJw==,iv:nletxfPXNpZX1ZlIVv3KMsLS3Pvg4t4Jh3Tlu9seSlE=,tag:bvr0JD9TZTaRwAcA+W/W2w==,type:str]
kind: Secret
metadata:
    name: rook-ceph-config
    namespace: rook-ceph
type: kubernetes.io/rook
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDTk5UaC9wRWZpRzB6a2Fv
            K2RkS1ArNXJjSm1pMTBIMkVhbERtQURySmpjCk9WdStTemswSkg4TEQ2cXZPWHZr
            a0ZtV082L2U1d0NGemFwWmx2TlhYZE0KLS0tIEpuczhDUXBqS1grTEFqVlN6OGVn
            M0svcGh4Q0lpNjM1T2k3WHJJMmduUVEKxqhf6hDk6mRmACg+dE0UJJCbB3tkNtvK
            p+paJ++E0vb57d1Sayaigu9jbrrFiNhFiQuMuW9gsXIs5xQRLDag6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-17T08:32:23Z"
    mac: ENC[AES256_GCM,data:QtOjmjDDK3FOckp9I+XftlTWGv07S/GZZy2atOKHtXHLsMPR3J+LJvbThaUulGNyTeOPKFOUs0O6Feibs39B4URcQLSgufCpJHmlRObiextBl/9HtTkC8GDEFyMC9JFI9f0i/l/DdIzDv/nLRDl6gPPvS/eTRcxJZ6U11h3gw3w=,iv:C0QoRk9cuLmn6YQDYSYJURtZcd00DZPs2a8YW/3bjto=,tag:YLl1Sg2pPlX1DXINubQmzw==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|mon_host|mon_initial_members|ceph-secret|ceph-username|fsid|mon-secret)$
    version: 3.12.2
