apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: vaultwarden
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      containers:
        - name: vaultwarden
          image: vaultwarden/server:1.37.2
          ports:
            - containerPort: 80
          env:
            - name: DOMAIN
              valueFrom:
                secretKeyRef:
                  name: vaultwarden-secrets
                  key: domain
            - name: ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vaultwarden-secrets
                  key: admin-token
            - name: SIGNUPS_ALLOWED
              value: "false"
            - name: WEBSOCKET_ENABLED
              value: "true"
          resources:
            requests:
              cpu: "10m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "512Mi"
          volumeMounts:
            - name: data
              mountPath: /data

        - name: caddy
          image: caddy:2
          ports:
            - containerPort: 443
          resources:
            requests:
              cpu: "10m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
          volumeMounts:
            - name: caddy-config
              mountPath: /etc/caddy/Caddyfile
              subPath: Caddyfile
            - name: ssl-certs
              mountPath: /certs
              readOnly: true

        - name: netbird
          image: netbirdio/netbird:0.77.0
          env:
            - name: NB_HOSTNAME
              value: vaultwarden-s1-main01
            # - name: NB_DISABLE_DNS
            #   value: "true"
          envFrom:
            - secretRef:
                name: vaultwarden-secrets
          resources:
            requests:
              cpu: "10m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          volumeMounts:
            - name: netbird-state
              mountPath: /var/lib/netbird

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: vaultwarden-data
        - name: ssl-certs
          secret:
            secretName: vault-tls
        - name: caddy-config
          configMap:
            name: vaultwarden-caddyfile
        - name: netbird-state
          persistentVolumeClaim:
            claimName: vaultwarden-netbird