apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: vaultwarden-data-backup
  namespace: vaultwarden
spec:
  sourcePVC: vaultwarden-data
  trigger:
    schedule: "*/15 * * * *"
  restic:
    copyMethod: Snapshot
    volumeSnapshotClassName: csi-cephfsplugin-snapclass
    repository: volsync-vaultwarden-secrets
    pruneIntervalDays: 28
    cacheAccessModes:
      - ReadWriteOnce
    cacheCapacity: 5Gi
    cacheStorageClassName: ceph-rbd-nvme-r1
    storageClassName: ceph-fs-hdd-r2
    moverSecurityContext:
      fsGroupChangePolicy: OnRootMismatch
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    retain:
      hourly: 24
      daily: 7
      weekly: 4
      monthly: 12
      yearly: 3