apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secrets
    namespace: vaultwarden
stringData:
    domain: ENC[AES256_GCM,data:3Zzp40Pq02lNpE1MoqdanU+87J/2iXnuxQ==,iv:CBizgkU6SMWkCvgADFnvB0xpIsCN3veF4EkFaRA5V+g=,tag:MipDryyOd/GoXlrdoLJ3pA==,type:str]
    admin-token: ENC[AES256_GCM,data:NeQ1HzlrLWeMCTttkkk+Nh4Hy58jgZ/rfV2fTYXwWoxocv2GY6cxKTwaOe/fXeH43e/RdIGYO/RNvWsVVQ6EoiYarTmPiKmhVRRPD2todn01Wgm9DI+NgPD+GnfR2eWTafNV9d26qI5okd0=,iv:Vw4hA0Tv6Ztkq3qyJlXItkyXbIsp3CsEXPbmekm71LM=,tag:U2fd2jh2OoWLmP4oaCTs4Q==,type:str]
    admin-token_unhashed: ENC[AES256_GCM,data:ARHMuhG/0Z4Q9tIuJJj3n7vRkGA4ZyrzTCGJdIgGEb6nRLOU7Evkesb/v9Bz8mXaZ127TE+Dpq8PKACOAUvFZA==,iv:fkZwjuXmBTkHyA6A1ciYQ9cdrxg0ctj1x4eum6vrikI=,tag:GREIKaSltUxfisVr/en6QA==,type:str]
    NB_SETUP_KEY: ENC[AES256_GCM,data:wQAvTt7PFafVUF1k0MLvYzGQbJV3lGsi5umFxb29kAKnx9To,iv:u3ZSeBPj0pX2ZLHKEynsfSuY8rF4bhJnPg+5RMivF8A=,tag:MEjxXUyIDj0gWnbG4Ke0+A==,type:str]
    NB_MANAGEMENT_URL: ENC[AES256_GCM,data:L47cO+DAAb+8MxlrYo7n6KehIw==,iv:W8nq5RZwt1QS93IL1t/mcy0Wm6ngSktDdSGI1MQ4c0A=,tag:n5waSUVzUyHgPvt1CbwvGQ==,type:str]
    NB_EXTRA_DNS_LABELS: ENC[AES256_GCM,data:fEZrp68=,iv:kH2mkADS8/qr1Nf31MieyovjUCN5OvpFrl3oh0BqBfM=,tag:dHEd6rlfFML7qED7bEbkvQ==,type:str]
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeXBwTkF4WDUwT3Q4RGpV
            ZnNMeFF0bU1QYjI2UitMUHdIbGoycUJTWmpNCnQ4WnNuMFpHUFpwM3lpbnN1bHBP
            T0FtSTJEZ254Qkl3VEwwc3g0TmNYaG8KLS0tIE5zYzVkTHcwZURDRmtYNWN0THVz
            ZDJndVVzV1ZiK3daNXQ5N1A3Q25leWMKs+n2XnTych5naMF/Zo5LfoDUx5CuScJx
            jsf+jmuv4mo+Y/TJItgwuH1fQjlhzyqojSTSg83Yqnb/e9yzuNgvdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-06T12:54:53Z"
    mac: ENC[AES256_GCM,data:D2cl25HkJIfHz8VHI00Srb+IX4kwDSRV+rVMUU3lVC+jU/fjDA7KNhiAiL++JY2HV2x3vAfFWKb89wCGXx1z8DOTTYsTU4cf2gMzJCq3cAl4TDCS4GRFHiG5+VNVbi8mg4dy5sqQiXIFkZduZs8IbhiNqLSBTg/hlO0+S9O5EBs=,iv:gtKsakfp/dIAwBh4kDj+zY0UM1/CITFYSI3lZmmOSYY=,tag:sPnaTZFkjdLZyLj8ebl+QA==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: volsync-vaultwarden-secrets
    namespace: vaultwarden
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:0QvxY60Wjsjdo5nDPoM7CEiEduazWKx7SN8sE+pOgPlpBzPPSmwDuMG9qXguBy6pZT6seDCy1Xaw,iv:rjhaEuUdeDyaRQdnVRcl5y1bBxeqmcZgUONwMqnYhdU=,tag:Idbasj7aEIq67FwCmBEB2Q==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:sTHm6m9lMnWSIkZ3bXSa6GRq019OxhutvTWDXWlf7wolYeDBRW1uASEUb4ZxbMinlM0=,iv:ORUewfXU8ym4TnpO3+uN/vYlaogn1aWMmjycDGvo79c=,tag:0hcXOLTtXKgQkd2UKcriDQ==,type:str]
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeXBwTkF4WDUwT3Q4RGpV
            ZnNMeFF0bU1QYjI2UitMUHdIbGoycUJTWmpNCnQ4WnNuMFpHUFpwM3lpbnN1bHBP
            T0FtSTJEZ254Qkl3VEwwc3g0TmNYaG8KLS0tIE5zYzVkTHcwZURDRmtYNWN0THVz
            ZDJndVVzV1ZiK3daNXQ5N1A3Q25leWMKs+n2XnTych5naMF/Zo5LfoDUx5CuScJx
            jsf+jmuv4mo+Y/TJItgwuH1fQjlhzyqojSTSg83Yqnb/e9yzuNgvdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-06T12:54:53Z"
    mac: ENC[AES256_GCM,data:D2cl25HkJIfHz8VHI00Srb+IX4kwDSRV+rVMUU3lVC+jU/fjDA7KNhiAiL++JY2HV2x3vAfFWKb89wCGXx1z8DOTTYsTU4cf2gMzJCq3cAl4TDCS4GRFHiG5+VNVbi8mg4dy5sqQiXIFkZduZs8IbhiNqLSBTg/hlO0+S9O5EBs=,iv:gtKsakfp/dIAwBh4kDj+zY0UM1/CITFYSI3lZmmOSYY=,tag:sPnaTZFkjdLZyLj8ebl+QA==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    version: 3.12.2
