apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secrets
    namespace: vaultwarden
stringData:
    domain: ENC[AES256_GCM,data:3Zzp40Pq02lNpE1MoqdanU+87J/2iXnuxQ==,iv:CBizgkU6SMWkCvgADFnvB0xpIsCN3veF4EkFaRA5V+g=,tag:MipDryyOd/GoXlrdoLJ3pA==,type:str]
    admin-token: ENC[AES256_GCM,data:NeQ1HzlrLWeMCTttkkk+Nh4Hy58jgZ/rfV2fTYXwWoxocv2GY6cxKTwaOe/fXeH43e/RdIGYO/RNvWsVVQ6EoiYarTmPiKmhVRRPD2todn01Wgm9DI+NgPD+GnfR2eWTafNV9d26qI5okd0=,iv:Vw4hA0Tv6Ztkq3qyJlXItkyXbIsp3CsEXPbmekm71LM=,tag:U2fd2jh2OoWLmP4oaCTs4Q==,type:str]
    admin-token_unhashed: ENC[AES256_GCM,data:ARHMuhG/0Z4Q9tIuJJj3n7vRkGA4ZyrzTCGJdIgGEb6nRLOU7Evkesb/v9Bz8mXaZ127TE+Dpq8PKACOAUvFZA==,iv:fkZwjuXmBTkHyA6A1ciYQ9cdrxg0ctj1x4eum6vrikI=,tag:GREIKaSltUxfisVr/en6QA==,type:str]
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeXBwTkF4WDUwT3Q4RGpV
            ZnNMeFF0bU1QYjI2UitMUHdIbGoycUJTWmpNCnQ4WnNuMFpHUFpwM3lpbnN1bHBP
            T0FtSTJEZ254Qkl3VEwwc3g0TmNYaG8KLS0tIE5zYzVkTHcwZURDRmtYNWN0THVz
            ZDJndVVzV1ZiK3daNXQ5N1A3Q25leWMKs+n2XnTych5naMF/Zo5LfoDUx5CuScJx
            jsf+jmuv4mo+Y/TJItgwuH1fQjlhzyqojSTSg83Yqnb/e9yzuNgvdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-26T09:57:20Z"
    mac: ENC[AES256_GCM,data:2f5g1/+BkfUe+sqoNTH8ZzmJ09Qplsah7s5t3R4NE5xt+n3456C4maTxoholhuQEPxkRScaw3DXKjUBCXHeTCiAAqzG42MWWQrKGYpTzGsuvMVgHlTbXa9POctOOGbfvnm1wmf5h01ekdk6pWnogn8GeO3cVC6tLldA3N2D2tlU=,iv:aAFCAOEOwpjEANMc3nJe7HYGq+Rd//6roeP9GcVQI9w=,tag:2e/0mC46Ahbyt81fcs1TiA==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    version: 3.12.2
