apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secrets
    namespace: vaultwarden
stringData:
    domain: ENC[AES256_GCM,data:3Zzp40Pq02lNpE1MoqdanU+87J/2iXnuxQ==,iv:CBizgkU6SMWkCvgADFnvB0xpIsCN3veF4EkFaRA5V+g=,tag:MipDryyOd/GoXlrdoLJ3pA==,type:str]
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeXBwTkF4WDUwT3Q4RGpV
            ZnNMeFF0bU1QYjI2UitMUHdIbGoycUJTWmpNCnQ4WnNuMFpHUFpwM3lpbnN1bHBP
            T0FtSTJEZ254Qkl3VEwwc3g0TmNYaG8KLS0tIE5zYzVkTHcwZURDRmtYNWN0THVz
            ZDJndVVzV1ZiK3daNXQ5N1A3Q25leWMKs+n2XnTych5naMF/Zo5LfoDUx5CuScJx
            jsf+jmuv4mo+Y/TJItgwuH1fQjlhzyqojSTSg83Yqnb/e9yzuNgvdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-25T19:38:54Z"
    mac: ENC[AES256_GCM,data:zueOy4a4zNsfusVaP8j0zfMtL4QobXnw0jW+e8cfvlNrgl5NTRGjHIP575Qx2jx5UvFbYB/o4hW4kVl9Ex+fzTReXZ4PaVlHxQeZW/CXSHbaDQSuj/fNJsnRU3E56pi8MrFoXlBXsxpm8jE1tG3trJZsV+0CMIdEunElArm25vA=,iv:sepr5jraKUoQo91qtqzO0AhDyiUd2k/W3rDg+qIPsXs=,tag:jGg+CPYuOBlVUbV1jRa82A==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    version: 3.12.2
