apiVersion: v1
kind: Service
metadata:
  name: vaultwarden
  namespace: vaultwarden
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ${DNS_NAME_VAULTWARDEN}
spec:
  selector:
    app: vaultwarden
  ports:
    - port: 80
      targetPort: 80