---
apiVersion: v1
kind: Service
metadata:
  name: audiobookshelf
  namespace: podcast
  annotations:
    io.cilium/lb-ipam-ips: "192.168.201.115"
spec:
  type: LoadBalancer
  selector:
    app: audiobookshelf
  ports:
    - port: 80
      targetPort: 80
      name: http
      protocol: TCP