---
apiVersion: cilium.io/v2
kind: CiliumEgressGatewayPolicy
metadata:
  name: exit-node-egress-path
spec:
  selectors:
    - podSelector:
        matchLabels:
          app: exit-node
          io.kubernetes.pod.namespace: tailscale-exit
  destinationCIDRs:
    - "0.0.0.0/0"
  excludedCIDRs:
    - "10.101.0.0/17"
    - "10.101.128.0/17"
    - "100.64.0.0/10"
  egressGateway:
    nodeSelector:
      matchLabels:
        egress-vlan30: "true"
    interface: ethSel0.30