---
apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: tailscale-exit-proxyclass
  namespace: tailscale
spec:
  statefulSet:
    pod:
      labels:
        role: tailscale-exit-node
      # tolerations:
      #   - key: "node-role/infra-only"
      #     operator: "Equal"
      #     value: "true"
      #     effect: "NoSchedule"
      # affinity:
      #   nodeAffinity:
      #     preferredDuringSchedulingIgnoredDuringExecution:
      #       - weight: 100
      #         preference:
      #           matchExpressions:
      #             - key: "node-role/infra-only"
      #               operator: DoesNotExist
      tailscaleContainer:
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"