apiVersion: v1
kind: Secret
metadata:
    name: tailscale-auth
    namespace: tailscale-exit
stringData:
    TS_AUTHKEY: ENC[AES256_GCM,data:2HVuY7Ufb+17NUXvnPbNoEWdhk44Zi1PGYWi9UO283IQoBvDJYiNR/zx2EeUa0SH8JcttGIXRHLAMXxemho=,iv:UjUujuz/4DXlPTXhPKd2Fw/y7LV/dP91FcucDZT4/Gg=,tag:UgWTWv+PKCRdNvmzWph9JA==,type:str]
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWOC9BclorVDlSRzluT0pp
            T1dubFZCTEY1dElhOXR2d1VnOUVhUjdXR0RJCkNUSGV0UjRhZWNHd2dtQ1h5ajF4
            M2gxaU5vbnAxZ05QREorYlpIRGtQckUKLS0tIG56T25GZ054MUk0WUpEWGJhYUo0
            YkVIdDVjT1RWb1RJQkxCTTVvbU9BZG8Kf9uRuQ/Dqcy6RnGo99A6pyfXND8i9xYX
            jwVPwyUuexxJD2Li1tamXG92r5EBLOBTPSb+QJDjMKNMnvFEYie2VA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-11T17:54:51Z"
    mac: ENC[AES256_GCM,data:8/qB8ZiWXY16P8oSTYpwdWxgZHn7SJv/k7Vl6gG9hzyx72B0Zqnw+dlXMRYE2qdoSsZ16aD3RHYZEvYweFE5zlSGyqJC+PR7hnIfZcep1mrxLz7DBPeovDKjv9rebt4zLuyHSRA4HyO95zzqwA5OcD1dooK9+QZxOU/mD0orS7E=,iv:xu64wa+maIDJykDWtf3CX6BhIEcFech2xBRaH+JXZZY=,tag:6PMaZcDeJ8mv0kgOXD69IQ==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    version: 3.12.2
