apiVersion: v1
kind: Secret
metadata:
    name: tailscale-auth
    namespace: tailscale-exit
stringData:
    TS_AUTHKEY: ENC[AES256_GCM,data:hGvyMybXnN+5vuchEVcVDqlAq4gO4vV5hc0CleHRqaV8GK8F30TS97kKyBz35ctRLw+8LWUnaOy5UiWSdRc=,iv:7c8DTRbC7pWChNoinZ5r1mYjRkY4eLlp08IYnfpvrBI=,tag:8JmUBfp2H0JT336xDo+RrQ==,type:str]
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWOC9BclorVDlSRzluT0pp
            T1dubFZCTEY1dElhOXR2d1VnOUVhUjdXR0RJCkNUSGV0UjRhZWNHd2dtQ1h5ajF4
            M2gxaU5vbnAxZ05QREorYlpIRGtQckUKLS0tIG56T25GZ054MUk0WUpEWGJhYUo0
            YkVIdDVjT1RWb1RJQkxCTTVvbU9BZG8Kf9uRuQ/Dqcy6RnGo99A6pyfXND8i9xYX
            jwVPwyUuexxJD2Li1tamXG92r5EBLOBTPSb+QJDjMKNMnvFEYie2VA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-12T14:43:04Z"
    mac: ENC[AES256_GCM,data:vbRbtCs0aGvvbAS+UqQMGRNmnyy0WaCZtkMS0Mt+Q1Wcfz8TYSoBRAvmpcLd5Ox2HAL7pja4ABZSOEslI1yk3FnH8+aZY1xfz8Ibva1z3ODY55vRIriCkqooloZ2xZTGSWmkjLPH/l28S1bUcfpeolA3fYw+hj6Dd1tUWhFyuMo=,iv:Swbo4397evfBv9nt0MZbmg8v92DYsghjZgd9owMLls4=,tag:6xvppJFthLKPEUIdM8n1Kw==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    version: 3.12.2
