apiVersion: v1
kind: Secret
metadata:
    name: tailscale-auth
    namespace: tailscale-exit
stringData:
    TS_AUTHKEY: ENC[AES256_GCM,data:2HVuY7Ufb+17NUXvnPbNoEWdhk44Zi1PGYWi9UO283IQoBvDJYiNR/zx2EeUa0SH8JcttGIXRHLAMXxemho=,iv:UjUujuz/4DXlPTXhPKd2Fw/y7LV/dP91FcucDZT4/Gg=,tag:UgWTWv+PKCRdNvmzWph9JA==,type:str]
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWOC9BclorVDlSRzluT0pp
            T1dubFZCTEY1dElhOXR2d1VnOUVhUjdXR0RJCkNUSGV0UjRhZWNHd2dtQ1h5ajF4
            M2gxaU5vbnAxZ05QREorYlpIRGtQckUKLS0tIG56T25GZ054MUk0WUpEWGJhYUo0
            YkVIdDVjT1RWb1RJQkxCTTVvbU9BZG8Kf9uRuQ/Dqcy6RnGo99A6pyfXND8i9xYX
            jwVPwyUuexxJD2Li1tamXG92r5EBLOBTPSb+QJDjMKNMnvFEYie2VA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-12T09:33:19Z"
    mac: ENC[AES256_GCM,data:YBjt2mQCXPlqcFD75S21kxXE8EZeGOw7G14xO6MbbIUZgajdnao3NDn7eIAR81ZdjTVB/00v6C58maJcYr8OchkqmBvhmC3J6/TqwwLQT4h27w/KymEIVcj2ewsg/2ddsSfWYBByNb9JfL+sBLxTXw6BOrO2PlMC1D1rGKr7ki0=,iv:GVVsFLa3cMxSnpRsxgeNADhIXu377BQ7Ud1J2WO5jJ4=,tag:T5A/GmbDD9HavduD60HdCQ==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    version: 3.12.2
