apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: librespeed-tls
  namespace: librespeed
spec:
  secretName: librespeed-tls
  dnsNames:
    - ${DNS_NAME_LIBRESPEED}
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer