apiVersion: netbird.io/v1
kind: NBResource
metadata:
  name: librespeed
  namespace: librespeed
spec:
  name: Librespeed-s1-main01
  networkID: d9i7fjj3kdac73apg8f0
  address: librespeed.librespeed.svc.cluster.local
  groups:
    - s1-main01-services
  tcpPorts:
    - 443