apiVersion: netbird.io/v1
kind: NBResource
metadata:
  name: librespeed-s1-main01
  namespace: librespeed
spec:
  name: librespeed-s1-main01
  networkID: d9i7fjj3kdac73apg8f0
  address: librespeed.librespeed.svc.cluster.local
  groups:
    - librespeed-s1-main01
  tcpPorts:
    - 443