apiVersion: netbird.io/v1alpha1
kind: NetworkResource
metadata:
  name: librespeed
  namespace: librespeed
spec:
  domain: ${DNS_NAME}
  networkRouterRef:
    name: prod
    namespace: librespeed
  serviceRef:
    name: librespeed
  # groups:
  #   - name: kubernetes