---
apiVersion: netbird.io/v1alpha1
kind: NetworkResource
metadata:
  name: librespeed
  namespace: librespeed
spec:
  name: librespeed-s1-main01
  networkRouterRef:
    name: s1-main01
    namespace: netbird
  serviceRef:
    name: librespeed