apiVersion: v1
kind: Secret
metadata:
    name: librespeed-secrets
    namespace: librespeed
type: Opaque
stringData:
    NB_SETUP_KEY: ENC[AES256_GCM,data:Rcf6TVLyAXdZllxy8wxKHerfow/+pfBO9NlskF/knacb46r4,iv:JuEoPjOHQ+dyRnos+OyV9znQ+x4MK+9ODleFvKCGyGY=,tag:4IQ1vN8KrZxUnDso8Ou4nQ==,type:str]
    NB_MANAGEMENT_URL: ENC[AES256_GCM,data:6J5nuGYBpz2jQI2uPEEK4cKVIg==,iv:5tRdogXAqLNH0HyVlaLAyRKdH7prbBJ6Mgn0zlsSm1s=,tag:owkApe6KloQdzO4cZL0FUw==,type:str]
    NB_EXTRA_DNS_LABELS: ENC[AES256_GCM,data:szmIEEuNlBrHXytpZ7cGuLNSgag=,iv:k1XgqZnQmSpJBdFi2Dtobzr5m063JUo4Z7SPKhHBqe8=,tag:mHplzmkj+9ZXBZRVe6t9yw==,type:str]
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2amE5V1NEMzcxRHB2T29H
            Q3lzZElNRWhGa0thNkNpWGY5SWpUemZadHpZCkk2eGo4WG9xZExGV012UkNEMDU0
            TThvTGNqVTZlbWQ5VUNIRmhaNm83YkUKLS0tIFBWY3JVSlhobVptcGRNNS9ySFhR
            eENtUHlxeVEyQmVSZjA0elZGeU5CUTQK/NLyoKoSaddJpla7x1EYYnj+0NzDWFaC
            sKoqNFnQyMuA+La+qybs2KZswodT1kcWsLaznGr3+Y4wg4oSpC5lvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-30T18:02:04Z"
    mac: ENC[AES256_GCM,data:Y8fVUpyafcWRkIUsJvQpaFU/+4CFc1mRe9AiqFBJ4f5mOFfwMPbJaczsAQqW6cr+/6RZMwLTRe2Fv/i/DS3IoLoWJ1JxC1TMIsIiZ0MLsoUYFblRVcr0GEt0cnwyWCkZjp9fenGGLuUPj/Xxeq/ajZ1crrsZsYB1LM6mpMYS9VA=,iv:Qhrz5wwez7TLTVaac18rdhF0Rf5XY9Zb6SaPSloEANs=,tag:RWySIN9cwwA1pZFgUXQ97A==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    version: 3.12.2
