apiVersion: v1
kind: Secret
metadata:
    name: netbird-secrets
    namespace: librespeed
type: Opaque
stringData:
    NB_SETUP_KEY: ENC[AES256_GCM,data:yxS5F8q4FDLpCFPVG2Y1cuFIHcAc7n8UEsqPtZWoZp/iy0WZ,iv:kxzTNh/nZMiaBI9Q3vl+vw0SCl0FzdKYc78H6aJsAzw=,tag:3dDE+KNfMxl0a9+vL0e6gw==,type:str]
    NB_MANAGEMENT_URL: ENC[AES256_GCM,data:6J5nuGYBpz2jQI2uPEEK4cKVIg==,iv:5tRdogXAqLNH0HyVlaLAyRKdH7prbBJ6Mgn0zlsSm1s=,tag:owkApe6KloQdzO4cZL0FUw==,type:str]
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2amE5V1NEMzcxRHB2T29H
            Q3lzZElNRWhGa0thNkNpWGY5SWpUemZadHpZCkk2eGo4WG9xZExGV012UkNEMDU0
            TThvTGNqVTZlbWQ5VUNIRmhaNm83YkUKLS0tIFBWY3JVSlhobVptcGRNNS9ySFhR
            eENtUHlxeVEyQmVSZjA0elZGeU5CUTQK/NLyoKoSaddJpla7x1EYYnj+0NzDWFaC
            sKoqNFnQyMuA+La+qybs2KZswodT1kcWsLaznGr3+Y4wg4oSpC5lvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-30T08:30:28Z"
    mac: ENC[AES256_GCM,data:JAtxNFBOIvj7QkhLncrF3F8mU5RV22oczjlwDq+alYfgWu16KI0CroNnmvZX5faMfboqLKMUXVT8s27zzYY1n9TZyfE3AYE6JukPBrXeBUm1aZ9P2DZoyrzFT6tcPyCIS80Et2KuFsZc0CZsCUt52j66B8rlgjbx5eztPyIxYBA=,iv:Gto2uV7+GEqDvtoI5SdWM7TRtRV4vIsLdVp9aAo7QjQ=,tag:cBpjnOvYMVVwMYjlq8uIvA==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    version: 3.12.2
