apiVersion: v1
kind: Secret
metadata:
    name: netbird-secrets
    namespace: librespeed
type: Opaque
stringData:
    NB_SETUP_KEY: ENC[AES256_GCM,data:sXOrxQzj8OXlJVEcBPl3QhlEQT5GicaKLa4+ZFvC/qlhtvTh,iv:O5CxeYhgv5LsCOBYpxrry1A7i6zfKK4UlK9C+RskjSk=,tag:XSM47IBFbEqh3XkmbJ4YNQ==,type:str]
    NB_MANAGEMENT_URL: ENC[AES256_GCM,data:6J5nuGYBpz2jQI2uPEEK4cKVIg==,iv:5tRdogXAqLNH0HyVlaLAyRKdH7prbBJ6Mgn0zlsSm1s=,tag:owkApe6KloQdzO4cZL0FUw==,type:str]
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2amE5V1NEMzcxRHB2T29H
            Q3lzZElNRWhGa0thNkNpWGY5SWpUemZadHpZCkk2eGo4WG9xZExGV012UkNEMDU0
            TThvTGNqVTZlbWQ5VUNIRmhaNm83YkUKLS0tIFBWY3JVSlhobVptcGRNNS9ySFhR
            eENtUHlxeVEyQmVSZjA0elZGeU5CUTQK/NLyoKoSaddJpla7x1EYYnj+0NzDWFaC
            sKoqNFnQyMuA+La+qybs2KZswodT1kcWsLaznGr3+Y4wg4oSpC5lvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-30T10:29:12Z"
    mac: ENC[AES256_GCM,data:n2lXVuqlDJPUYQPxWTe/ILoIe0Mh1lAsoOczt/0TXuO29a8xvMBnwhYDM1fYBhkOz4LqzbVB4g/h3+as5d/CfYrVq5vnbt2QaNVeONVHSrNuW2/eZpVd63/e/4IRFou1hS9hpOfRX07tuSjtczJUBi0eE6qB9A579Hde5iW7tgg=,iv:smysR8hRlwDjQ+hcGgrlQQwYO3EX6hM3ohzxfCadJ0U=,tag:6EZX5pStf+QK4V8wC5vOOg==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    version: 3.12.2
