---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: podcast
resources:
  - pvc.yaml
  - secrets.enc.yaml
  - deployment.yaml
  - service.yaml
  - certificate.yaml
  - caddymap.yaml