apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: minuspod-data-backup
  namespace: podcast
spec:
  sourcePVC: minuspod
  trigger:
    schedule: "0 * * * *"
  restic:
    copyMethod: Snapshot
    volumeSnapshotClassName: csi-cephfsplugin-snapclass
    repository: volsync-minuspod-secrets
    pruneIntervalDays: 28
    cacheAccessModes:
      - ReadWriteOnce
    cacheCapacity: 5Gi
    moverSecurityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    retain:
      hourly: 24
      daily: 7
      weekly: 2