apiVersion: v1
kind: Secret
metadata:
    name: minuspod-secret
    namespace: podcast
type: Opaque
stringData:
    openrouter-api-key: ENC[AES256_GCM,data:/81L5jWQ3V2jnWsN2M6m1S1aPu0Xpd7AY80MWFCr3Rlbip3m/IcgZUiTP1QkFxfIwhhOr3Ye9uDQpG44zjtQwhcmY80F70YzqA==,iv:9gNola2kcNIqtCVIJrXe+2rX1TBoYXtA3JQDcSFB89E=,tag:LjkTQe1MzXNf/2C+i84Pog==,type:str]
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZ0JqNXdhK1lPNkpqRlJT
            dkhYV2h0VmR2WktkaVpGMVJKK0tDWnRJSFRJCitUVkxtUUFHb0U5djVpNEdkUDlh
            MitkUmwzTGd4UEdMMGowcVVFa2lJVW8KLS0tIERrUzFOamRxYnFUdiswckJRMkV0
            YnZXZVFEb2V6SmlWay9GUTc2QUQ1eXcK77zEwZJB5wl3h1Dc1Rh46tjJ7HBQI4TL
            jSQdr+kZO9JCYlor6m80eEByn6C+15tNc7hXy7A6mqqrXFNgiIydgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-17T09:40:42Z"
    mac: ENC[AES256_GCM,data:D8FOaombgEeWStUf1BPo9JLarfGylv8AgaqEnGVYMKgLLFmeCyX2jTbMt78pNCiN77pOOBTTPFS9fbE75Sj+5PG67q5PXI1PyfooFpXjG1L0NLxopyoWeGVh1X6CRcsTTzIS+NESxW1R3UMVN3/JZiZunhHGQd1ML+89iabOr0o=,iv:ZFowt/I9p7EUcdc823L9J7pfDVtJlM5Wi4j8Fb7+MLM=,tag:2Ltsat3hsY6iYcx6ByO79A==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    version: 3.12.2
