apiVersion: v1
kind: Secret
metadata:
    name: minuspod-secret
    namespace: podcast
type: Opaque
stringData:
    master-passphrase: ENC[AES256_GCM,data:MEe3rQmwzSrEzz/f4iS9dvFeq2w/QaUCfBNMJqRtC/718EKbvXYAJond8vK69H5Cv90=,iv:ia0C4bU9RuzZtA1CB/+eBHLUN0/GD7SrSe1DLn2EIBs=,tag:JEeAUiN0JjtY4ZB3EHz+FA==,type:str]
    openrouter-api-key: ENC[AES256_GCM,data:/81L5jWQ3V2jnWsN2M6m1S1aPu0Xpd7AY80MWFCr3Rlbip3m/IcgZUiTP1QkFxfIwhhOr3Ye9uDQpG44zjtQwhcmY80F70YzqA==,iv:9gNola2kcNIqtCVIJrXe+2rX1TBoYXtA3JQDcSFB89E=,tag:LjkTQe1MzXNf/2C+i84Pog==,type:str]
    base-url: ENC[AES256_GCM,data:y0ETKJDNVP0iAYsv+zdwHG0xkGQFp0kLdV9b5o+CU7AHVazHeAefKp+p7DOwpA==,iv:FwCUj/1oIe0uy5XmjUGT3vIV5KRfhj1ynHDJxZXUTEM=,tag:dnPIswgYj7e7tbg8ufIlkw==,type:str]
    NB_SETUP_KEY: ENC[AES256_GCM,data:4kXhMJKneQzpK25SfweDzQHhDG2JuYpk/o7WEQy4Cz4320zk,iv:ddS50shgUbSfhmupsnaA7uLClbflWJCgURmJ0mFQqF0=,tag:wu7xsWjRm9eBf5b1OEO/yw==,type:str]
    NB_MANAGEMENT_URL: ENC[AES256_GCM,data:tR/mKEV/hs0PtlJJ4YENvxrnwg==,iv:x+h4XQRiCW2POXZfN+S/u/U9SSlr4Z5Q/qFyNRqR/kw=,tag:gB5Xl1R2aAunRIiX01emdw==,type:str]
    NB_EXTRA_DNS_LABELS: ENC[AES256_GCM,data:cgwnEDHsPtC+2qqSObNS/Scy,iv:23c7TrL/pgfQwCJcJ9/PBkWArbWt3wq/ycqHhjTj7rM=,tag:m9MaQoh4ovyQmVhsbwY2lw==,type:str]
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZ0JqNXdhK1lPNkpqRlJT
            dkhYV2h0VmR2WktkaVpGMVJKK0tDWnRJSFRJCitUVkxtUUFHb0U5djVpNEdkUDlh
            MitkUmwzTGd4UEdMMGowcVVFa2lJVW8KLS0tIERrUzFOamRxYnFUdiswckJRMkV0
            YnZXZVFEb2V6SmlWay9GUTc2QUQ1eXcK77zEwZJB5wl3h1Dc1Rh46tjJ7HBQI4TL
            jSQdr+kZO9JCYlor6m80eEByn6C+15tNc7hXy7A6mqqrXFNgiIydgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-30T18:00:47Z"
    mac: ENC[AES256_GCM,data:kFY9hiMR2xMwU6kOUxTqDK3tCruoO6Ge8MMM9LqvhbcKsHrsAuNvCEZpyDpQJGXJIOK2t9v+RHnIGK23wzQeGm4tfUqLjaDfPzGlb50I4luDizMz2rVqrNLf6DbXUi7guH5Ohs8etWm6FxvMhaR5KHypTetSKddTyuIipDsbg4Y=,iv:KyW7qXfFt3V1oxhwBW7KBhxH0HL5o+HRkEZfraRUj5U=,tag:c3s+8FD61Jtj4dSabyIJyg==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    version: 3.12.2
