apiVersion: v1
kind: Secret
metadata:
    name: minuspod-secrets
    namespace: podcast
type: Opaque
stringData:
    master-passphrase: ENC[AES256_GCM,data:Wf55RPgM6fSlKifKzZI9H2F7PRO6EXl76nLruInv8QHH1Wx/SZnT3ziIvupgXAM2/qo=,iv:Ky5PppXo4FzM9gv8wycDz0AE/Sz0Qt/dA/wLdIMQecs=,tag:hJl4B+k/BXVulLKA+Qiz/Q==,type:str]
    openrouter-api-key: ENC[AES256_GCM,data:nlt1/0PuQGccHe3j0vyfw74ni/YhYTo8oiKDxbH32DxIWY3QjGt61/YYdnNZMoZ/V+XhCIV8c6JgbEMLCSQm1Fa8O2oarloQLQ==,iv:+BgxiV2M527T54pONq0357yVozig7PeaoDRWUW0XSvg=,tag:24KuFiJMaTIW48X7PEhiHg==,type:str]
    base-url: ENC[AES256_GCM,data:1EPWousmO8q/Xu4WWCuPeNaH7+RDecd0t41L8nTVnjuJccllFXjv4lqyi4NQrw==,iv:clc48ZgDxF8swHYzN1FSboWRWMrRU0MzjpBoVMkyBfQ=,tag:jJ165PiTVzTHGB3Ead1AMA==,type:str]
    NB_SETUP_KEY: ENC[AES256_GCM,data:vM93J+t0RteTRGGn+CcMs1RZPKisIdYQyg2o9XGnYi6YxFIi,iv:YRYAd+gha0M9LY/09Sd1ww6I56A28RwcxRCfhaFDbps=,tag:KzCBGeNcLRUCwLZ0HKdb2Q==,type:str]
    NB_MANAGEMENT_URL: ENC[AES256_GCM,data:HDyxqC0yPh/yYDaBmma4viizMw==,iv:q9ujMJQMTRi76Xhl3DkDCtAELdBJ1U3APwDEOQQRzoY=,tag:WcPd2tmay+7iC3X0u/4AdQ==,type:str]
    NB_EXTRA_DNS_LABELS: ENC[AES256_GCM,data:veUQin1z7B4dL3hG8Xl0pd5T,iv:6UYg5eB3W+rqh2rjH+X9jCrmxqX4f9NPu2xyHjVaJOE=,tag:JBjHnO/vprZxy4i1tSVVNQ==,type:str]
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtM0szdEkwbG00MGhUNzMx
            TUM3c0VWUkxaeG92WlZhdE00SGZkbSs3QTAwCnNmT21ia1BLU0pDTGl6OG4rOVBV
            dmZtemc1TFpmU0t1ODdNNjRGOENIVm8KLS0tIDhPUzBCU0tOclRiaDdPUUREamM0
            TjZQaW9oS0NsME9GbUxUOHBEWmtMSEUKxFqtGyMcJwSwRW4x7wdeaab9JuiyJ9cK
            rwCs+O1rMxiKntMMPc19LepbTvnUtdIUzMTOaa+uvsXevsiCpRVICg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-06T14:22:33Z"
    mac: ENC[AES256_GCM,data:I8z6+ybQZWsGw0P4JwfRrBu7vR/OdNwtuW86+iMHCwlBeRC3xdYPYyW63aL1tOcMoHpJVqoo+bfqV9QrEBaQaZgvh9vXbkGW/f8xO7kPNNZUETOI+aUfkKgLmcBAfKN8Vc/Qg+I6JVlNbGEnUexjL7VP/QII+jXxGiftyJHa9kE=,iv:1fa4+d40s+NKZl4CSiqPAjywBWO7m/MAq5fv+rSi02Q=,tag:nMgxbetWnRYddYteD+1XyA==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: volsync-minuspod-secrets
    namespace: podcast
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:nrTYlhM5Y5xjooh90oUBVcACT0nFPjLPKu7I63voAELBFL5VTVZKT5PCez9Wyg==,iv:ZrVwReMEbVakKbY8QGjX+7i/uiNsN34XOgbtt3IEGIU=,tag:B2WaVkcS8JO3W9Okq4JAkw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:iFN7xrrPONjKKteyTg9rWTiST6w1DdMyUdSgl8UQG7HB91jGrJAvz9Xt3AGSdxg6ez8=,iv:IUa6YO0Lw9Ap+xdQY6DYfi54e0fZvU6hEqacvLNOE58=,tag:rPXkozwj6cnI6+8cKx2A0w==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:IbG/zOL9KhIH8i/vASgkEg==,iv:kRs1Po6XvciywQFYEVHj2qSH+B4li8zenzty16m5OAo=,tag:870+xx61hsP6oaNTrFdsXA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ZQEYqG8vwD/xYblhY/r6fUah0qUXym0KurtXgs9w+QdDoWoZ+3Hn5ZLF63LtfHtBSbo=,iv:wMjqKQgOtswxIxPlcJz8lCMHZ4/DZ57aAAfKcbI+XlU=,tag:EP6x5YyjwNObUwAPEkkbWA==,type:str]
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtM0szdEkwbG00MGhUNzMx
            TUM3c0VWUkxaeG92WlZhdE00SGZkbSs3QTAwCnNmT21ia1BLU0pDTGl6OG4rOVBV
            dmZtemc1TFpmU0t1ODdNNjRGOENIVm8KLS0tIDhPUzBCU0tOclRiaDdPUUREamM0
            TjZQaW9oS0NsME9GbUxUOHBEWmtMSEUKxFqtGyMcJwSwRW4x7wdeaab9JuiyJ9cK
            rwCs+O1rMxiKntMMPc19LepbTvnUtdIUzMTOaa+uvsXevsiCpRVICg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-06T14:22:33Z"
    mac: ENC[AES256_GCM,data:I8z6+ybQZWsGw0P4JwfRrBu7vR/OdNwtuW86+iMHCwlBeRC3xdYPYyW63aL1tOcMoHpJVqoo+bfqV9QrEBaQaZgvh9vXbkGW/f8xO7kPNNZUETOI+aUfkKgLmcBAfKN8Vc/Qg+I6JVlNbGEnUexjL7VP/QII+jXxGiftyJHa9kE=,iv:1fa4+d40s+NKZl4CSiqPAjywBWO7m/MAq5fv+rSi02Q=,tag:nMgxbetWnRYddYteD+1XyA==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    version: 3.12.2
