apiVersion: v1
kind: Secret
metadata:
    name: minuspod-secret
    namespace: podcast
type: Opaque
stringData:
    master-passphrase: ENC[AES256_GCM,data:MEe3rQmwzSrEzz/f4iS9dvFeq2w/QaUCfBNMJqRtC/718EKbvXYAJond8vK69H5Cv90=,iv:ia0C4bU9RuzZtA1CB/+eBHLUN0/GD7SrSe1DLn2EIBs=,tag:JEeAUiN0JjtY4ZB3EHz+FA==,type:str]
    app-password: ENC[AES256_GCM,data:vPvO0RT75p7u38N+sGMIY4X2VzxKmbndtyTEi1npHwda/GaOR9CNDGulm5b5m5DxW40=,iv:QCZ0gcPNxTJ7lvah3F/dOLmBhvHjsAlMvDEVmgWXRJs=,tag:QfU3eE/00AM2AA3miQx+LA==,type:str]
    openrouter-api-key: ENC[AES256_GCM,data:/81L5jWQ3V2jnWsN2M6m1S1aPu0Xpd7AY80MWFCr3Rlbip3m/IcgZUiTP1QkFxfIwhhOr3Ye9uDQpG44zjtQwhcmY80F70YzqA==,iv:9gNola2kcNIqtCVIJrXe+2rX1TBoYXtA3JQDcSFB89E=,tag:LjkTQe1MzXNf/2C+i84Pog==,type:str]
    base-url_public: ENC[AES256_GCM,data:7gTb4DXdi5zKgOOqMPTN9eC8CGNdDd05HPgTVyFezSIekFSaOj3r4t7eDsE=,iv:Tgj3En94NRvd0Xem3rbZRHCeI4s73AaIZe9/wV5uDGM=,tag:YuCqW0M7Xh7Xsb1cJ1rVpg==,type:str]
    base-url: ENC[AES256_GCM,data:BOP8dU4sdspHDsB021VyKWrQo6z2HoV9P3+Yt7MC1AGrU6OZOXv7U1U=,iv:QGYaHpWTp2QZvxRFjQa/3P3aj3sCCX+v2oYm4QAfjMo=,tag:6HpZBj2G82D6EC5sJ0sk4w==,type:str]
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZ0JqNXdhK1lPNkpqRlJT
            dkhYV2h0VmR2WktkaVpGMVJKK0tDWnRJSFRJCitUVkxtUUFHb0U5djVpNEdkUDlh
            MitkUmwzTGd4UEdMMGowcVVFa2lJVW8KLS0tIERrUzFOamRxYnFUdiswckJRMkV0
            YnZXZVFEb2V6SmlWay9GUTc2QUQ1eXcK77zEwZJB5wl3h1Dc1Rh46tjJ7HBQI4TL
            jSQdr+kZO9JCYlor6m80eEByn6C+15tNc7hXy7A6mqqrXFNgiIydgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-27T13:28:27Z"
    mac: ENC[AES256_GCM,data:N6mpDyo+T3LD6sFbr8R8P+YcEFSihHDBuVryI4D8z01MymoYQTX7kIot0jQBgBncnQfilUFhVhWQgO2Rbklt8UWIWTXquO8GS+YlJzvXXX3XUC0ytzwMCwh2EgMOriJYf4Mmzk1WStr2WwN8QMtyE+oGTEqm4v4ltV+DzL6sv6Q=,iv:H11H6aAFOal4KK2pxaIiWAx696GyOOlIzM5FbBjiyc4=,tag:K8PT4QF565+eZaysURVNIQ==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    version: 3.12.2
