apiVersion: v1
kind: Secret
metadata:
    name: minuspod-secret
    namespace: podcast
type: Opaque
stringData:
    master-passphrase: ENC[AES256_GCM,data:MEe3rQmwzSrEzz/f4iS9dvFeq2w/QaUCfBNMJqRtC/718EKbvXYAJond8vK69H5Cv90=,iv:ia0C4bU9RuzZtA1CB/+eBHLUN0/GD7SrSe1DLn2EIBs=,tag:JEeAUiN0JjtY4ZB3EHz+FA==,type:str]
    openrouter-api-key: ENC[AES256_GCM,data:/81L5jWQ3V2jnWsN2M6m1S1aPu0Xpd7AY80MWFCr3Rlbip3m/IcgZUiTP1QkFxfIwhhOr3Ye9uDQpG44zjtQwhcmY80F70YzqA==,iv:9gNola2kcNIqtCVIJrXe+2rX1TBoYXtA3JQDcSFB89E=,tag:LjkTQe1MzXNf/2C+i84Pog==,type:str]
    base-url: ENC[AES256_GCM,data:L61rih5pnRVVQU0yG1onqoRlsZhwrUKuC3cDAGy0TIZQhtWzuzM=,iv:1qSePqvMqTX8gwsErmdAgV4PW/j+1vGlzhejlqpG9jg=,tag:CkX5o1D9EwbZMtRJxbY/EA==,type:str]
    old_base-url: ENC[AES256_GCM,data:Jycim4ByIrZq2b581M0ymopzTXa5f/fxPudYGjgo/bnIOoGQpX86zLLzTNI=,iv:klTJdOOMwOcHxEyzhJj3msnL8Pyoc1hNhIJFU5lZE9k=,tag:0f4vsMJs28VYB52v1isGDg==,type:str]
    base-url_local: ENC[AES256_GCM,data:XS+GwTHIhQQhTSP/LxE7ix9J1maOOrbIrgigpkG7edE/8jSfH7+rPj4=,iv:fBAFB2JOiECT0dtWfjWfrkjoHelKXJ4for83pfX/86s=,tag:ruId5303LkNkSyk/yTeNiw==,type:str]
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZ0JqNXdhK1lPNkpqRlJT
            dkhYV2h0VmR2WktkaVpGMVJKK0tDWnRJSFRJCitUVkxtUUFHb0U5djVpNEdkUDlh
            MitkUmwzTGd4UEdMMGowcVVFa2lJVW8KLS0tIERrUzFOamRxYnFUdiswckJRMkV0
            YnZXZVFEb2V6SmlWay9GUTc2QUQ1eXcK77zEwZJB5wl3h1Dc1Rh46tjJ7HBQI4TL
            jSQdr+kZO9JCYlor6m80eEByn6C+15tNc7hXy7A6mqqrXFNgiIydgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-25T11:11:38Z"
    mac: ENC[AES256_GCM,data:x0YHDuHXGetwOG4VbV+cYC94aLmm8xIAVg9DmvNRAC8NDcieTcDuiPcq6unXeBDE15Lum4dmJtFqpHBq3Qg4ERyztw69gWTVsvBzt1XCtTokC4qMczfYt+4imAgthPso/Hqpr2xK6qQ0v1jmFxgq8fjG2J/EWTIP8GEwfoWSgkY=,iv:VZ5zyAPuoZTdd06VITfobvrKvnp8JEpWYk7ZaoFc0LA=,tag:vyqVynk87pyuopjfuqjwlQ==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    version: 3.12.2
