---
apiVersion: v1
kind: Service
metadata:
  name: minuspod
  namespace: podcast
spec:
  type: ClusterIP
  selector:
    app: minuspod
  ports:
    - port: 443
      targetPort: 443
      name: https
      protocol: TCP