---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minuspod-ingress
  namespace: podcast
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: minuspod
      port:
        number: 80
  tls:
    - hosts:
        - s1-main01-minuspod