apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iperf3-server-netbird
  namespace: iperf3
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "ceph-rbd-hdd-r2"
  resources:
    requests:
      storage: 100Mi