apiVersion: v1
kind: Secret
metadata:
    name: iperf3-secrets
    namespace: iperf3
type: Opaque
stringData:
    NB_SETUP_KEY: ENC[AES256_GCM,data:4SqAVFYZZ8+yy5HzG3ahYCRwaLEwQ8lLzoCT5qgX4gcM1B0Z,iv:9Vr4mOGw8wyj/VrxfnJUDE5FMyDWy6N/3Vshh7F0ETU=,tag:FnmE5v9TDi68PwXpqVluuw==,type:str]
    NB_MANAGEMENT_URL: ENC[AES256_GCM,data:FkINPM0YL2pH87qg7i1BAfvZeg==,iv:80E6gkns573HPJw4uCzIopsxjyRznHurDbDO2AxLCtM=,tag:DhbAcxZRkw9Fl2ZFczlifw==,type:str]
    NB_EXTRA_DNS_LABELS: ENC[AES256_GCM,data:4XQHUD53qyQlCtvJVfHQp+oOWzaL/T0=,iv:4tnAcvq17554FIwrMSo4XJNieFbxImMd0YY1YUH6jxQ=,tag:RCUasTGK9v9yV4WRW+ZiYQ==,type:str]
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvK1lYV2haZkF1a3c4c0Y2
            dFkzd3g5YXFzeDVLNkdSTElrdVEvQmorVlU4CmVJQkwxZlpxYjdDenFzOVVIT1FG
            U1JjbGRTTHIzUzBrN3drbkZVTkNBVGMKLS0tIG9rR2RaQnJuSkdTbTdtYlVGVTY4
            TnJKbUdaVTAxdzdXMEVIV0YwTDdvNGsKoQ5C//F/PTcu1coMWeX125MRMAquPYFb
            SicqCNaZCYiBd9kTs9PsvSEzNUsAd4mUY1QzwROCY0cr19pXEhqxRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-06T11:27:17Z"
    mac: ENC[AES256_GCM,data:HoF88/WPxfZGrMsAApq3jjGYhIZjKIpNFRieZs7K7DsruVr2nR6YyDyakOGWHtbn/1w6BI8tJbgBDoc01WFeh2YUd2MCB425c7x7nHtk5KwLG4Rz2aMtm3sqG9tJiBulQCJ3ezZTapqnviPuoZWuZM+yA0RymEOYWc1vtxO2OQo=,iv:v739fboZsfTuMPoGOKjMPWwN2UDLyEEkiZS5DD6St8c=,tag:ClB1vCfD0peGB1gqdhFq7A==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    version: 3.12.2
