apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd-hdd-r2
  resources:
    requests:
      storage: 500Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-netbird
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd-hdd-r2
  resources:
    requests:
      storage: 100Mi