apiVersion: v1
kind: Secret
metadata:
    name: immich-netbird-secrets
    namespace: immich
type: Opaque
stringData:
    NB_SETUP_KEY: ENC[AES256_GCM,data:dp2vWXBeVssas9biZe1fJM2MoqjHoPkwV8g4LlRy/NBfJNLY,iv:r/o7lxRYo+UU9Kzlx/LtT9dKjK1H18s8tekgt2PpHv0=,tag:fiaU8L5TaSRrXQ7dBz0xUw==,type:str]
    NB_MANAGEMENT_URL: ENC[AES256_GCM,data:kx9Y6uIPQ9yYGlUFyEbP3KESow==,iv:e/pTT2JttzCjQstD9le1j3siiWOQmzcH7hZ24IVVIes=,tag:QYV1oYAqIw05cFuNV5PutQ==,type:str]
    NB_EXTRA_DNS_LABELS: ENC[AES256_GCM,data:AIF2QqFsgZnUd+N8QVFDQg==,iv:jCzWaa8vTQ6gqdUqAzaf26FmuGGxoZkJJ473yVrgfjI=,tag:sOM0nblRfW4n97x87172PQ==,type:str]
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjd21OamU0Rk5TNHRoUTZj
            YmdnV3d5SXcyTHV6bmRub1B4M0M0cHRjMmdvCkVCQTRYRzlPUzJxVU56N01oTy9Y
            NmZoS1g3SnJSamFxU2U4Y1BGUGh6UmMKLS0tIC9xd3c1dzMvZXBoeWd2VVBPUDJy
            cTRnVi9tOFBsVHRmUmdXeHdndTdLS28KYlHHZOdhHD4ORo6Un5Cb9cHC0H1Z6ezf
            j+FlkfOBdvk8MunOrAMCELoec6zQ1oH3FtW5vqaQSndLpdIfQBaDjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-11T18:56:15Z"
    mac: ENC[AES256_GCM,data:16Krrw3mc+Mnzehz+4M6MIlREkNpsi9tfWZ0JNXQmG2WRJsuGYYv3HqY0xA0aKWbxzePoZzJUYgRtrmCcB7tkrDyNiEAW9ia8l5DgXz3DMlKa4RgzuKkNjNTkJlyWlYSqaePXr0DqrM2dpZYb7KLpV3N5Rf+fW7MJaCdBugTVwI=,iv:RUPFl17HLu13yaH1eNkTj7K2rTBpLdizPBGKX8E0DFk=,tag:X6ZF02bd54p3glZ21muuFQ==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: immich-library-volsync-secret
    namespace: immich
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:6rQ1f7JQ2Zn2audOVKvW3tmmlYTvgu/G0cuRVJ18yne2n8NLNY4U0kvZJ8M56RIoNwyJFBhDRafxcgI7rA==,iv:4Vml7id9rK2jdgcsA8xbkQZ4tOQkevl5uYjKP7amy5o=,tag:YhL2QEFVe51SadjeRwK2xQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:zRH1VR8qfAvJE2Dm8zifL40l/VSwX40CX96kqK3KpvbK1qbUywZLoTccvCaeI7+9s9s=,iv:F0/OFkZsbHBLxTiUM4MhGakNadXVBasxmkZMpCjpYHo=,tag:X/0sUxj4tg2fpHTVbSzQ0g==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:/8YvV8v05YXiEW8516zcFA==,iv:+nHHS4EX9x9YtSnvy/XBfm/6id+RrEGw7Jj2DUD8on0=,tag:fV1n4K1aWPwnS+AWW0RcLw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:qYf1+zFVgvSkjB7DAYV/mf5bJrfnIeN70G6rTmX/AK59bsk3SuYH/NDW2IQvW1+QgCM=,iv:ky8ammBOlMzjfr2H7ZSY+GquiJ2z+HpOcCxC3ce3uRc=,tag:4kqyhgdyIaeEYXsX2GxLCA==,type:str]
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjd21OamU0Rk5TNHRoUTZj
            YmdnV3d5SXcyTHV6bmRub1B4M0M0cHRjMmdvCkVCQTRYRzlPUzJxVU56N01oTy9Y
            NmZoS1g3SnJSamFxU2U4Y1BGUGh6UmMKLS0tIC9xd3c1dzMvZXBoeWd2VVBPUDJy
            cTRnVi9tOFBsVHRmUmdXeHdndTdLS28KYlHHZOdhHD4ORo6Un5Cb9cHC0H1Z6ezf
            j+FlkfOBdvk8MunOrAMCELoec6zQ1oH3FtW5vqaQSndLpdIfQBaDjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-11T18:56:15Z"
    mac: ENC[AES256_GCM,data:16Krrw3mc+Mnzehz+4M6MIlREkNpsi9tfWZ0JNXQmG2WRJsuGYYv3HqY0xA0aKWbxzePoZzJUYgRtrmCcB7tkrDyNiEAW9ia8l5DgXz3DMlKa4RgzuKkNjNTkJlyWlYSqaePXr0DqrM2dpZYb7KLpV3N5Rf+fW7MJaCdBugTVwI=,iv:RUPFl17HLu13yaH1eNkTj7K2rTBpLdizPBGKX8E0DFk=,tag:X6ZF02bd54p3glZ21muuFQ==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: immich-database-barman-secret
    namespace: immich
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:/8YvV8v05YXiEW8516zcFA==,iv:+nHHS4EX9x9YtSnvy/XBfm/6id+RrEGw7Jj2DUD8on0=,tag:fV1n4K1aWPwnS+AWW0RcLw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:qYf1+zFVgvSkjB7DAYV/mf5bJrfnIeN70G6rTmX/AK59bsk3SuYH/NDW2IQvW1+QgCM=,iv:ky8ammBOlMzjfr2H7ZSY+GquiJ2z+HpOcCxC3ce3uRc=,tag:4kqyhgdyIaeEYXsX2GxLCA==,type:str]
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjd21OamU0Rk5TNHRoUTZj
            YmdnV3d5SXcyTHV6bmRub1B4M0M0cHRjMmdvCkVCQTRYRzlPUzJxVU56N01oTy9Y
            NmZoS1g3SnJSamFxU2U4Y1BGUGh6UmMKLS0tIC9xd3c1dzMvZXBoeWd2VVBPUDJy
            cTRnVi9tOFBsVHRmUmdXeHdndTdLS28KYlHHZOdhHD4ORo6Un5Cb9cHC0H1Z6ezf
            j+FlkfOBdvk8MunOrAMCELoec6zQ1oH3FtW5vqaQSndLpdIfQBaDjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-11T18:56:15Z"
    mac: ENC[AES256_GCM,data:16Krrw3mc+Mnzehz+4M6MIlREkNpsi9tfWZ0JNXQmG2WRJsuGYYv3HqY0xA0aKWbxzePoZzJUYgRtrmCcB7tkrDyNiEAW9ia8l5DgXz3DMlKa4RgzuKkNjNTkJlyWlYSqaePXr0DqrM2dpZYb7KLpV3N5Rf+fW7MJaCdBugTVwI=,iv:RUPFl17HLu13yaH1eNkTj7K2rTBpLdizPBGKX8E0DFk=,tag:X6ZF02bd54p3glZ21muuFQ==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    version: 3.12.2
