apiVersion: v1
kind: Secret
metadata:
    name: navidrome-netbird-secrets
    namespace: music
type: Opaque
stringData:
    NB_SETUP_KEY: ENC[AES256_GCM,data:dJ+Wjtm3jIbtQ9ly/NJfe7AXtaFECSK/6bBw9c5Y7VNXTVHa,iv:s7P7C7ZzJxOGgDy5laT6X99jRKMi0KW2cwadFNlErug=,tag:j8hkZ2a56fXumX84UtV7aQ==,type:str]
    NB_MANAGEMENT_URL: ENC[AES256_GCM,data:feWWoeN2hQolvOmGfGLCLkenIg==,iv:mxO1mAZuRGT9gCKwO4HUTcGoMdMrUBPgzkrRQ9Jf7VY=,tag:zlXEwwy5ZMDIBKmNXEuy1g==,type:str]
    NB_EXTRA_DNS_LABELS: ENC[AES256_GCM,data:jHBiVwLNAiQAOc8tclx27ULTCQ==,iv:lW8tc7Cl6pimoQoc0EubI0Epn2xaSFasbj1LZeO4Qy4=,tag:1hQrNvK/lZ63vxuht9V6ow==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmdVo4SGZ3VEd6Vm5XY010
            bFRZTWtxVitQeXhlNXpzbVBoay8rb0tCYmdvCjR2ZnRGNlBab3NQSXBVa1hhWnhw
            bTBTeWNpYTM5UXVXMVZxNStqTGs1RU0KLS0tIGNLTmw0Nmo0NkZEU080OVdabHEw
            RWtNb3pRRlJ4R1h1elNFUGJ2LzQ0RHcKeIP7fJ5VrmfYB1JSua7WFvTlh0hlHPFj
            94m7qJi8Kx23I1n5y/BDsYGPgIVFYnzMOSnQChfVzmyYBL7YDI+IYA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    lastmodified: "2026-09-06T14:40:42Z"
    mac: ENC[AES256_GCM,data:k6TpSSzJd6M4tCHwEz4xsPmzOTZgpkRSYEIHD0FK5reLPWCjCFAKYXw8qBLRzQgr7Bwk2FklTX6Ou2pJs2x0fHIEYs5Sgd/TJ20/ecdMLUge7/3+iu2/fYNwlVxexpC8VBvThKgLVGMAMO6GxvlZK7AbmxlnYduT2qLN00zrakw=,iv:P+PX26CnbIzZhQYMaZafHtcHsUGXVDQOpZOu1WT13Pw=,tag:rOwXpEItgMUDkL5g+VhaFg==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: navidrome-data-volsync-secret
    namespace: music
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:X/m2bi3dCpRDmbvPWhNg+uRt5yw+FDPnYh7RSdVliDE6V1BuWSDAh3toeGeniywRYSxr3mLaKl8UmFbKKw==,iv:j8YT87qZ8aZIQTUJdbPmjLPUkNV5y5tpDoq0DbuP3WU=,tag:gRXPsTioWErgy44EPJLZKA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:Hex3R6S55MrEaEO7EGUPBdSff6ksfnAj47ArNX9QgjLj7gTrh29Zl+JZxAFwy8zKX4g=,iv:xH+gjswVgY3htxpRt1Z3b9VBzKWhO+6GvtkEJb+yJA4=,tag:fr/3efFoGWQovGSQwONgzw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:KG/u6HCAFi6+KdWc6Kj4VA==,iv:FvaZoNow1UyjjEZOs/u0k1EHHTRuDPMcnFKhOQfe3XM=,tag:RXdpiuJXEjoI+cPjG006ng==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:vql7Z2y5keO6egG5Q9jy6waI7vkycZum7JMylL/J1jqB5IT3zkRoGXJNhJXK8DjaRVU=,iv:XvUm2cyotaFHoQiVwVhXI+CvOcHQqx13eYaydiVh0oA=,tag:ORtJBmDWwrBaBNfCbMBYSQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmdVo4SGZ3VEd6Vm5XY010
            bFRZTWtxVitQeXhlNXpzbVBoay8rb0tCYmdvCjR2ZnRGNlBab3NQSXBVa1hhWnhw
            bTBTeWNpYTM5UXVXMVZxNStqTGs1RU0KLS0tIGNLTmw0Nmo0NkZEU080OVdabHEw
            RWtNb3pRRlJ4R1h1elNFUGJ2LzQ0RHcKeIP7fJ5VrmfYB1JSua7WFvTlh0hlHPFj
            94m7qJi8Kx23I1n5y/BDsYGPgIVFYnzMOSnQChfVzmyYBL7YDI+IYA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    lastmodified: "2026-09-06T14:40:42Z"
    mac: ENC[AES256_GCM,data:k6TpSSzJd6M4tCHwEz4xsPmzOTZgpkRSYEIHD0FK5reLPWCjCFAKYXw8qBLRzQgr7Bwk2FklTX6Ou2pJs2x0fHIEYs5Sgd/TJ20/ecdMLUge7/3+iu2/fYNwlVxexpC8VBvThKgLVGMAMO6GxvlZK7AbmxlnYduT2qLN00zrakw=,iv:P+PX26CnbIzZhQYMaZafHtcHsUGXVDQOpZOu1WT13Pw=,tag:rOwXpEItgMUDkL5g+VhaFg==,type:str]
    version: 3.13.3
