apiVersion: v1
kind: Secret
metadata:
    name: renovate-secrets
    namespace: renovate
type: Opaque
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:HZVcBd6msCWpoMwxKCgx1iw4Fz43SVaNRrsXJ30F5tdF2OHQMOJUCqu2VA6xfC40VOTjgkF7wqk2KNNprOlne5B8J4UDzGV67PsiPafdOz3wUo1ewMLe0toiAy1X,iv:Cr9JY6tnHr5ChARH6ns/a745VpOsU/EFt//aI23fcn0=,tag:t539+L5lIV+YKw+mCg8Uxw==,type:str]
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrL2RjRWpnSVFYd3ZsalBS
            TlJOSlY3NmNjN0pjTlVTZHNPWlUwSGdab1Y4CjkvN1VsbUZzakpVUVMxT0loVy9x
            NmJjaFU0TjJRZWtmbnFtQkQ5TXhnSU0KLS0tIHU4d0RYOEZGTVZ1TEhvcllxekJX
            QkpKOE5jc2x1NTZ0bFZsNGdXTndUNWMKnySVjIdiCZ9MtsW9VS+2NR0NqPZVIzXn
            8Rw9DNqC0MeC6szhn1NNthpz4pB5Noqch2s35u3ZXJmiaQ2yTYWE9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-04T09:17:31Z"
    mac: ENC[AES256_GCM,data:IMlG8nkfZg/lS5Mtd4TNmxq2cLm9jKJEogOAN6MSv+fFHSi1Hg1siF8HWwQ1QZwiOJUf5WBiP36zKpL+RuGhEkyYi29kcvxiC/fLfuLzUsGA0QSIFvJWCvHwGSAQGUwM5vhE+NxkV8f6ykqzdUa1DqILrAkX1AfXTYkMKIWlIR0=,iv:jPZ5SqTkmXwsELLUUEVs+AxgKpMDmVPljH5IISUk1zo=,tag:Q3f2j7WTXzg6UpTylKE05w==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    version: 3.12.2
