---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: localai-models
  namespace: localai
  annotations:
      kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ceph-fs-hdd-r2
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: localai-output
  namespace: localai
  annotations:
      kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ceph-fs-hdd-r2
  resources:
    requests:
      storage: 50Gi