---
apiVersion: ceph.rook.io/v1
kind: CephNFS
metadata:
  name: ceph-nfs-hdd
  namespace: rook-ceph
spec:
  rados:
    pool: ceph-filesystem-hdd-data
    namespace: nfs-ns
  server:
    active: 1
    priorityClassName: low-priority
---
apiVersion: v1
kind: Service
metadata:
  name: ceph-nfs-hdd
  namespace: rook-ceph
  annotations:
    io.cilium/lb-ipam-ips: "192.168.201.101"
spec:
  type: LoadBalancer
  ports:
    - port: 2049
      protocol: TCP
      name: nfs
  selector:
    app: rook-ceph-nfs
    ceph_nfs: ceph-nfs-hdd