apiVersion: apps/v1
kind: Deployment
metadata:
  name: samba
  namespace: samba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samba
  template:
    metadata:
      labels:
        app: samba
    spec:
      priorityClassName: medium-priority
      initContainers:
        - name: fix-permissions
          image: alpine:latest
          # resources:
          #   requests:
          #     cpu: 100m
          #     memory: 64Mi
          #   limits:
          #     cpu: 250m
          #     memory: 128Mi
          command:
            - sh
            - -c
            - |
              chmod 777 /mnt/test
          volumeMounts:
            - name: vol-test
              mountPath: /mnt/test
      containers:
        - name: samba
          image: dperson/samba:latest
          # resources:
          #   requests:
          #     cpu: 250m
          #     memory: 1Gi
          #   limits:
          #     cpu: 1500m
          #     memory: 2Gi
          env:
            - name: PASS_ANDREAS_HEDLUND
              valueFrom:
                secretKeyRef:
                  name: samba-auth
                  key: pass_andreas_hedlund
          args:
            - "-u"
            - "andreas_hedlund;${PASS_ANDREAS_HEDLUND}"
            - "-s"
            - "Test;/mnt/test;yes;no;no;andreas_hedlund"
            - "-g"
            - "vfs objects = fruit streams_xattr"
            - "-g"
            - "fruit:aapl = yes"
          ports:
            - containerPort: 445
              name: smb
          volumeMounts:
            - name: vol-test
              mountPath: /mnt/test
      volumes:
        - name: vol-test
          persistentVolumeClaim:
            claimName: s1-main01-nas