apiVersion: apps/v1
kind: Deployment
metadata:
  name: samba
  namespace: samba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samba
  template:
    metadata:
      labels:
        app: samba
    spec:
      priorityClassName: medium-priority
      initContainers:
        - name: fix-permissions
          image: alpine:latest
          command:
            - sh
            - -c
            - |
              chmod 777 /mnt/nas
              chmod 777 /mnt/tm-claes_hedlund
          volumeMounts:
            - name: vol-nas
              mountPath: /mnt/nas
            - name: vol-tm-claes_hedlund
              mountPath: /mnt/tm-claes_hedlund
      containers:
        - name: samba
          image: dperson/samba:latest
          env:
            - name: PASS_ANDREAS_HEDLUND_NAS
              valueFrom:
                secretKeyRef:
                  name: samba-auth
                  key: pass_andreas_hedlund_nas
            - name: PASS_CLAES_HEDLUND_TM
              valueFrom:
                secretKeyRef:
                  name: samba-auth
                  key: pass_claes_hedlund_tm
          args:
            # Användare (Format: "användarnamn;lösenord")
            - "-u"
            - "andreas_hedlund_nas;${PASS_ANDREAS_HEDLUND_NAS}"
            - "-u"
            - "claes_hedlund_tm;${PASS_CLAES_HEDLUND_TM}"

            # Delade mappar (Format: "ShareNamn;Sökväg;Browsable;ReadOnly;Guest;Users")
            - "-s"
            - "NAS;/mnt/nas;yes;no;no;andreas_hedlund_nas"
            - "-s"
            - "TM-Claes-Hedlund;/mnt/tm-claes_hedlund;yes;no;no;claes_hedlund_tm"
            
            # Globala Apple/Time Machine-inställningar
            - "-g"
            - "vfs objects = fruit streams_xattr"
            - "-g"
            - "fruit:aapl = yes"
            - "-g"
            - "fruit:time machine = yes"
          ports:
            - containerPort: 445
              name: smb
          volumeMounts:
            - name: vol-nas
              mountPath: /mnt/nas
            - name: vol-tm-claes_hedlund
              mountPath: /mnt/tm-claes_hedlund
      volumes:
        - name: vol-nas
          persistentVolumeClaim:
            claimName: nas
        - name: vol-tm-claes_hedlund
          persistentVolumeClaim:
            claimName: tm-claes-hedlund