apiVersion: v1
kind: Secret
metadata:
    name: samba-auth
    namespace: samba
stringData:
    SMB_USER: ENC[AES256_GCM,data:5etgGA==,iv:HqDugszZbyKQsLMoBrAVRqw0n11EWedE/rMMJWVkV50=,tag:bYxad+XDnenJ2txIxRg6ww==,type:str]
    SMB_PASS: ENC[AES256_GCM,data:00kJSMs8N10=,iv:QazW1h0uaqfZUh5G1HyjROd/7PMlb4MFr2IqxkoxSRE=,tag:DNpldYaQ/odT+7is4OhDUQ==,type:str]
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMdjkzc2ZMSUFPOFBTR3pm
            RWxwZnpzVVNhTU0zbTU3UzdlT0tOZWZqMWpzCitwQzFqTXlVOXVVYUxTV3BVeWZv
            a1V6WkZkQi9kUllBNzlWNCtRL2pBQWsKLS0tIHczcmtBUVZWWVJTcUtWNzZDbGZL
            bkYxR0NIMTNLbFl3M2F4b3JuUGM5SmcKgMuIZ8XGm9q6N7nxRzWlIiDfQqcKVZl6
            YPUXgRkoAUfitOLfX+A/0qqo6a5DU/3N7ZZmThQeKFLU8mO3uo8NRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-15T18:38:20Z"
    mac: ENC[AES256_GCM,data:8o7gDbxohadPXn+QwjBLJO3MIrqN43k6aoj2luZFMxU1ZZpQtxLZJbQ0j3AuHH2s6ly/2xLfKdDRBucKtPcRO6pnTP55/6cOj8hJfWsVSKKnwr6TTPt6dUpwL0zmFkWflugTZHSld4ui0e4AayON8tE1Ff2ktyWalNFjvgK7sMU=,iv:AxIbiWsYxR6qfRD8lJOSzCUutEJW7FxFaK3SwO1WK7c=,tag:pz0RzrR6sc//WDWntuzNdg==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS)$
    version: 3.12.2
