apiVersion: v1
kind: Secret
metadata:
    name: podcast-ad-remover-secret
    namespace: default
type: Opaque
stringData:
    GEMINI_API_KEY: ENC[AES256_GCM,data:yQZS9Mry/2Ed/5Qdrj9Ue4flUJvR2ykZwPW2rvuvsGaxwefXl/6b3pt8ZMCJcqfnxlk8SUU=,iv:3tS85HXwpu/BFet9PCSSdFJ4cSwqYxJtCNmsCK2MdQE=,tag:jIwsspZVojcUDvLf5tT+Rg==,type:str]
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Tm1LUUpUdjVpSjVqWXJa
            NGJ1VUc0a2ZlN3dTSkg0eXBZUmUrMW5GMEZjCkVjWGMxNlBnQ1h2TDUwTTErVmli
            SzRQdy9vbTFTeUtRaFNrQWpFMjZpbW8KLS0tIE1NTnJodW5jWm1Od2JlUGM5MXA2
            UmkyQkNWanhqTHEwRU9PQmJ1OEdGZFUKKtnz4hn4KXiBghWI8ak87/PZBVqBnff7
            TJfRf7Rcbqwv7qX1d/oNRz1UNCBcquS6V2zU4SSZ+vucaYtvAuHwMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-09T08:31:49Z"
    mac: ENC[AES256_GCM,data:BSXiNNvyX3Ka4D2ZrhMiKEXfReLACHbdAUo3IM0c6cFQTeW9xJ6a6vrQccbrX91N2pqkMxkPqKFhofJ4DQz4VYd3bA4iMt9VRtOrY2MRU7sj3iKdrBx35SoxcyyVI50yQBCEupyAKc0Q2D9iLgzn8gb6tvqAufBAJCPy2eig0cw=,iv:2oM+iGceQnJKAURmxZtzxtiBuA7eNikL3+vRGXpmz6o=,tag:34K1b6R4zu9OAhb7ZGJLTw==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    version: 3.12.2
