---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: netbird-exit-isolation
  namespace: netbird
spec:
  endpointSelector:
    matchLabels:
      app: netbird-exit-node
  egress:
    - toEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: ANY
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: librespeed
            app.kubernetes.io/name: librespeed
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP

# --- IPv4  ---
    - toCIDRSet:
        - cidr: "100.64.0.0/10"   # Netbird
    - toCIDRSet:
        - cidr: "0.0.0.0/0"
          except:
            - "10.0.0.0/8"        # Private IPv4
            - "172.16.0.0/12"     # Private IPv4
            - "192.168.0.0/16"    # Private IPv4
            - "169.254.0.0/16"    # Link-local IPv4

# --- IPv6  ---
    - toCIDRSet:
        - cidr: "fd00::/8"    # Netbird
    - toCIDRSet:
        - cidr: "::/0"
          except:
            - "fc00::/7"      # Private IPv6
            - "fe80::/10"     # Link-local IPv6