---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netbird-exit-node
  namespace: netbird
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netbird-exit-node
  template:
    metadata:
      labels:
        app: netbird-exit-node
    spec:
      containers:
      - name: netbird
        image: netbirdio/netbird
        tag: 0.76.0
        securityContext:
          privileged: false
          capabilities:
            add: ["NET_ADMIN", "NET_RAW"]
            drop: ["ALL"]
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "1000m"
            memory: "512Mi"
        env:
        - name: NB_SETUP_KEY
          valueFrom:
            secretKeyRef:
              name: netbird-exit-node-secret
              key: NB-SETUP-KEY
        - name: NB_MANAGEMENT_URL
          valueFrom:
            secretKeyRef:
              name: netbird-exit-node-secret
              key: NB-MANAGEMENT-URL
        - name: NB_HOSTNAME
          value: "exit-node-s1-main01"
        volumeMounts:
        - name: netbird-config
          mountPath: /etc/netbird
        - name: dev-net-tun
          mountPath: /dev/net/tun
      volumes:
      - name: netbird-config
        persistentVolumeClaim:
          claimName: netbird-exit-node-pvc
      - name: dev-net-tun
        hostPath:
          path: /dev/net/tun
          type: CharDevice