---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netbird-exit-node
  namespace: netbird-exit-node
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd-hdd-r2
  resources:
    requests:
      storage: 100Mi