---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netbird-exit-node-pvc
  namespace: netbird-exit-node
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ceph-fs-hdd-r2
  resources:
    requests:
      storage: 100Mi