apiVersion: v1
kind: Secret
metadata:
    name: netbird-exit-node-secret
    namespace: netbird
type: Opaque
stringData:
    NB_SETUP_KEY: ENC[AES256_GCM,data:pyoa3DIRsRm08kg5qiFOsyRQQ9QfyMeNxudWPKBLMi01VLa8,iv:2DtdPvdk70GUU/qOrbXJoBx4xctz9Uifb8JKTwnJKms=,tag:Hmbw3f3Mz59qsHqVTPklpA==,type:str]
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0aGsxd3pXckV3RHlpb3Zl
            YXZLWWszZ2w2Q1NpYW5mVGlhRTE5ZW9uZHpjCjAxV0NWdXJvOTRsMDF0RDU5ZlM2
            aXF5YktDdjZEbit0enFuOXg4c0dFL1kKLS0tIG15U0dNYWpEczRMQzhsbG5LLzBa
            M05FcnhIbFo4bm84OTlmVXAzYUtBZzgK+7uA0PuzGmtSxEqajjeDqXXQ4JAgFHFQ
            9vXZNyIxYpcN8geU8ESeJ42Vvfvm3U4+YErhq4feM64tQcIIXbdsUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-27T18:20:34Z"
    mac: ENC[AES256_GCM,data:E4gQDX7RP4Rdiy4JrSiSOBr8isXdh4RGdrP5cz9eSyVFQ/s3b55N7sk0XRC7RPt7oGxFpdx2rJ2gixF3xxUMv1Gm0Qev6haeLsoz9oFTCdH8lD36T1T4TIAlm6+pGR+SlqTGQOLXDsudxczD0TbvPYz4iHDhE5gIREW5GIvi7yU=,iv:9a16HAOZF8YpF/nC7VJBjIU67a/wAwPLrHCyGMGWMak=,tag:FUkGjBnjXVJlKlOUe6/KBA==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    version: 3.12.2
