apiVersion: v1
kind: Secret
metadata:
    name: netbird-exit-node-secret
    namespace: netbird
type: Opaque
stringData:
    NB_SETUP_KEY: ENC[AES256_GCM,data:YW+ubuyyck2Pkl/8kYfYQQHL4XnS+RlIxL1DBnSfH2w1Hrol,iv:Q+sZaUW7RajSUAO18y4jRh/xgzp5YVLOnxW6KVWxQN8=,tag:ghufj2uBne+NsqFo6R6hRQ==,type:str]
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0aGsxd3pXckV3RHlpb3Zl
            YXZLWWszZ2w2Q1NpYW5mVGlhRTE5ZW9uZHpjCjAxV0NWdXJvOTRsMDF0RDU5ZlM2
            aXF5YktDdjZEbit0enFuOXg4c0dFL1kKLS0tIG15U0dNYWpEczRMQzhsbG5LLzBa
            M05FcnhIbFo4bm84OTlmVXAzYUtBZzgK+7uA0PuzGmtSxEqajjeDqXXQ4JAgFHFQ
            9vXZNyIxYpcN8geU8ESeJ42Vvfvm3U4+YErhq4feM64tQcIIXbdsUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-27T18:07:28Z"
    mac: ENC[AES256_GCM,data:JWS3jDznBPZjkcLGuFu3tP+pXBtfgL2VIaX/ICW8YBFKJJ3tSgCEyMN4cXAs+gsufI+IzDEsEKQcojAm9Z7uPQsGFX+erdQyS2lrekkQShgeWXZDyAaNURXokBHlRSEjAPa+bVXVQtCKXibVurpa4UQHl3wMwZnnO5KH7dGXZ2Y=,iv:khWKxk49cSG1ti+ScJpezCcCYFhwr8yPStdF+bKs1v8=,tag:1WPJhsevg9u6t3hBL3lzHQ==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    version: 3.12.2
