apiVersion: v1
kind: Secret
metadata:
    name: netbird-exit-node-secret
    namespace: netbird-exit-node
type: Opaque
stringData:
    NB-SETUP-KEY: ENC[AES256_GCM,data:ddqFTIykUhyYrjfFZg19wfDjIsuFOd4hYNGKmoUHBza0KyCj,iv:6R7CHvbzq63VRrFR7RiW0vYpGmK5iHG3v1GMCIInGGw=,tag:FIgAP+ZYxx+eGP5C95pnMg==,type:str]
    NB-MANAGEMENT-URL: ENC[AES256_GCM,data:pgXS21aZYO5Gow2vcOOeSnJ+Eg==,iv:Frvyp1ONkoD1G07JLNsZViMwVb8voztqewizR2Jw7eY=,tag:Mgga8tqxYz0ISOJIcorz6Q==,type:str]
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0aGsxd3pXckV3RHlpb3Zl
            YXZLWWszZ2w2Q1NpYW5mVGlhRTE5ZW9uZHpjCjAxV0NWdXJvOTRsMDF0RDU5ZlM2
            aXF5YktDdjZEbit0enFuOXg4c0dFL1kKLS0tIG15U0dNYWpEczRMQzhsbG5LLzBa
            M05FcnhIbFo4bm84OTlmVXAzYUtBZzgK+7uA0PuzGmtSxEqajjeDqXXQ4JAgFHFQ
            9vXZNyIxYpcN8geU8ESeJ42Vvfvm3U4+YErhq4feM64tQcIIXbdsUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-31T11:08:13Z"
    mac: ENC[AES256_GCM,data:hfB/4rDF1IGMikNZ3yEmaz21SU2clVwvSpTVbRDKNu3w1q7vzZI389Q9CkJYYjXiWtzTZ2m2N3nk5DxFWOCQmVVwv9n64fif5uGLz7JGbGQMAJXY3wEk4xq6QGSQGUyp3JPcYMn3RAs8oYzkpvExvJdOJ2gRIs86wo8UC5NF8ok=,iv:prL0EQgHvZfX7RRj4WJFcYIKo/dAnouhtvF4GEfCw9Q=,tag:yV1ynLotse+hu5iimUaavg==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    version: 3.12.2
