apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rbd-external-attacher-leases
  namespace: rook-ceph
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rbd-external-attacher-leases
  namespace: rook-ceph
subjects:
  - kind: ServiceAccount
    name: rbd-ctrlplugin-sa
    namespace: rook-ceph
roleRef:
  kind: Role
  name: rbd-external-attacher-leases
  apiGroup: rbac.authorization.k8s.io