apiVersion: apps/v1
kind: Deployment
metadata:
  name: svtplay-dl
  namespace: svtplay-dl
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: svtplay-dl
  template:
    metadata:
      labels:
        app: svtplay-dl
    spec:
      priorityClassName: medium-priority
      automountServiceAccountToken: false
      containers:
      - name: downloader
        image: python:3.11-alpine
        command:
        - sh
        - -c
        - |
          apk add --no-cache ffmpeg gcc musl-dev python3-dev libffi-dev openssl-dev
          pip install --no-cache-dir svtplay-dl
          echo "svtplay-dl är redo!"
          sleep infinity
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "4"
            memory: "2Gi"
        env:
          - name: KUBERNETES_MEMORY_LIMIT
            valueFrom:
              resourceFieldRef:
                containerName: downloader
                resource: limits.memory
        volumeMounts:
        - name: media-storage
          mountPath: /downloads
      volumes:
      - name: media-storage
        persistentVolumeClaim:
          claimName: svtplay-dl