apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: svtplay-dl-backup
  namespace: svtplay-dl
spec:
  sourcePVC: svtplay-dl
  trigger:
    schedule: "0 3 * * *"
  restic:
    copyMethod: Direct
    volumeSnapshotClassName: csi-cephfsplugin-snapclass
    repository: volsync-svtplay-dl-secrets
    pruneIntervalDays: 28
    cacheAccessModes:
      - ReadWriteOnce
    cacheCapacity: 5Gi
    cacheStorageClassName: ceph-rbd-nvme-r1
    storageClassName: ceph-fs-hdd-r2
    moverSecurityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    retain:
      daily: 7
      weekly: 2