apiVersion: v1
kind: Secret
metadata:
    name: volsync-svtplay-dl-secrets
    namespace: svtplay-dl
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:YhLZL1TNs/veiztMGKbxs8hoVR+/LdJZsNPAzk31twaEaTei40szN4IQKc9Y+BAEQBVLbdU+SKMD,iv:YOQFTIcrRki5QvhtpkNGxZq8fnxoEcCXg3kZ+Db5byc=,tag:4eTWICcBsr387bz+zlPTQQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:iFN7xrrPONjKKteyTg9rWTiST6w1DdMyUdSgl8UQG7HB91jGrJAvz9Xt3AGSdxg6ez8=,iv:IUa6YO0Lw9Ap+xdQY6DYfi54e0fZvU6hEqacvLNOE58=,tag:rPXkozwj6cnI6+8cKx2A0w==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:IbG/zOL9KhIH8i/vASgkEg==,iv:kRs1Po6XvciywQFYEVHj2qSH+B4li8zenzty16m5OAo=,tag:870+xx61hsP6oaNTrFdsXA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ZQEYqG8vwD/xYblhY/r6fUah0qUXym0KurtXgs9w+QdDoWoZ+3Hn5ZLF63LtfHtBSbo=,iv:wMjqKQgOtswxIxPlcJz8lCMHZ4/DZ57aAAfKcbI+XlU=,tag:EP6x5YyjwNObUwAPEkkbWA==,type:str]
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtM0szdEkwbG00MGhUNzMx
            TUM3c0VWUkxaeG92WlZhdE00SGZkbSs3QTAwCnNmT21ia1BLU0pDTGl6OG4rOVBV
            dmZtemc1TFpmU0t1ODdNNjRGOENIVm8KLS0tIDhPUzBCU0tOclRiaDdPUUREamM0
            TjZQaW9oS0NsME9GbUxUOHBEWmtMSEUKxFqtGyMcJwSwRW4x7wdeaab9JuiyJ9cK
            rwCs+O1rMxiKntMMPc19LepbTvnUtdIUzMTOaa+uvsXevsiCpRVICg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-06T17:22:32Z"
    mac: ENC[AES256_GCM,data:qkcYVFQjhMxpvbWVIicKlSG765YVohzhk0nkughBa+bqRQ/Svoc883UsmkBxhiiGqUz+8ga1H8Hp1qNdXZkwi7kk0AG7g7enilQtkoi6kD9PDUIkgbyY/ybWChveVvv7IE0jMGCnzHKVKYDxyyOIMOHJ8bLI9Re518y8+xZnoKE=,iv:Ys+HeiZm18Dzy2GPyoZiN4FFOCkxtMFWww19KE4cA3Y=,tag:GA3Fa5FgMVW2A6hW19Kkqw==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    version: 3.12.2
