apiVersion: v1
data:
    ceph-secret: ENC[AES256_GCM,data:SPJJRbTq+EDWO16PSbnnO1vjOEZpPqMbfLJO7QwGXiHSw0tOMOGpLz+lSOIIyVRy2SfksbTGip4=,iv:19Y3fyoBBI0SYyuiPxtnsIHjuZyx0xL5YL6KwT371Bw=,tag:aihS00UPZ9P1u2y6pNDDmQ==,type:str]
    ceph-username: ENC[AES256_GCM,data:8xhCnDSC9vwQEx9/ipt5cA==,iv:xk/1cbp/VJLBCDgMarckKdpNA5nqRkR7jHIyfnOqNQg=,tag:dCSUtrSfr6QMi/Xz+En6Mg==,type:str]
    fsid: ENC[AES256_GCM,data:nC8d1LyXGpMLCVxyVnbMj8xkDYehfgHyFe/O9fdOOZ9vT3FeM+QOKz24jPlM1ph4,iv:Hp8GmLI6oCnKlrZzwN4RqzAj1xwexQiFQA5/fKy+kuk=,tag:56+aqDwxEilC+30kw1gKvQ==,type:str]
    mon-secret: ENC[AES256_GCM,data:Okq44tSXB10FlpFA7cqzXpUExJxLj5925pUNnritXsA80R/MZZ1yXM1kR61Ms1WQ8Q5eRddRjVQ=,iv:KG5I8pvPrSLk2xAYquUAfBxAMPK+nCnW7BB2R+h1aas=,tag:gobKszFjXajfBbZQI+ojvA==,type:str]
kind: Secret
metadata:
    name: rook-ceph-mon
    namespace: rook-ceph
type: kubernetes.io/rook
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQK3QrMVJBL0x5b3NlQzhY
            cFh6TWdJYlAwR01lMDhsam1rVWxFTDcxQ1FJClRYSFNUNWo4KytISk1zaGtwOXJj
            dDl2T0RUWTMwMDZQUWlLSWROM1lUQ3cKLS0tIGVsa1dQQ1k5VWZQTTZGVmFsSlJM
            Tm9HUUFKc1hYM05WWkdXU2RaQVdOa1kK4biQ0E4Lg50CqHB8axQnu/FQxozHmGJ1
            eOZDHVwL6zeyt/3T+EMKJfQhs2z3jxgpiLTenKXBRRLiwrpESlSbiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-17T08:32:13Z"
    mac: ENC[AES256_GCM,data:CagOe4tTwS6EPwHap6XNFVLE8+qP8VmusrX0Fu52IX/tWUrIb+0OKW7M/jDxTYCFfNBW05TRLrSppjyH2K0UYiRRdjCH4j2n6Wfwv044WknDUPM5ua/xmzJ+u/l1/yPJyVLVqUy73xZJXqeQbdB3ySxG4dEfFTpsgnlSJOnn0tA=,iv:0HADQq6xNKP/odQZ4yBBbd64FQzp9wag+47KD+OjlDc=,tag:AvKBDW/9h2bIxvHye+7baA==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|mon_host|mon_initial_members|ceph-secret|ceph-username|fsid|mon-secret)$
    version: 3.12.2
