apiVersion: v1
data:
    keyring: ENC[AES256_GCM,data:cqSyG+g1gfXX7XKHL6lVYZQ7ilpbMzpCuQ2Ing0S/y9MyyBcY1uSE/To2Wkb/S1BDsaD+90sJXRO8a7/77B6hBolcnZyvQ1zcXTK7XegM1OUyG6seYBw3nZP3VciYLAv7HsbHKqOpYEB7rAwy7pP8m+nHgiETXw7zjwQpHwrtJnFaUknHJD0ax41bu9QWhnW9p14TekmLtHOk7hT+O2EiKy0Ca0BthitIAqPDNpcZ9BAsKCMPuI9IfT2l6A7l+XfspnN47wiZkqziGi5,iv:kZxw7AQya1wrAO0nktnUhmEmbdJTXIjikuWTnLipUGo=,tag:EMTCt5dRcmRwlVSSILy2uA==,type:str]
kind: Secret
metadata:
    name: rook-ceph-admin-keyring
    namespace: rook-ceph
type: kubernetes.io/rook
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVRmgrRmdnT3VhSTVEY1dJ
            TmZFWjIyWFZRQ2NadGZmR3VtWi9ISmFMWkJNCldCak5kNTlVVENTeGQvOC9oZ2Y0
            UnJEMzBKTE9SNncyVDd4SERiUUwzL0EKLS0tIDhjVWZoUkRRWmc0ZlpoR29OcXFP
            NzkzTEY1cndtR3FrWjRGZ04reE1TdncKEwJHFAq2I4qIWByGEhw2IU088gfjVJWq
            GXph30CWQIWZJvUfBauVGsA30wui5T7nNxgLXvQG3MuKInuFXLmT3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-17T08:32:31Z"
    mac: ENC[AES256_GCM,data:/ZdtSv04F/XWv5+5ByARP5AaHlkEz6EWlp8wYk2Tw7KKtRYzm8GZ99FvEv6Rd+9jI/kXf4hKa/wnAdBLRpInfKI5ZIQ9UhE2AVcLKkLBACJjTIFIfgRrjg09pg4lohGMFfBSYmgAhwfpsDNoi4/GkRY4dwyo5bMJFzDISEMyV34=,iv:LpZJMrngftGLia3BGKvJXwMVKMxLXpt2pc8oRfsyK9Q=,tag:ibAsGBQ+6BlrYPmY7acznw==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|mon_host|mon_initial_members|ceph-secret|ceph-username|fsid|mon-secret)$
    version: 3.12.2
