apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale-exit
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:gREeKCcBhD00KGJwG/l2U94=,iv:euNmPQKFFmcs4NUR4buVte8qcnFT50Ki9LTZFjr7WME=,tag:XcrQaEyY1jRN8u+bRzKe6w==,type:str]
    client-secret: ENC[AES256_GCM,data:BymQzIe4EtRA3K41EOInG7dVnRQ7Sp0IbqQz33EgSMTyCwo3d4qc7J7YQ9MohYqU7dNQesI21K6SAfbN7q2j6A==,iv:vgDC7Xffappqu3W+NpGa0HeMSx2HsNdyFAOlLUD4o/s=,tag:DAb6B8U28snKbfeKOny4AQ==,type:str]
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWOC9BclorVDlSRzluT0pp
            T1dubFZCTEY1dElhOXR2d1VnOUVhUjdXR0RJCkNUSGV0UjRhZWNHd2dtQ1h5ajF4
            M2gxaU5vbnAxZ05QREorYlpIRGtQckUKLS0tIG56T25GZ054MUk0WUpEWGJhYUo0
            YkVIdDVjT1RWb1RJQkxCTTVvbU9BZG8Kf9uRuQ/Dqcy6RnGo99A6pyfXND8i9xYX
            jwVPwyUuexxJD2Li1tamXG92r5EBLOBTPSb+QJDjMKNMnvFEYie2VA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-15T11:40:56Z"
    mac: ENC[AES256_GCM,data:WkzrmigRPhB9Hnjevf3qdR1iqdPYVF6bEV2DrGLPC6Ft9sEm9sR4bYOUHU2ZCAnk1hksxV22A8CqG88DQBsxhzRPHsgTaEVcmT1p+h+sMOsx6fQemRmIrvExeUKc+VIhxpLe08UGopsxUilnX6o5z/fN5RONryFOSiYOrEcFlBc=,iv:z/JWDqIsrleBkCS2+q8NhOC2ZEdJK9oV4mhkRwwWhPc=,tag:mdAgXhGkAVIRcgNE2R13RQ==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    version: 3.12.2
