---
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: quay.io/ceph/ceph:v20.2.4
    allowUnsupported: false
  dataDirHostPath: /var/lib/rook
  skipUpgradeChecks: false
  continueUpgradeAfterChecksEvenIfNotHealthy: true
  disruptionManagement:
    managePodBudgets: true
    osdMaintenanceTimeout: 30
    pgHealthCheckTimeout: 10
  priorityClassNames:
    all: medium-priority
    mon: high-priority
    osd: urgent-priority
    prepareosd: low-priority
    mgr: high-priority
    crashcollector: low-priority
    exporter: low-priority
  resources:
    osd:
      requests:
        cpu: "250m"
        memory: "2Gi"
      limits:
        memory: "4Gi"
    mon:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        memory: "2Gi"
    mgr:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        memory: "2Gi"
  cephConfig:
    global:
      mon_osd_down_out_interval: "3600"
      osd_recovery_delay_start: "30"
      mon_warn_on_pool_no_redundancy: "false"
      osd_pool_default_size: "2"
      osd_pool_default_min_size: "1"
      osd_pool_default_crush_rule: "0"
      osd_memory_target: "2147483648"
  mon:
    count: 3
    allowMultiplePerNode: false
  mgr:
    count: 2
    allowMultiplePerNode: false
    modules:
      - name: rook
        enabled: true
  placement:
    mon:
      tolerations:
        - key: "node-role/infra-only"
          operator: Equal
          value: "true"
          effect: NoSchedule
    mgr:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
                - key: node-role/infra-only
                  operator: DoesNotExist
    osd:
      tolerations: []
  dashboard:
    enabled: true
    ssl: false
    prometheusEndpoint: "http://kube-prometheus-stack-prometheus.monitoring.svc:9090"
    
  storage:
    useAllNodes: false
    useAllDevices: false
    config:
      encryptedDevice: "true"
    nodes:
      - name: s1-main01-cpwr10
        devices:
          - name: /dev/disk/by-id/wwn-0x50014ee217016a21
          - name: /dev/disk/by-id/wwn-0x5000039da8d00a9a
          - name: /dev/disk/by-id/nvme-eui.001b448b4b44c26c
      - name: s1-main01-cpwr11
        devices:
          - name: /dev/disk/by-id/wwn-0x5000039da8d00a55