---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: rook-ceph-tools
    namespace: rook-ceph
spec:
    replicas: 1
    selector:
        matchLabels:
            app: rook-ceph-tools
    template:
        metadata:
            labels:
                app: rook-ceph-tools
        spec:
            dnsPolicy: ClusterFirstWithHostNet
            containers:
                - name: rook-ceph-tools
                  image: rook/ceph:v1.20.6
                  command:
                    - /bin/bash
                  args:
                    - -m
                    - -c
                    - /usr/local/bin/toolbox.sh
                  imagePullPolicy: IfNotPresent
                  tty: true
                  env:
                    - name: ROOK_CEPH_USERNAME
                      valueFrom:
                        secretKeyRef:
                            name: rook-ceph-mon
                            key: ceph-username
                    - name: ROOK_CEPH_SECRET
                      valueFrom:
                        secretKeyRef:
                            name: rook-ceph-mon
                            key: ceph-secret
                  securityContext:
                    runAsUser: 0
                    runAsGroup: 0
                    privileged: false
                    runAsNonRoot: false
                  resources:
                    requests:
                      memory: "128Mi"
                      cpu: "100m"
                    limits:
                      memory: "256Mi"
                      cpu: "500m"
                  volumeMounts:
                    - mountPath: /etc/ceph
                      name: ceph-config
                    - mountPath: /etc/rook
                      name: mon-endpoint-volume
            volumes:
                - name: ceph-config
                  emptyDir: {}
                - name: mon-endpoint-volume
                  configMap:
                    name: rook-ceph-mon-endpoints
                    items:
                      - key: data
                        path: mon-endpoints