---
apiVersion: ceph.rook.io/v1
kind: CephFilesystemSubVolumeGroup
metadata:
  name: tm-claes-hedlund
  namespace: rook-ceph
spec:
  filesystemName: ceph-filesystem-hdd
  pinning:
    distributed: 1
---
apiVersion: ceph.rook.io/v1
kind: CephFilesystemSubVolumeGroup
metadata:
  name: tm-asa-hedlund
  namespace: rook-ceph
spec:
  filesystemName: ceph-filesystem-nvme
  pinning:
    distributed: 1
---