apiVersion: v1
kind: Secret
metadata:
    name: influxdb-secrets
    namespace: influxdb
type: Opaque
stringData:
    TOKEN:
        id: ENC[AES256_GCM,data:4w==,iv:/g1ql4N7ka8i9rIbKp2VweOYGWEUmHTwMNg0xn6H3ZQ=,tag:F+HtCJmQqUFit7bEyffmsQ==,type:int]
        name: ENC[AES256_GCM,data:SA2E9SbA,iv:Qz7fYYH4r2nZdpQhc3W/RQJ7ljB1trOAThvggt3uG7g=,tag:sZuaRfdZVZLgQBa5qVDI9Q==,type:str]
        token: ENC[AES256_GCM,data:VqDQXRkrIRvpGyj+CV5kM6HGAmDLsH72xoEyHuaJHreJfNpo6B2S6zT17NxRZ/jed/1ak1a4WSV6K60oiefhxQPPSG/rfiB1XN7AURfE/97NIzenT0T8+0gZyVs=,iv:utAP17M1KwFOfMVuLFaxcYT0jLl+EdKCCFF78mnZoyg=,tag:XULV+MhWwckwVKLq+1MVYQ==,type:str]
        hash: ENC[AES256_GCM,data:jUSAD1BfxcZczQ0RKAU9GgvJo9rmDAKGqb6zoFHev+33tA5iFBadmVyC3XINkTP6lZcrId0Es3Qu7/C/cGy2zh67c8RGWG2fJJ1pCZ15y8d26qS6vljhVAZVUxLqzHyLnMnKRPpZGkT6mU/pLY0rpd6H2qQ+e474XMrLqFQvcVg=,iv:v3xARqql5bk3uLyNfXbmP4GSL3S6uizriS5xQ35uOkQ=,tag:8KeNE/BsAp4y8rWFxCK0gw==,type:str]
        created_at: ENC[AES256_GCM,data:2l1SpZkJQvcHYd48RRbqVE0tP2X1Hrzi,iv:cphGdVflGvQJA37kcJdoPDvTDJN5A4OCfCAo84a0jYE=,tag:WG3iRDYdROXj3svfX0iufA==,type:str]
        expiry: null
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsQjgyV1l5dEZWRUpNQ0t6
            UUJsWi84YnRhdkpjQUNIOU1YOHFSYW9ZWUdrCmlNdzA1R3Rta05qUlFORDRmcUh4
            VTZVNWtxaENUK0NpTUpNdm1la0JVZjQKLS0tIGw2VUVhdlZTUGZyM0dJOE5NdzIx
            WWNPbEZsK2tWR0VZVEVobk1iajJQY00KBc7nmzfU7lZ4roJ/+RtJngYDBf29j2wG
            pZsA+BlId99KcOxi3MKYI6QUEFHy1ewodzyI6SgjHP4s3DbQ5mx8jA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    lastmodified: "2026-09-03T12:48:03Z"
    mac: ENC[AES256_GCM,data:a5bQ++HXRb0grp3quSNgGjG0jJaqnVfaQE16XSS+8qqSwYXo+6f2MRRnZWAldVLtWhTfAe9BYp6tv4F+Row/Ln4haqriFbb/rbJjNXWpkKgkXDIndnElPHQFtt2Y28kuRora9iab2DsVLJ+HcKxouEUQnWdpw1nrQGlT8hRNtO8=,iv:7S/4kSm86ClV++07WuK0uD0feW5D0P1MVynVjnVdUec=,tag:4aeoBQMc4SMo7ZXPtLEUSg==,type:str]
    version: 3.13.3
