apiVersion: v1
kind: Secret
metadata:
    name: influxdb-secrets
    namespace: influxdb
type: Opaque
stringData:
    TOKEN:
        id: ENC[AES256_GCM,data:/w==,iv:HKWR3wRDnRWXoPL7B/iIoWXAAx/vJsw94ZZdIr+ta7U=,tag:nVpH3tW4q08dlMZFI55IpQ==,type:int]
        name: ENC[AES256_GCM,data:zgtHlR0g,iv:KdV/BVEIozYawaLHuV+IrDIkazCXMNq3He+IgAXG2/Y=,tag:vgVAKtmTIj8zSiTbxmfv0w==,type:str]
        token: ENC[AES256_GCM,data:a00T9Lkq0lx63tgYqGSyCx3fMjnXKmkcvsRPX9mpcyYoDMqJaUTuUlvkmR8eY14vbamW2/kfCyZRVq0qANGsf70bA8M985vhJ4wR59NbvnDg0E5BGmJABljR1cA=,iv:y9k9t5clY6qLYcR0gf1WrW8p00we6KI++SjOifA9KS8=,tag:yrxABswHb4Xyu/6RyjXThA==,type:str]
        hash: ENC[AES256_GCM,data:I+Jwf59gpK+R9XJqcZlRS438FJ5hxjyTzkUOeGDcZNLIBZhImD0xWNDDpHUwSYqacZWRdztLJ1+VoZF5RSBCAB1/1dZoHsWHDMVgNClM/Swx79RQaCqRY9Rbh2GjoSeQJui/OdTuLYEL/8GeLgcA+uuMng6s75h9+0SI6qdgkXE=,iv:TYZ7WOZQ3ev83OHHVvQc9xqRLivkQHNO7GcjPIRmGPA=,tag:nM3Gplt1AqAn03bjJWKJxQ==,type:str]
        created_at: ENC[AES256_GCM,data:FVfeqCK0UODLk9kWHe+t17Wdk2dQ9mg7,iv:1TaZWuBKnavHQrMQFrREq8qUv34dhOWTrccL6b6hV1I=,tag:yKIIZJERqHaoVGZVoAvkKA==,type:str]
        expiry: null
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsQjgyV1l5dEZWRUpNQ0t6
            UUJsWi84YnRhdkpjQUNIOU1YOHFSYW9ZWUdrCmlNdzA1R3Rta05qUlFORDRmcUh4
            VTZVNWtxaENUK0NpTUpNdm1la0JVZjQKLS0tIGw2VUVhdlZTUGZyM0dJOE5NdzIx
            WWNPbEZsK2tWR0VZVEVobk1iajJQY00KBc7nmzfU7lZ4roJ/+RtJngYDBf29j2wG
            pZsA+BlId99KcOxi3MKYI6QUEFHy1ewodzyI6SgjHP4s3DbQ5mx8jA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    lastmodified: "2026-09-08T11:26:49Z"
    mac: ENC[AES256_GCM,data:EEws4l+sKy9hUdv9uUw2RzPK+pD3AkLwY2azlrTAWg4v9q2sy+QbKX4Ayh4Zp6NlfmMp3FJ9WTlQNwFdpzeykC1J1M3a6jELWBplqLnmokvSs1AXmz+AEqhMWBpYjGiPXzE207mBVlnuWO2qrxJb+M5OxEmXs0BiR7Cbl4rDVqE=,iv:F3iVw8FrfkslpF5Ji/ntk/OKiAgD8Cqjji/A+DexNQc=,tag:sM+bZKpSt0XniPTGkcZBwQ==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: influxdb-data-backup-secrets
    namespace: influxdb
type: Opaque
stringData:
    S3_ACCESS_KEY: ENC[AES256_GCM,data:w8FUZU73E9VayQpmcbPjEQ==,iv:mTzLsqgJO+c+oOIby39tB3qUK1DyMcr30T0CGKkSN+w=,tag:ElmkESNIDElpNAHLV01H4g==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:o3YP/DAdqNL3axbrpgW9o/PJ0oKoULPOCVt+KsjQguq6XTIV/66hNJ+95xmEn/axjZA=,iv:3jKbQVO32tkIJqSiHAQlof8Z1Mrl9Z3H+fP0SdRccnk=,tag:Um26vZKscz3mczGPPfAfEQ==,type:str]
    S3_ENDPOINT: ENC[AES256_GCM,data:7Fwq+OcmLaQCN/LEKEO69d49IZhUgkHfzZ8=,iv:hLebfoy8mWPLRZIVgUJU47pYaFByL526gImvvPfhjy8=,tag:0+Vbk6grVfzsLNrEWo4ovg==,type:str]
    S3_BUCKET: ENC[AES256_GCM,data:gikEDigFUwss70vUfwf1kaAszDGhrA2nGdVEJh4d,iv:HYgrh/f9UZ3gKzsUsVfSwlIebeBROqhL5vkBePFJ0gs=,tag:cRDgOxPIiMy81XYG0VTYuQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsQjgyV1l5dEZWRUpNQ0t6
            UUJsWi84YnRhdkpjQUNIOU1YOHFSYW9ZWUdrCmlNdzA1R3Rta05qUlFORDRmcUh4
            VTZVNWtxaENUK0NpTUpNdm1la0JVZjQKLS0tIGw2VUVhdlZTUGZyM0dJOE5NdzIx
            WWNPbEZsK2tWR0VZVEVobk1iajJQY00KBc7nmzfU7lZ4roJ/+RtJngYDBf29j2wG
            pZsA+BlId99KcOxi3MKYI6QUEFHy1ewodzyI6SgjHP4s3DbQ5mx8jA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    lastmodified: "2026-09-08T11:26:49Z"
    mac: ENC[AES256_GCM,data:EEws4l+sKy9hUdv9uUw2RzPK+pD3AkLwY2azlrTAWg4v9q2sy+QbKX4Ayh4Zp6NlfmMp3FJ9WTlQNwFdpzeykC1J1M3a6jELWBplqLnmokvSs1AXmz+AEqhMWBpYjGiPXzE207mBVlnuWO2qrxJb+M5OxEmXs0BiR7Cbl4rDVqE=,iv:F3iVw8FrfkslpF5Ji/ntk/OKiAgD8Cqjji/A+DexNQc=,tag:sM+bZKpSt0XniPTGkcZBwQ==,type:str]
    version: 3.13.3
