---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: iperf3-server
  namespace: flux-system
spec:
  interval: 60m
  path: ./kubernetes/apps/iperf3-server
  prune: true
  wait: true
  timeout: 30m
  sourceRef:
    kind: GitRepository
    name: flux-system