apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tailscale-exit-operator
  namespace: flux-system
spec:
  dependsOn:
    - name: cilium-infrastructure
  interval: 15m
  path: ./kubernetes/apps/tailscale-exit/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age