---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - kustomization-cilium-infrastructure
  - kustomization-rook-ceph-infrastructure
  - kustomization-rook-ceph-operator
  - kustomization-rook-ceph-cluster
