---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - kustomization-priority-classes.yaml
  - kustomization-cilium-infrastructure.yaml
  - kustomization-rook-ceph-infrastructure.yaml
  - kustomization-rook-ceph-secrets.yaml
  - kustomization-rook-ceph-operator.yaml
  - kustomization-rook-ceph-cluster.yaml
  - kustomization-samba.yaml
