---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - kustomization-priority-classes.yaml
  - kustomization-cilium-infrastructure.yaml
  - ks-rook-ceph-infrastructure.yaml
  - ks-rook-ceph-operator.yaml
  - ks-rook-ceph-cluster.yaml
  - ks-rook-ceph-csi-drivers.yaml
  - ks-rook-ceph-pools.yaml
  - ks-storage-infrastructure.yaml
  - ks-monitoring.yaml
  - ks-samba.yaml
  - kustomization-metrics-server.yaml
  - kustomization-svtplay-dl.yaml
  - kustomization-podcast.yaml
  - ks-localai.yaml
  - ks-librespeed.yaml
  - ks-iperf3.yaml
  - ks-cert-manager.yaml
  - ks-vaultwarden.yaml
  - ks-netbird-exit-node.yaml
  - ks-renovate.yaml
  - ks-snapshot-controller.yaml
  - ks-volsync.yaml
  - ks-immich.yaml
  - ks-cnpg-system.yaml
  - ks-influxdb.yaml
  - ks-syncthing.yaml
  - ks-victoriametrics.yaml