apiVersion: v1
kind: ConfigMap
metadata:
    name: rook-config-override
    namespace: rook-ceph
data:
    config: |-
        [global]
        client_mount_timeout = 5
        mon_client_ping_timeout = 5
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlS2xqWTIvc3NyWHBjZVVZ
            MFRzQk1KZkRDQVIycjJvS2VSbjVWRzVSQUhjClA4MDFscVVCL0tRa2V6bTZBQWRy
            bXQvNWJsbXNlSmhBS25DT0JrZTR1YTAKLS0tIEtQSU5DRjRwSEpTN25MNytwZWdR
            NFpjMC9kR21aRFl4SHZMREtCNUw5VUEKqQAHbcBen1VUSbjxKeHd7SxztgALL4g5
            52YUOdnLOWduJsTOwSZPQ8fQrxXzzDU6us6acHTfD38+cjcSHqVclw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-19T11:09:12Z"
    mac: ENC[AES256_GCM,data:5JAGUudMaC7QSZEb8Y7yj2C1kKTz/r8/NzgqdJ0Httm5TTy+1U+Zq+1XnCF1j2WxU6GqHUBMuJYTuye7607o9rEVaDr1GMAAdS/mvq1CIaSQhtUPfBSgdy8Orm+YI/U8eQDX7ghTMqlUqT0EffCo+F8lVEBlv2fO0ZEARNac+jo=,iv:L0OSEGthzXNFcVvKTaBHT+E5nP9NiX+Qu6wOh2OIWTE=,tag:8xE08bQQ+h//FjcyXmv6qQ==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|mon_host|mon_initial_members|ceph-secret|ceph-username|fsid|mon-secret)$
    version: 3.12.2
