apiVersion: v1
kind: ConfigMap
metadata:
    name: rook-config
    namespace: rook-ceph
data:
    config: |-
        [global]
        client_mount_timeout = 5
        mon_client_ping_timeout = 5
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZakNTNHRPZktVK05pUnZn
            dGpsQjhaWUlISmJ3WSsrQWxJNVZzUTJ0ZmhJCkNPMlJiUzFUVkZkcVh0ME13dzNo
            eVNLeXZsd1V1cjhlN2xLY3ZVV0dpQzQKLS0tIHpKMTJENmI0dUFRYmpuQUlJR0NR
            SGgvdG5uZENjQndVWm43SDZHMGlXbzQKHDf+gl2J0PNQVI/8gW/LMa4VNPNnYeYA
            AipkNHxOwJIEyPEcjL3vlRo2IZAjh6VXlGuGJnFlnvzCQkCK1cSHOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-19T09:33:08Z"
    mac: ENC[AES256_GCM,data:mUfOj5+Ro8V5e6oz4l1i0hjomYOMu/7r6jkrE8s6wWdUyO1Jzsb/wFbAWTrNK1aFqvNokFjTj0Yv91PYouaV90oAf8IZ+6aufV5Q3Dbf9eMuSDswPGUbimSSdHw8h8b2K2RbPtRdqcvTGz5F2zuGtVLS6PaWv3bn0zx29Lw2Rsc=,iv:pf68Gej6+vKpUP3T1lRakCc1CJ0wR9pUhXlpgVm+cn0=,tag:pETGjrQPGfL69gsI7DJaWQ==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|mon_host|mon_initial_members|ceph-secret|ceph-username|fsid|mon-secret)$
    version: 3.12.2
