apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: rook-ceph-cluster
    namespace: rook-ceph
spec:
    interval: 30m
    dependsOn:
        - name: rook-ceph
    chart:
        spec:
            chart: rook-ceph-cluster
            version: v1.19.5
            sourceRef:
                kind: HelmRepository
                name: rook-release
                namespace: flux-system
    values:
        operatorNamespace: rook-ceph
        cephClusterSpec:
            mon:
                count: 1
                allowMultiplePerNode: true
            mgr:
                count: 1
            dashboard:
                enabled: true
                ssl: false
            storage:
                useAllNodes: false
                useAllDevices: false
                nodes:
                    - name: s1-main01-cpwr01
                      devices:
                        # HDD disks
                        - name: naa.50014ee217016a21
                        - name: naa.5000039da8d00a9a
                        # NVMe disk
                        - name: eui.001b448b4b44c26c
        
        
        cephBlockPools:
        - name: ceph-blockpool-hdd
          spec:
                failureDomain: osd
                replicated:
                    size: 2
                deviceClass: hdd
          storageClass:
            enabled: true
            name: ceph-block-hdd
            isDefault: true
            reclaimPolicy: Delete
            allowVolumeExpansion: true

        - name: ceph-blockpool-nvme
          spec:
            failureDomain: osd
            replicated:
                size: 1
            deviceClass: nvme
          storageClass:
            enabled: true
            name: ceph-block-nvme
            isDefault: false
            reclaimPolicy: Delete
            allowVolumeExpansion: true

        cephFileSystems: []
        cephObjectStores: []