---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: rook-ceph-quota
  namespace: rook-ceph
spec:
  hard:
    requests.memory: 2000Mi
    limits.memory: 7000Mi
    requests.cpu: "1250m"
    limits.cpu: "5000m"