---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: rook-ceph-quota
  namespace: rook-ceph
spec:
  hard:
    requests.memory: 6000Mi
    limits.memory: 7000Mi
    requests.cpu: "4000m"
    limits.cpu: "5000m"