apiVersion: v1
kind: Secret
metadata:
    name: localai-secrets
    namespace: localai
type: Opaque
stringData:
    p2p-token: ENC[AES256_GCM,data:EuWJ6QzmGXJ/dBJzkDlyX+MRAU8VBDl1O1pB7J6J59VeAOhhrsA9iJSo664=,iv:bBw90K2iy38pErHfZwpa4p1uI4EqHcdFzBgvwggPhms=,tag:wul2j/v/Iiz/9GSEB/Y79A==,type:str]
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlWERjUUp6dHB2K3AwUWZh
            ekNzdUNOaklmSFhZVVpSdkxndjJGL0JRTEMwCnhINGNlZlpjc3duL2tuKzZsMzRN
            UVg2ZFYvK0JRblh0U3hDSVpqd21ha1EKLS0tIDZqQ1ArdG92YnJpN3ZibkNHeHpo
            bjhKV1g4RFh0UW4ySi9ZVUtXMEVPcHcKjwOBHFD+C7R9SKmzh/XXDTTx7//mePiC
            p5NEzt5XzMnlxVNGIO6fDyqlikaRm5WWZwEqS8s5tYKLvtsopKYsMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-29T17:42:13Z"
    mac: ENC[AES256_GCM,data:d3yxyHfF1JVo2DtGKOpTTTfh3MIxvowduI0Ub9PVQZSU0e4r9/gSGQ7wavoMB2GjbSZMPViPJ8XQvpW3silwx5u1BxUgJswqPb96UtouiXLhrF09YpiYxXOD+kF1o5hafZ5PX1p2JZP9cN1yHQpN3itLCnJhtm6w8VNz/eDI3wA=,iv:VQs0l6tCnimTTTEaUM2fhfjv44zmk89GMDEr8eOxCHQ=,tag:NZ3+LJCbylLiCAGgXCO8+w==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    version: 3.12.2
