apiVersion: v1
kind: Secret
metadata:
    name: localai-secrets
    namespace: localai
type: Opaque
stringData:
    p2p-token: ENC[AES256_GCM,data:lzqFJ0hIyg9neyz3e+Xfm4bj+p04qFUtJqWIV7VtHMWouDmdTmbi2+La/4UAGJDGeE/zX3+ChdalpEdpP6p7+fJ2E76YL6yyKsXLeULDD9evBuVBi3BffaIt2P1HLyicKP4B132HxqwK0vR5n8o7yOYN5ybc9JvBxMENKZqAgpjzfn8nS2t8tf+VTUQ9TLQBEvjRtXJTQiQAIdhFim1hcxBUe0GaANUH7VqFlPXaCqR2ZMrAMhp3fCCcD58bt3gRPgiXiHUG8KGCpV8+XlFFAKQ1mKHzje2Hv3rJdrOemZuxyxtoUX8rWiPzV30kRPw5pr1sSJSDPnN95Rg2fKFrWQWtzXFWoknyugQNNn2RJqflU9oWx2deRqGC2X8GdA6mF9ke+WTF/oY5JF7AdrACG5T7FVLJZTiWBZ8yDpqCKnc8VzQ/MXDe5A1Sj6dhPRwStLRSqVpgGhdPAsyRPWAhw1yEEAqYSU0KuDewo1D46/M2oJhpiqGiexs0AIUmLfzSN+KjdnZ7wpN8TJ98Hxly9fHaoYkTOmBNj7E/hq7Rdvt2b490zqDtnlw6nSJOF7IXFpgcSzYpV5+ZhNGt78C0KoFfY25QQt84r7gJC1MjR70mNxsZ2KkjC+1Cv9OemCZ4WkkIM179d+1UuPtI/7WrqqNyZOTy0pRL,iv:/jcGLbo+ynM3yVPBOKhUvngRDsm4li+p9EY3rCasSUQ=,tag:6LveSfIiuuwzKO5B7znFcA==,type:str]
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlWERjUUp6dHB2K3AwUWZh
            ekNzdUNOaklmSFhZVVpSdkxndjJGL0JRTEMwCnhINGNlZlpjc3duL2tuKzZsMzRN
            UVg2ZFYvK0JRblh0U3hDSVpqd21ha1EKLS0tIDZqQ1ArdG92YnJpN3ZibkNHeHpo
            bjhKV1g4RFh0UW4ySi9ZVUtXMEVPcHcKjwOBHFD+C7R9SKmzh/XXDTTx7//mePiC
            p5NEzt5XzMnlxVNGIO6fDyqlikaRm5WWZwEqS8s5tYKLvtsopKYsMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-29T17:51:15Z"
    mac: ENC[AES256_GCM,data:9/l98qvgAQOunquRsmqzmTe81AQWtw7+COESVBq8nYURtSpnvvFnVPSFp9+/9TIlor7gqB1UrRxzHrcCi2yiCZUa/DftRCkDrBxzC+XF9SU3KEFfZTtxvSh5j9WJ8P3KUPtr2AsrwhfYlX2Ni6xvkIJmIZlzZNF1xwKr4n6igGA=,iv:Sx1SCs3WsCT6tvpNZmBWHHJ0T8GyKbKTFFNFYoSUWYk=,tag:Jemc6Lcoik+dBV+gDPYufg==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    version: 3.12.2
