apiVersion: v1
kind: Secret
metadata:
    name: localai-secrets
    namespace: localai
type: Opaque
stringData:
    p2p-token: ""
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlWERjUUp6dHB2K3AwUWZh
            ekNzdUNOaklmSFhZVVpSdkxndjJGL0JRTEMwCnhINGNlZlpjc3duL2tuKzZsMzRN
            UVg2ZFYvK0JRblh0U3hDSVpqd21ha1EKLS0tIDZqQ1ArdG92YnJpN3ZibkNHeHpo
            bjhKV1g4RFh0UW4ySi9ZVUtXMEVPcHcKjwOBHFD+C7R9SKmzh/XXDTTx7//mePiC
            p5NEzt5XzMnlxVNGIO6fDyqlikaRm5WWZwEqS8s5tYKLvtsopKYsMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-29T17:48:36Z"
    mac: ENC[AES256_GCM,data:rS9pEtA0AnrzwR899CnGXhrvXmN/oUgFYbQKo9GrlRNwErWTd59o8/Nwe1u3VXL/l05izeiUm0FY5CQvTUpL2Ei2ZLrTnV+lqBYFRgD7OanDPsKkr6wRkHRlFONCYhJuplNjzCOSjs5UWhwkozoZtPPqffYbLg0kdPF6d4fcins=,iv:1p4cHzO4e/7sxBREhV+KylBH4aj2fCeue8oHgbtkyOg=,tag:crbV40Hyg4mm+NbO6s3Q5Q==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    version: 3.12.2
