apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netbird-operator
  namespace: netbird
spec:
  interval: 10m
  targetNamespace: netbird
  chart:
    spec:
      chart: netbird-operator
      version: "0.8.0"
      sourceRef:
        kind: HelmRepository
        name: netbird
        namespace: netbird
  values:
    installCRDs: true
    webhook:
      enabled: false
    metrics:
      webhook:
        certManager:
          enabled: false
  valuesFrom:
    - kind: Secret
      name: netbird-operator-secret
      valuesKey: setup-key
      targetPath: setupKey
    - kind: Secret
      name: netbird-operator-secret
      valuesKey: management-url
      targetPath: managementURL