---
apiVersion: netbird.io/v1alpha1
kind: NetworkRouter
metadata:
  name: s1-main01
  namespace: netbird
spec:
  dnsZoneRef:
    name: ${DNS_ZONE_NAME}
  volumeMounts:
    - name: config-dir
      mountPath: /root/.config
    - name: netbird-state
      mountPath: /var/lib/netbird
  volumes:
    - name: config-dir
      emptyDir: {}
    - name: netbird-state
      emptyDir: {}