apiVersion: v1
kind: Secret
metadata:
    name: netbird-operator-secret
    namespace: netbird
type: Opaque
stringData:
    setup-key: ENC[AES256_GCM,data:RngqOXJjlDiF1ZvoR3YHKKpQTcvcQOn9gSL3MBctsmt2U/CN,iv:YN1pju1PgtkCPF8agR8KvbYklh7ishn+LujVsk1IhoM=,tag:+mxLi1mieBqHJyQ3F7WwpQ==,type:str]
    management-url: ENC[AES256_GCM,data:4tpjw57uk1hCRW49fqaVXNJlBg==,iv:R5nCfL08fQ8o9dOx9KdZoaR2D/kt9Z4YzAlEoTFvBws=,tag:Gjry04OWTsZQ+hRKNoSqTg==,type:str]
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQK1FQNHBraXhjOFdVM2dW
            VGZSTjZUSkEvL1FWZVJteWsyc0J6MitZVmdvCjFQSzJkUWx2Q3FHTDZYRXdZS0N4
            dnZKamZrZUdOTkZUd0Z4MmlsVjRZcEkKLS0tIE1uSDloYWQwOXQ5TFI5TnJlVnhG
            VDN2eElPcHdleG1HV0hoVy9oK3ZoVkEKDMjm2BWCXUMrAtOKoGZVziBJ6jV6Yrff
            b26VkWEwYJNecU8tEUgHz0EAxgqg2u3RkOKBPokD6FO6zt+HgyEXeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-20T09:55:01Z"
    mac: ENC[AES256_GCM,data:gBdK5qfPvoQc3yQ7nVZ0BsPcJaMfmakAJ4Jsneuw+KXxZJ1HawEN187nmqGN3iQ3JpUi4Vm00z2/d3xn21Df48o6lAAtJDBWmd2+Diq3qmQ5qNQF88GMU4Z3vllf8XlYkivU4OpzZRVFtHV+14VYksyS8TLY/lUkuZ5LD8faPjA=,iv:JHOQgc5YcmbHqVGUyCZ4wu7XgnT89h0gk2WxBWOmu5o=,tag:g48tJmRd9gwGoapy+Wxg+Q==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: netbird-mgmt-api-key
    namespace: netbird
type: Opaque
stringData:
    NB_API_KEY: ENC[AES256_GCM,data:GrfdbbK6ArrjEyJBQ5Sp57RNyZz1Xc1ODoqbCTR/SQ1bAOYDMq3xmw==,iv:iH1llnI2ti7Pg6yEntI1lgQ4wxeJhsA9zTh2vStUM08=,tag:/BncIHsdB4B7q/evn+rI1A==,type:str]
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQK1FQNHBraXhjOFdVM2dW
            VGZSTjZUSkEvL1FWZVJteWsyc0J6MitZVmdvCjFQSzJkUWx2Q3FHTDZYRXdZS0N4
            dnZKamZrZUdOTkZUd0Z4MmlsVjRZcEkKLS0tIE1uSDloYWQwOXQ5TFI5TnJlVnhG
            VDN2eElPcHdleG1HV0hoVy9oK3ZoVkEKDMjm2BWCXUMrAtOKoGZVziBJ6jV6Yrff
            b26VkWEwYJNecU8tEUgHz0EAxgqg2u3RkOKBPokD6FO6zt+HgyEXeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-20T09:55:01Z"
    mac: ENC[AES256_GCM,data:gBdK5qfPvoQc3yQ7nVZ0BsPcJaMfmakAJ4Jsneuw+KXxZJ1HawEN187nmqGN3iQ3JpUi4Vm00z2/d3xn21Df48o6lAAtJDBWmd2+Diq3qmQ5qNQF88GMU4Z3vllf8XlYkivU4OpzZRVFtHV+14VYksyS8TLY/lUkuZ5LD8faPjA=,iv:JHOQgc5YcmbHqVGUyCZ4wu7XgnT89h0gk2WxBWOmu5o=,tag:g48tJmRd9gwGoapy+Wxg+Q==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    version: 3.12.2
