apiVersion: v1
kind: Secret
metadata:
    name: netbird-operator-secret
    namespace: netbird
type: Opaque
stringData:
    setup-key: ENC[AES256_GCM,data:RngqOXJjlDiF1ZvoR3YHKKpQTcvcQOn9gSL3MBctsmt2U/CN,iv:YN1pju1PgtkCPF8agR8KvbYklh7ishn+LujVsk1IhoM=,tag:+mxLi1mieBqHJyQ3F7WwpQ==,type:str]
    management-url: ENC[AES256_GCM,data:4tpjw57uk1hCRW49fqaVXNJlBg==,iv:R5nCfL08fQ8o9dOx9KdZoaR2D/kt9Z4YzAlEoTFvBws=,tag:Gjry04OWTsZQ+hRKNoSqTg==,type:str]
    api-key: ENC[AES256_GCM,data:VUBU1TDiY8rzYiiN9x5HjyXkxPH2cEf52sYkEGQ0vmtwGcG0FHXllw==,iv:/Kah38ZfxQb7h7AkZQgaQTq7KeEVgK92Yl2v/sXIvrA=,tag:SAnQT0WcW+cS4eBUeeJE9Q==,type:str]
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQK1FQNHBraXhjOFdVM2dW
            VGZSTjZUSkEvL1FWZVJteWsyc0J6MitZVmdvCjFQSzJkUWx2Q3FHTDZYRXdZS0N4
            dnZKamZrZUdOTkZUd0Z4MmlsVjRZcEkKLS0tIE1uSDloYWQwOXQ5TFI5TnJlVnhG
            VDN2eElPcHdleG1HV0hoVy9oK3ZoVkEKDMjm2BWCXUMrAtOKoGZVziBJ6jV6Yrff
            b26VkWEwYJNecU8tEUgHz0EAxgqg2u3RkOKBPokD6FO6zt+HgyEXeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-20T09:48:48Z"
    mac: ENC[AES256_GCM,data:05ulEP4elI7otbIQ/tw5Tks56+wLAS9PouUnXflUMuDkA1AsKv4fwrTiqGsnggUk5dKmS2ZS7BITFvj3Sol1ecwdVICzCBqjc0QDesGzqGqz/u1Q123qCZUqkPJVkEkvlLSaugMAnSnuemSBOYI5q1jgW+twyF93mKyINJI2U5I=,iv:ujDZk0fO8HHerI2Zbjs36jEzmIBhPDVyS0Jzonz2sFI=,tag:0031o1HKYo7+rZcFn7LppQ==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    version: 3.12.2
