apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: victoriametrics-data
  namespace: victoriametrics
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd-hdd-r2
  resources:
    requests:
      storage: 100Gi