apiVersion: v1
kind: Secret
metadata:
    name: victoriametrics-auth
    namespace: victoriametrics
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:BZDLVD8mB4z4LfAFlB7r765yVYyTgQeVELYYJh1iEQJrEnr7CAxxOQf4CUFeMEzyEFU=,iv:5vC+MU0g1gPHZHNUBJbC2bkD9m9ng/Mtc9GD8AVx3o4=,tag:2gq07yg9Vp8hyMJGesX1EA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCTFduNmdKMFFNbyt2Mkox
            ZlFmSnkrdUZnTGZJYmtuUEVKUjdHMHlEVmhzCjc5Ni83VjN4UlphSlI2K3c0eHNS
            K3FLSHJxN2dFZWhUaWhjOWIzSUN2ZmMKLS0tIGN2bFFsUHhDVUY1QkJYTlA3c2ZT
            YlQ4b3pyTTBoSXF3OGdtVlFza1k3ZWcK9PeG2PQozV/4Mj/FBP/Y6ViivWproPET
            BGnLzr4s2cydLmqf81CFae3FH1BcGQ0tYxYmr6dIwZFx2wfRXK2nHg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    lastmodified: "2026-09-04T08:13:17Z"
    mac: ENC[AES256_GCM,data:+EGvoGTZUmyg/ggUsO44pxEx0v3qANm+vNt2B1pyo9BkJ6MhP8EGFdSIyuLrWQDixKOq+b4rl7ZyebyCMlJdk11myggOu4fKcPyvO0lxw7XSkJLtaBKaGmD2+JYZwWTnumY4HxAtGsTIKzKAZbmswAtKjIMJhfoIO01/4QEuoZQ=,iv:tUU9ygASY1nkAVKHMfDZnr6mvAxkPzquokqJdDksqBI=,tag:UIy7MaOU9f1DUgDa3mSC7Q==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: victoriametrics-data-volsync-secret
    namespace: victoriametrics
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:PIiIdl8PE1QilmJp4qIeadUiqaRiZSyuQ2wokUQdC/EbT6x6WLcHNw9s6LoK3VPcCJ1H6lRPQhEvaIO3RWRzzkHchQ==,iv:d1LxbdMW+J798zP2gZpDt3NZxxsxxeewoiIM+PG1lfM=,tag:pJCZLhzz6AveRB15GtmXGw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:RZdR0GhyLRKuTIT3z/OMyoeBvgPzWgHdP/QxdJr+qvdsNfJRTX1qnE+mBlcG9aBj+ak=,iv:Cgn4KTMCVG8ev/izWRvQZBC5DEGxZAsyNji5vTIjmk4=,tag:TKzRIHjOGjCMMPLdWpzAdg==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:5Y81iYUPLNM98+iA9ez1CA==,iv:1mLviB1c9eowJ0pzGMQSj3yzBIS7fkWAVqG0GhPDcOA=,tag:ARUtQngAQtGVva8pMsAVkA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:lamvmh7Co3UD2vNJtcFvoT3iokNsHFk3dmzUtz/dqEoJKZWcwTcX+XPZ25CxCAu2DMo=,iv:4lcTn4PGKEvorqkNIid4YKZKSRmhjNu7/oFkA8lJ4pg=,tag:yeJoLaecezemWZFuOsTR9g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCTFduNmdKMFFNbyt2Mkox
            ZlFmSnkrdUZnTGZJYmtuUEVKUjdHMHlEVmhzCjc5Ni83VjN4UlphSlI2K3c0eHNS
            K3FLSHJxN2dFZWhUaWhjOWIzSUN2ZmMKLS0tIGN2bFFsUHhDVUY1QkJYTlA3c2ZT
            YlQ4b3pyTTBoSXF3OGdtVlFza1k3ZWcK9PeG2PQozV/4Mj/FBP/Y6ViivWproPET
            BGnLzr4s2cydLmqf81CFae3FH1BcGQ0tYxYmr6dIwZFx2wfRXK2nHg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    lastmodified: "2026-09-04T08:13:17Z"
    mac: ENC[AES256_GCM,data:+EGvoGTZUmyg/ggUsO44pxEx0v3qANm+vNt2B1pyo9BkJ6MhP8EGFdSIyuLrWQDixKOq+b4rl7ZyebyCMlJdk11myggOu4fKcPyvO0lxw7XSkJLtaBKaGmD2+JYZwWTnumY4HxAtGsTIKzKAZbmswAtKjIMJhfoIO01/4QEuoZQ=,iv:tUU9ygASY1nkAVKHMfDZnr6mvAxkPzquokqJdDksqBI=,tag:UIy7MaOU9f1DUgDa3mSC7Q==,type:str]
    version: 3.13.3
