apiVersion: v1
kind: Service
metadata:
  name: victoriametrics
  namespace: victoriametrics
  annotations:
    io.cilium/lb-ipam-ips: "192.168.201.128"
spec:
  type: LoadBalancer
  selector:
    app: victoriametrics
  ports:
    - name: http
      port: 8428
      targetPort: 8428