---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-caddy-config
  namespace: monitoring
data:
  Caddyfile: |-
    {
      auto_https off
    }
    :443 {
      tls /certs/tls.crt /certs/tls.key
      reverse_proxy 127.0.0.1:3000
    }