apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: grafana-postgres
  namespace: monitoring
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:15.5
  primaryUpdateStrategy: unsupervised
  storage:
    size: 5Gi
    storageClass: ceph-rbd-hdd-r2
  bootstrap:
    initdb:
      database: grafana
      owner: grafana
      secret:
        name: grafana-postgres-credentials