apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secrets.enc.yaml
  - pvc.yaml
  - helmrepository.yaml
  - database.yaml
  - helmrelease.yaml
  - certificate.yaml
  - caddymap.yaml
  - replicationsource.yaml