apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:j0wV+2c=,iv:49dDW+SOk/Waru/5vBh3AU6wy7W4Cd9SBsqvSamsphA=,tag:JgGJVVzEh52ZTlOFdzJJNw==,type:str]
    admin-password: ENC[AES256_GCM,data:pqan+JrJLW9f,iv:wCrJEmgb/Dw10d+nR2IfHsZ8B9y5cTlLzUmZ4VWLl0w=,tag:lRvquouSRGH0kocNMG97SA==,type:str]
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRZnErcW1LeHpoc0tNclJX
            WVJBTUpvZ295MnNSRXlqM1NzWXRsLzZKcTFJCnpveWRMaW9VaVdvR2VHL1lIclRX
            WDFRZEZUOW95Z3pDVHh1b1dXcERSVVkKLS0tIElqaWJneXlIL3p3Tm1nbXFPR2FG
            WTZaRy93TVJEN1F5MVlKUEloV2ZSblkKO0R+iX1o9GHj5QNY14S6lFX2piJ78LWZ
            nR8p7zbvrvoaPsKubC0wtPN18gw0QTliBdTOzesAQXmsHpqvfS2GnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-12T11:23:31Z"
    mac: ENC[AES256_GCM,data:AmBUzsVsOnidlTV3cHmK3RjJDU1HUOpB0sL7878EGZdYLJvyHekDWW8tGyBs8yNopFywBOnyPK6Oot6fp35Mm/MI++7aki6hx36tRXGgAGkFEh5hhgVS3H/y6LSKcuKbyFIg7woNNO5aQG3FsAsAQuv6SPqT4eNnlaD2Y4DE8Qs=,iv:uAXJEe16ESerfERTIt6rkOf0YW0mqNckGrclbGDGI5c=,tag:VMUG7hl9eH1aXOMQhNM0Eg==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: grafana-netbird-secrets
    namespace: monitoring
type: Opaque
stringData:
    NB_SETUP_KEY: ENC[AES256_GCM,data:ArKIKkeIR2deqfZUd86haNJ9BiXO4j1GRHWkTdeqxgSIRH5W,iv:8wqVlA0Cwr1wHtZaXZByn+nLMqS5F+3IMf3kAOZv6xc=,tag:ZMbcukeYm++EWm7Dzdzn1Q==,type:str]
    NB_MANAGEMENT_URL: ENC[AES256_GCM,data:qNL430zPdMyfVOELaEUqA3BDcA==,iv:iwSi800xKMHjlZZFu1LCOkgMCul+o8ZWD5q+PKPdM+I=,tag:nRiwvmbuYgvrVOuXGPLwLg==,type:str]
    NB_EXTRA_DNS_LABELS: ENC[AES256_GCM,data:TvI3fLuYB8vHsZAKgR+4wg==,iv:T9wOmGkWFWWPQ10gpln+Yu95vDZR7vrp3ZbSkRSKRmI=,tag:gNDedrF2r+ZD1pKUvV/2Bg==,type:str]
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRZnErcW1LeHpoc0tNclJX
            WVJBTUpvZ295MnNSRXlqM1NzWXRsLzZKcTFJCnpveWRMaW9VaVdvR2VHL1lIclRX
            WDFRZEZUOW95Z3pDVHh1b1dXcERSVVkKLS0tIElqaWJneXlIL3p3Tm1nbXFPR2FG
            WTZaRy93TVJEN1F5MVlKUEloV2ZSblkKO0R+iX1o9GHj5QNY14S6lFX2piJ78LWZ
            nR8p7zbvrvoaPsKubC0wtPN18gw0QTliBdTOzesAQXmsHpqvfS2GnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-12T11:23:31Z"
    mac: ENC[AES256_GCM,data:AmBUzsVsOnidlTV3cHmK3RjJDU1HUOpB0sL7878EGZdYLJvyHekDWW8tGyBs8yNopFywBOnyPK6Oot6fp35Mm/MI++7aki6hx36tRXGgAGkFEh5hhgVS3H/y6LSKcuKbyFIg7woNNO5aQG3FsAsAQuv6SPqT4eNnlaD2Y4DE8Qs=,iv:uAXJEe16ESerfERTIt6rkOf0YW0mqNckGrclbGDGI5c=,tag:VMUG7hl9eH1aXOMQhNM0Eg==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: grafana-config-volsync-secret
    namespace: monitoring
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:jem0/FU/UcYO1g8tuHYdhdmIPjvUxnePPmscf/MILB17vc1FAJOws9aUzVbXmVaPi2vzDa0ojlCXetlsXA==,iv:iro8vEVcM0DqJpa16vOpJsm4j1JbvnIswFUmUZQuKw0=,tag:RxZAmA4g0hmysMOK6Pz67w==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:ppyh3aR4ZaL7kQy0ErD1M11dMhECn2xMuLJILir9cTR1k8e/2w9jyrmuNGVPokoWdg4=,iv:RD4xneXdbLbEMhuzEX1lewTuimHepDj3G9H15fCrmnI=,tag:ClIDRX358hxETXaWvdxgjQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:F50Ab7Q75jDac+0IXkZhqg==,iv:KwYHmCAutTSjWo35OvWbhD5M42k4D73/ubh1bensy8Y=,tag:vicOo/MHeXBRdd9z2+gerQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:NgsWWIb+MVWFq8nSLlAT51oClF9+/dQMY8m4OtQ6Dbs9gMOOHXcsHtNhM6pRip00u7E=,iv:4Xj6heoOm2uG8bB286mM/tkigNO/6K0VT5U0EaVSgZ8=,tag:qJ8hBwMG3YqQX2C9efHnhQ==,type:str]
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRZnErcW1LeHpoc0tNclJX
            WVJBTUpvZ295MnNSRXlqM1NzWXRsLzZKcTFJCnpveWRMaW9VaVdvR2VHL1lIclRX
            WDFRZEZUOW95Z3pDVHh1b1dXcERSVVkKLS0tIElqaWJneXlIL3p3Tm1nbXFPR2FG
            WTZaRy93TVJEN1F5MVlKUEloV2ZSblkKO0R+iX1o9GHj5QNY14S6lFX2piJ78LWZ
            nR8p7zbvrvoaPsKubC0wtPN18gw0QTliBdTOzesAQXmsHpqvfS2GnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-12T11:23:31Z"
    mac: ENC[AES256_GCM,data:AmBUzsVsOnidlTV3cHmK3RjJDU1HUOpB0sL7878EGZdYLJvyHekDWW8tGyBs8yNopFywBOnyPK6Oot6fp35Mm/MI++7aki6hx36tRXGgAGkFEh5hhgVS3H/y6LSKcuKbyFIg7woNNO5aQG3FsAsAQuv6SPqT4eNnlaD2Y4DE8Qs=,iv:uAXJEe16ESerfERTIt6rkOf0YW0mqNckGrclbGDGI5c=,tag:VMUG7hl9eH1aXOMQhNM0Eg==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    version: 3.12.2
