apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-cluster-issuer-secrets
    namespace: flux-system
type: Opaque
stringData:
    ACME_EMAIL: ENC[AES256_GCM,data:Ff0RQS0Wh8/Z6ue48Q==,iv:ygohRPHUDwSz2EVT8+POzjTqbmlyjZKPWYnTowT+ALU=,tag:jgpygJUyxoVCN7KZcaAURA==,type:str]
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzRkNmL0ViQnkyZlM2dWNI
            RTZhM1ZYb0FvT09jdC8yVFZMTnhYTi96bG1zCnY2MWt2bUtVOFNmaDVCbzBIeFFZ
            MXo3Q1pyNHVvVDRBK21TbFdRUGI3UkUKLS0tIFJpWkx0S0VzVXAvSGFQNGJaeGIz
            a2lCN0RHL1JJa2MwdHZucTVVQlZrY2sKhDKCcRfliGSYwvXuswzPhtx3Hxfq4z6H
            w5sfqRRGZsEfHj5ofX+ahtcIyTxrlZ0U4WbcztTAc1ptjeP54U/3Cg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-21T09:19:10Z"
    mac: ENC[AES256_GCM,data:C4NKypXWyuxPkx3v3h/yit2L++FMN8N7AD9K+120OojoUoguac/DWTFR7gXw2C0rpHX1GBPGMTljak249OnFJhcgc9+iU6Ycui0X4trDmDk5Pi52K8UFisUgQi4GcT7fKv/2jRomL9fttKbAx1xpPNQA7InqwHqycJmig3aanzg=,iv:6nwNaeVGc0AZZGneLrecYCwfCLAFRZ6seH8o3aqcNIM=,tag:6q3pFCjsyzTPgRbN36H9nA==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: librespeed-secrets
    namespace: flux-system
type: Opaque
stringData:
    DNS_ZONE_NAME: ENC[AES256_GCM,data:G3APcXQDvhzXX1s=,iv:9ZmOlpfz8NyEAcoxSD01P5/Pck/mdc2rTqaJYqzCdy0=,tag:GslwD75GujFnQqgva9Sq0w==,type:str]
    DNS_NAME: ENC[AES256_GCM,data:4KRSx0r7Szk1bTQtQX5pO2xwQlUANg==,iv:JgrJBv7o0W8mnldvaAqVi93atneBjTRV7XybGni1RyE=,tag:O8RyAYjuc6ZX3SdAIfvnEA==,type:str]
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzRkNmL0ViQnkyZlM2dWNI
            RTZhM1ZYb0FvT09jdC8yVFZMTnhYTi96bG1zCnY2MWt2bUtVOFNmaDVCbzBIeFFZ
            MXo3Q1pyNHVvVDRBK21TbFdRUGI3UkUKLS0tIFJpWkx0S0VzVXAvSGFQNGJaeGIz
            a2lCN0RHL1JJa2MwdHZucTVVQlZrY2sKhDKCcRfliGSYwvXuswzPhtx3Hxfq4z6H
            w5sfqRRGZsEfHj5ofX+ahtcIyTxrlZ0U4WbcztTAc1ptjeP54U/3Cg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-21T09:19:10Z"
    mac: ENC[AES256_GCM,data:C4NKypXWyuxPkx3v3h/yit2L++FMN8N7AD9K+120OojoUoguac/DWTFR7gXw2C0rpHX1GBPGMTljak249OnFJhcgc9+iU6Ycui0X4trDmDk5Pi52K8UFisUgQi4GcT7fKv/2jRomL9fttKbAx1xpPNQA7InqwHqycJmig3aanzg=,iv:6nwNaeVGc0AZZGneLrecYCwfCLAFRZ6seH8o3aqcNIM=,tag:6q3pFCjsyzTPgRbN36H9nA==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    version: 3.12.2
