apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-cluster-issuer-secrets
    namespace: flux-system
type: Opaque
stringData:
    ACME_EMAIL: ENC[AES256_GCM,data:Ff0RQS0Wh8/Z6ue48Q==,iv:ygohRPHUDwSz2EVT8+POzjTqbmlyjZKPWYnTowT+ALU=,tag:jgpygJUyxoVCN7KZcaAURA==,type:str]
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzRkNmL0ViQnkyZlM2dWNI
            RTZhM1ZYb0FvT09jdC8yVFZMTnhYTi96bG1zCnY2MWt2bUtVOFNmaDVCbzBIeFFZ
            MXo3Q1pyNHVvVDRBK21TbFdRUGI3UkUKLS0tIFJpWkx0S0VzVXAvSGFQNGJaeGIz
            a2lCN0RHL1JJa2MwdHZucTVVQlZrY2sKhDKCcRfliGSYwvXuswzPhtx3Hxfq4z6H
            w5sfqRRGZsEfHj5ofX+ahtcIyTxrlZ0U4WbcztTAc1ptjeP54U/3Cg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-20T11:10:59Z"
    mac: ENC[AES256_GCM,data:1WTdigoZyjYjhBjMy/SEhOrmk/xFB5gy4J6cUJ/IQli10tg0jhc4VaXSdYDnBBDneZIGiS7vAfFJ8QbJcokxyVzyh56SyIbdrBo9iLVY5TqVy/5MbIPft0fTNwoxExjBVRwKiBZJVsedRnH6iF6hIS7DqJ44I0yoQfH2NkljPdo=,iv:YkHOPSSd8jv8b79KCwoxf9OaqBuoT4CNCFPHZruFY/o=,tag:jYfiThh8OvF/0XIDc09aUw==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    version: 3.12.2
