apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-cluster-issuer-secrets
    namespace: flux-system
type: Opaque
stringData:
    ACME_EMAIL: ENC[AES256_GCM,data:Ff0RQS0Wh8/Z6ue48Q==,iv:ygohRPHUDwSz2EVT8+POzjTqbmlyjZKPWYnTowT+ALU=,tag:jgpygJUyxoVCN7KZcaAURA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzRkNmL0ViQnkyZlM2dWNI
            RTZhM1ZYb0FvT09jdC8yVFZMTnhYTi96bG1zCnY2MWt2bUtVOFNmaDVCbzBIeFFZ
            MXo3Q1pyNHVvVDRBK21TbFdRUGI3UkUKLS0tIFJpWkx0S0VzVXAvSGFQNGJaeGIz
            a2lCN0RHL1JJa2MwdHZucTVVQlZrY2sKhDKCcRfliGSYwvXuswzPhtx3Hxfq4z6H
            w5sfqRRGZsEfHj5ofX+ahtcIyTxrlZ0U4WbcztTAc1ptjeP54U/3Cg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    lastmodified: "2026-09-05T12:09:02Z"
    mac: ENC[AES256_GCM,data:0bobJuyHdTxTNfcesPhjrZEmepJoo+serer9rb98Y8/VcT5/i7Y9tAyinhen5Ver/1/DwO/NeuZy1r+6NKt8BubBD+mDXRTBDwnvtigP/kgzqLSYfqXhRg2wvbMvnfRKBHNRjRaXq5MMK+kFKJmYsYmwwO+YXzKsp1RUTDWFweY=,iv:BsOfAwsLCvtNBlJJASsMaG/TmgJ9VTl42oXWX3VsYTQ=,tag:bP5I8MxLE3mmfysUs7dV/A==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: flux-netbird-secrets
    namespace: flux-system
type: Opaque
stringData:
    DNS_ZONE_NAME: ENC[AES256_GCM,data:G3APcXQDvhzXX1s=,iv:9ZmOlpfz8NyEAcoxSD01P5/Pck/mdc2rTqaJYqzCdy0=,tag:GslwD75GujFnQqgva9Sq0w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzRkNmL0ViQnkyZlM2dWNI
            RTZhM1ZYb0FvT09jdC8yVFZMTnhYTi96bG1zCnY2MWt2bUtVOFNmaDVCbzBIeFFZ
            MXo3Q1pyNHVvVDRBK21TbFdRUGI3UkUKLS0tIFJpWkx0S0VzVXAvSGFQNGJaeGIz
            a2lCN0RHL1JJa2MwdHZucTVVQlZrY2sKhDKCcRfliGSYwvXuswzPhtx3Hxfq4z6H
            w5sfqRRGZsEfHj5ofX+ahtcIyTxrlZ0U4WbcztTAc1ptjeP54U/3Cg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    lastmodified: "2026-09-05T12:09:02Z"
    mac: ENC[AES256_GCM,data:0bobJuyHdTxTNfcesPhjrZEmepJoo+serer9rb98Y8/VcT5/i7Y9tAyinhen5Ver/1/DwO/NeuZy1r+6NKt8BubBD+mDXRTBDwnvtigP/kgzqLSYfqXhRg2wvbMvnfRKBHNRjRaXq5MMK+kFKJmYsYmwwO+YXzKsp1RUTDWFweY=,iv:BsOfAwsLCvtNBlJJASsMaG/TmgJ9VTl42oXWX3VsYTQ=,tag:bP5I8MxLE3mmfysUs7dV/A==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: flux-librespeed-secrets
    namespace: flux-system
type: Opaque
stringData:
    DNS_NAME_LIBRESPEED: ENC[AES256_GCM,data:OsPUSdq5v4vbWYlXtNiht75bdGPdEufnwVUNiUrGwILM8yBuztFQlw==,iv:cPw6/zWAxivaSzmz8Q7p4oSj68m7HiGSRT2qO6CxfsM=,tag:BG62LxXf9D69wEEOS8Q6Yg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzRkNmL0ViQnkyZlM2dWNI
            RTZhM1ZYb0FvT09jdC8yVFZMTnhYTi96bG1zCnY2MWt2bUtVOFNmaDVCbzBIeFFZ
            MXo3Q1pyNHVvVDRBK21TbFdRUGI3UkUKLS0tIFJpWkx0S0VzVXAvSGFQNGJaeGIz
            a2lCN0RHL1JJa2MwdHZucTVVQlZrY2sKhDKCcRfliGSYwvXuswzPhtx3Hxfq4z6H
            w5sfqRRGZsEfHj5ofX+ahtcIyTxrlZ0U4WbcztTAc1ptjeP54U/3Cg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    lastmodified: "2026-09-05T12:09:02Z"
    mac: ENC[AES256_GCM,data:0bobJuyHdTxTNfcesPhjrZEmepJoo+serer9rb98Y8/VcT5/i7Y9tAyinhen5Ver/1/DwO/NeuZy1r+6NKt8BubBD+mDXRTBDwnvtigP/kgzqLSYfqXhRg2wvbMvnfRKBHNRjRaXq5MMK+kFKJmYsYmwwO+YXzKsp1RUTDWFweY=,iv:BsOfAwsLCvtNBlJJASsMaG/TmgJ9VTl42oXWX3VsYTQ=,tag:bP5I8MxLE3mmfysUs7dV/A==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: flux-podcast-secrets
    namespace: flux-system
type: Opaque
stringData:
    DNS_NAME_MINUSPOD: ENC[AES256_GCM,data:9EYI0+JeiwifmCn7ouM5afpNw7z/9LKFeuDpkbZ2bsLGl/IPfyA=,iv:XzURl6nx6uAlAfDECZLe3uzGBcVuVr7Ff8eEGD/zsB0=,tag:0Eb0axdHXl+Xr1BWJzZR7g==,type:str]
    DNS_NAME_PINEPODS: ENC[AES256_GCM,data:8hvwx3PyqZ8EpYTSz1o6CoVtMvbVB9rumZX3pC3RlR+8mITeTPk=,iv:hcP+reB/m0Wi1qCXQEd3CntKTR79uZ0Bg0G4kesq/ls=,tag:ZBP4VJHjJLz1KNQBeBZlUw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzRkNmL0ViQnkyZlM2dWNI
            RTZhM1ZYb0FvT09jdC8yVFZMTnhYTi96bG1zCnY2MWt2bUtVOFNmaDVCbzBIeFFZ
            MXo3Q1pyNHVvVDRBK21TbFdRUGI3UkUKLS0tIFJpWkx0S0VzVXAvSGFQNGJaeGIz
            a2lCN0RHL1JJa2MwdHZucTVVQlZrY2sKhDKCcRfliGSYwvXuswzPhtx3Hxfq4z6H
            w5sfqRRGZsEfHj5ofX+ahtcIyTxrlZ0U4WbcztTAc1ptjeP54U/3Cg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    lastmodified: "2026-09-05T12:09:02Z"
    mac: ENC[AES256_GCM,data:0bobJuyHdTxTNfcesPhjrZEmepJoo+serer9rb98Y8/VcT5/i7Y9tAyinhen5Ver/1/DwO/NeuZy1r+6NKt8BubBD+mDXRTBDwnvtigP/kgzqLSYfqXhRg2wvbMvnfRKBHNRjRaXq5MMK+kFKJmYsYmwwO+YXzKsp1RUTDWFweY=,iv:BsOfAwsLCvtNBlJJASsMaG/TmgJ9VTl42oXWX3VsYTQ=,tag:bP5I8MxLE3mmfysUs7dV/A==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: flux-vaultwarden-secrets
    namespace: flux-system
type: Opaque
stringData:
    DNS_NAME_VAULTWARDEN: ENC[AES256_GCM,data:dqbuZPqrC/lUOw1bLEuX0K2Qm2UOFRUZOQ==,iv:9C6uEJBmq2wNyY1SvUAP/Mkibz0ApZfEnizpFgbybnw=,tag:ytIU4fLXhiHIxlvtjfvOOQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzRkNmL0ViQnkyZlM2dWNI
            RTZhM1ZYb0FvT09jdC8yVFZMTnhYTi96bG1zCnY2MWt2bUtVOFNmaDVCbzBIeFFZ
            MXo3Q1pyNHVvVDRBK21TbFdRUGI3UkUKLS0tIFJpWkx0S0VzVXAvSGFQNGJaeGIz
            a2lCN0RHL1JJa2MwdHZucTVVQlZrY2sKhDKCcRfliGSYwvXuswzPhtx3Hxfq4z6H
            w5sfqRRGZsEfHj5ofX+ahtcIyTxrlZ0U4WbcztTAc1ptjeP54U/3Cg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    lastmodified: "2026-09-05T12:09:02Z"
    mac: ENC[AES256_GCM,data:0bobJuyHdTxTNfcesPhjrZEmepJoo+serer9rb98Y8/VcT5/i7Y9tAyinhen5Ver/1/DwO/NeuZy1r+6NKt8BubBD+mDXRTBDwnvtigP/kgzqLSYfqXhRg2wvbMvnfRKBHNRjRaXq5MMK+kFKJmYsYmwwO+YXzKsp1RUTDWFweY=,iv:BsOfAwsLCvtNBlJJASsMaG/TmgJ9VTl42oXWX3VsYTQ=,tag:bP5I8MxLE3mmfysUs7dV/A==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: flux-iperf3-secrets
    namespace: flux-system
type: Opaque
stringData:
    DNS_NAME_IPERF3_SERVER: ENC[AES256_GCM,data:xHXTRbR2kKBizxAlMX+aSBBHnAxHEVUPHEMBKl1RHF9ORciUEdw2qurE8A==,iv:I3IGx7BQtIZhE2pF/yXdKBFuiH6VjAn+t0bmWCY2KmQ=,tag:OxNRoMV2STcyT2f+HauFMQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzRkNmL0ViQnkyZlM2dWNI
            RTZhM1ZYb0FvT09jdC8yVFZMTnhYTi96bG1zCnY2MWt2bUtVOFNmaDVCbzBIeFFZ
            MXo3Q1pyNHVvVDRBK21TbFdRUGI3UkUKLS0tIFJpWkx0S0VzVXAvSGFQNGJaeGIz
            a2lCN0RHL1JJa2MwdHZucTVVQlZrY2sKhDKCcRfliGSYwvXuswzPhtx3Hxfq4z6H
            w5sfqRRGZsEfHj5ofX+ahtcIyTxrlZ0U4WbcztTAc1ptjeP54U/3Cg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    lastmodified: "2026-09-05T12:09:02Z"
    mac: ENC[AES256_GCM,data:0bobJuyHdTxTNfcesPhjrZEmepJoo+serer9rb98Y8/VcT5/i7Y9tAyinhen5Ver/1/DwO/NeuZy1r+6NKt8BubBD+mDXRTBDwnvtigP/kgzqLSYfqXhRg2wvbMvnfRKBHNRjRaXq5MMK+kFKJmYsYmwwO+YXzKsp1RUTDWFweY=,iv:BsOfAwsLCvtNBlJJASsMaG/TmgJ9VTl42oXWX3VsYTQ=,tag:bP5I8MxLE3mmfysUs7dV/A==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: flux-immich-secrets
    namespace: flux-system
type: Opaque
stringData:
    DNS_NAME_IMMICH: ENC[AES256_GCM,data:QAsvAIJ0oIiWE9ppY3E+xl3MQZgUTInuIFxUg9h/EYrbYKlQ,iv:1AAqy+Wy1JlJdZXqKEqyJU7Pe5IMnIbq/cV3ZYlkRpg=,tag:ZUfMY0J3CIsW7mCZKUTFzA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzRkNmL0ViQnkyZlM2dWNI
            RTZhM1ZYb0FvT09jdC8yVFZMTnhYTi96bG1zCnY2MWt2bUtVOFNmaDVCbzBIeFFZ
            MXo3Q1pyNHVvVDRBK21TbFdRUGI3UkUKLS0tIFJpWkx0S0VzVXAvSGFQNGJaeGIz
            a2lCN0RHL1JJa2MwdHZucTVVQlZrY2sKhDKCcRfliGSYwvXuswzPhtx3Hxfq4z6H
            w5sfqRRGZsEfHj5ofX+ahtcIyTxrlZ0U4WbcztTAc1ptjeP54U/3Cg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    lastmodified: "2026-09-05T12:09:02Z"
    mac: ENC[AES256_GCM,data:0bobJuyHdTxTNfcesPhjrZEmepJoo+serer9rb98Y8/VcT5/i7Y9tAyinhen5Ver/1/DwO/NeuZy1r+6NKt8BubBD+mDXRTBDwnvtigP/kgzqLSYfqXhRg2wvbMvnfRKBHNRjRaXq5MMK+kFKJmYsYmwwO+YXzKsp1RUTDWFweY=,iv:BsOfAwsLCvtNBlJJASsMaG/TmgJ9VTl42oXWX3VsYTQ=,tag:bP5I8MxLE3mmfysUs7dV/A==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: flux-monitoring-secrets
    namespace: flux-system
type: Opaque
stringData:
    DNS_NAME_GRAFANA: ENC[AES256_GCM,data:EhqdIZDvqAebAOJG8YT+KDotGEM4OQ7W8QaNUXyhdEqJ6UrLMQ==,iv:TBOz18/o89oOnEfQOyjbnpxPSX1mlUS4VL9sESTXlOc=,tag:tUj3fWPobeQVkwo00DEYig==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzRkNmL0ViQnkyZlM2dWNI
            RTZhM1ZYb0FvT09jdC8yVFZMTnhYTi96bG1zCnY2MWt2bUtVOFNmaDVCbzBIeFFZ
            MXo3Q1pyNHVvVDRBK21TbFdRUGI3UkUKLS0tIFJpWkx0S0VzVXAvSGFQNGJaeGIz
            a2lCN0RHL1JJa2MwdHZucTVVQlZrY2sKhDKCcRfliGSYwvXuswzPhtx3Hxfq4z6H
            w5sfqRRGZsEfHj5ofX+ahtcIyTxrlZ0U4WbcztTAc1ptjeP54U/3Cg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    lastmodified: "2026-09-05T12:09:02Z"
    mac: ENC[AES256_GCM,data:0bobJuyHdTxTNfcesPhjrZEmepJoo+serer9rb98Y8/VcT5/i7Y9tAyinhen5Ver/1/DwO/NeuZy1r+6NKt8BubBD+mDXRTBDwnvtigP/kgzqLSYfqXhRg2wvbMvnfRKBHNRjRaXq5MMK+kFKJmYsYmwwO+YXzKsp1RUTDWFweY=,iv:BsOfAwsLCvtNBlJJASsMaG/TmgJ9VTl42oXWX3VsYTQ=,tag:bP5I8MxLE3mmfysUs7dV/A==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: flux-syncthing-secrets
    namespace: flux-system
type: Opaque
stringData:
    DNS_NAME_SYNCTHING: ENC[AES256_GCM,data:1xyfezOl05ToCrb2C6JnMIogK1tjDcAoQ0TizjnowRccRarXB+nQ,iv:Y7lgVvjAKct1PkHk6Alqe0momfYUPbwxuNHOvilRJKQ=,tag:xcfv7Z1kC7+epmsJ9f0pqw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzRkNmL0ViQnkyZlM2dWNI
            RTZhM1ZYb0FvT09jdC8yVFZMTnhYTi96bG1zCnY2MWt2bUtVOFNmaDVCbzBIeFFZ
            MXo3Q1pyNHVvVDRBK21TbFdRUGI3UkUKLS0tIFJpWkx0S0VzVXAvSGFQNGJaeGIz
            a2lCN0RHL1JJa2MwdHZucTVVQlZrY2sKhDKCcRfliGSYwvXuswzPhtx3Hxfq4z6H
            w5sfqRRGZsEfHj5ofX+ahtcIyTxrlZ0U4WbcztTAc1ptjeP54U/3Cg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    lastmodified: "2026-09-05T12:09:02Z"
    mac: ENC[AES256_GCM,data:0bobJuyHdTxTNfcesPhjrZEmepJoo+serer9rb98Y8/VcT5/i7Y9tAyinhen5Ver/1/DwO/NeuZy1r+6NKt8BubBD+mDXRTBDwnvtigP/kgzqLSYfqXhRg2wvbMvnfRKBHNRjRaXq5MMK+kFKJmYsYmwwO+YXzKsp1RUTDWFweY=,iv:BsOfAwsLCvtNBlJJASsMaG/TmgJ9VTl42oXWX3VsYTQ=,tag:bP5I8MxLE3mmfysUs7dV/A==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: flux-streaming-secrets
    namespace: flux-system
type: Opaque
stringData:
    DNS_NAME_JELLYFIN: ENC[AES256_GCM,data:B1b6DvEYxGoL2CwNjIVEpePJoavAeLLmBlPXqDW2olagM2pJrUk=,iv:G97FkCH9t/am1JbSfEdQLFirTBMOjCkJXa0D24BnCQ8=,tag:HphNO4imD50YwzaANiBTdQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzRkNmL0ViQnkyZlM2dWNI
            RTZhM1ZYb0FvT09jdC8yVFZMTnhYTi96bG1zCnY2MWt2bUtVOFNmaDVCbzBIeFFZ
            MXo3Q1pyNHVvVDRBK21TbFdRUGI3UkUKLS0tIFJpWkx0S0VzVXAvSGFQNGJaeGIz
            a2lCN0RHL1JJa2MwdHZucTVVQlZrY2sKhDKCcRfliGSYwvXuswzPhtx3Hxfq4z6H
            w5sfqRRGZsEfHj5ofX+ahtcIyTxrlZ0U4WbcztTAc1ptjeP54U/3Cg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    lastmodified: "2026-09-05T12:09:02Z"
    mac: ENC[AES256_GCM,data:0bobJuyHdTxTNfcesPhjrZEmepJoo+serer9rb98Y8/VcT5/i7Y9tAyinhen5Ver/1/DwO/NeuZy1r+6NKt8BubBD+mDXRTBDwnvtigP/kgzqLSYfqXhRg2wvbMvnfRKBHNRjRaXq5MMK+kFKJmYsYmwwO+YXzKsp1RUTDWFweY=,iv:BsOfAwsLCvtNBlJJASsMaG/TmgJ9VTl42oXWX3VsYTQ=,tag:bP5I8MxLE3mmfysUs7dV/A==,type:str]
    version: 3.13.3
