apiVersion: v1
kind: Secret
metadata:
    name: pinepods-secrets
    namespace: podcast
stringData:
    postgres-password: ENC[AES256_GCM,data:xgJi685/R9smzDO0LPOWmL4utMVopvOU/9r3SOgzOGjnbXI9lJRdHcN5kqud38Qc8Tg=,iv:b18Ya23mNFVlt4JgGyMCFxPqv4a7v9+LOmhJVW1okdU=,tag:aHjHqwh2BZr/LmmUfZ+iZw==,type:str]
    admin-username: ENC[AES256_GCM,data:orl9eqUhmivsB4KzTg==,iv:jF5TZvWoJWsjpPTnwSDMR9JzM/1GLsAhLr0W4gTJv5g=,tag:HM7Z0O3RjSGPUqynahC92Q==,type:str]
    admin-password: ENC[AES256_GCM,data:AaHT07RQb/pzNmMLf1p3FT/kH+7k7ldTN/6poQcF2u8TeAff9y37ZH6Azf20dpJGRR4=,iv:epwakj5D2ddbT23vGKdEyqDYg3kfPzYfXszb16uEub4=,tag:NRinNkj7n9mGEm2Ous4tFw==,type:str]
    admin-fullname: ENC[AES256_GCM,data:9EJx5c+cuA==,iv:8dgeKN0kNdS6+ww0+yAeWzSXLZ+NX6CSNsgPhTsOj9Y=,tag:FkYyiBARP+fqDobkGfgvCQ==,type:str]
    admin-email: ENC[AES256_GCM,data:k2CSMpH5BRTziiOJqpCRkw==,iv:CvDNQVrhZdn1zj5VztMJbeBiSY3rFYO9OvAQJOZVC5A=,tag:j4hgOfO99tEt7SQZVdXL9g==,type:str]
    app-hostname: ENC[AES256_GCM,data:oeNBEauRCsjdGEld5PP4BnZPlC/B5h+FOZg3zHgdjRq45Dmnt6w29077NUc=,iv:Ip6R4irbRNBfNSE+qydhbL5BguQXht1S42MUxVE1v0Q=,tag:VthhjozuxMv372ELNkKKgw==,type:str]
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTm1PV0JIMTN2QUFUak9J
            L2lRZ3FZNVRBS3Bsa1hBVS9LTHVOZWZnU0c0CitUSVZHNW1vMFpHSWVQWmpWTTBR
            czBQTHVMMit2ZGNneHlST1pGdmNRTWMKLS0tIHhJOTFjMGJFN2ZOZTJTbEJuR0dX
            YUZMdDBGZU04KytQWS80WW9mWG9aWE0KKX0Jxje+j5U3dr/2rXSA5TgN62w512CK
            GHBIZVPBSb0sn0JdShwXZqjG4IOwgxrfAoe3J7XjJdR6Rn5Y+7cmqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-23T10:21:29Z"
    mac: ENC[AES256_GCM,data:iCZemtWf/pvA/IOd0TT/YOz93rOWUpkI6NIXqsrcq9LY59jRwgtgleqk0qXRv+ufSU0J6PzKS7o4+IfvS7D8SVsTxVWGJKx0KLhvglh7gNvoW83f9kW9zLHqpng7CWFzxpzNiyD2fpIwCTz8oVE8Y2sOP6TbsjNY0Nd0Gzuuhg8=,iv:8795SrTvwm6KkKmFRriTKY1PbEKbg5iUvXInRuSVXSE=,tag:RvvAHHRnb13XAifj0tvicA==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    version: 3.12.2
