apiVersion: v1
kind: Secret
metadata:
    name: pinepods-secrets
    namespace: podcast
stringData:
    postgres-password: ENC[AES256_GCM,data:xgJi685/R9smzDO0LPOWmL4utMVopvOU/9r3SOgzOGjnbXI9lJRdHcN5kqud38Qc8Tg=,iv:b18Ya23mNFVlt4JgGyMCFxPqv4a7v9+LOmhJVW1okdU=,tag:aHjHqwh2BZr/LmmUfZ+iZw==,type:str]
    admin-username: ENC[AES256_GCM,data:GRDUqKHGCA==,iv:AJRrDO2UXNzq6HeHg4jQexkiVDTa3m59fITeWg6VH0c=,tag:vFLiZxwAAMBWkefOTIIaTA==,type:str]
    admin-password: ENC[AES256_GCM,data:AaHT07RQb/pzNmMLf1p3FT/kH+7k7ldTN/6poQcF2u8TeAff9y37ZH6Azf20dpJGRR4=,iv:epwakj5D2ddbT23vGKdEyqDYg3kfPzYfXszb16uEub4=,tag:NRinNkj7n9mGEm2Ous4tFw==,type:str]
    admin-fullname: ENC[AES256_GCM,data:9EJx5c+cuA==,iv:8dgeKN0kNdS6+ww0+yAeWzSXLZ+NX6CSNsgPhTsOj9Y=,tag:FkYyiBARP+fqDobkGfgvCQ==,type:str]
    admin-email: ENC[AES256_GCM,data:k2CSMpH5BRTziiOJqpCRkw==,iv:CvDNQVrhZdn1zj5VztMJbeBiSY3rFYO9OvAQJOZVC5A=,tag:j4hgOfO99tEt7SQZVdXL9g==,type:str]
    app-hostname: ENC[AES256_GCM,data:u70Tuy1bKxi0ULkN6b2Ob5ut6jjgVGZNsJErvzfuZ5Zsnvw0Y13uvdclt5E+Pg==,iv:rCDMTDU6guKkM3RyhGKEKgilsuI+/Pr0FDIn06WZU8Y=,tag:LoQ/Tl0cWvPFC/RstR4HAQ==,type:str]
    NB_SETUP_KEY: ENC[AES256_GCM,data:LIsq5f/QWFOmmXlnkkalbVzJp+5vPk8tl48rxeujq5KpZ0/8,iv:M5XqydwiPjarIBegGpXcjTbAoGwmmmN3wPBOlEbMX3I=,tag:uygDWDoDY3syIjNHjoonQg==,type:str]
    NB_MANAGEMENT_URL: ENC[AES256_GCM,data:F6HAF1R3B8CgKmQ+edRQguc8MA==,iv:8VcJWKjm8r0BNs2gr5/zM+4mXBRLbqttXXlJZKcqSMQ=,tag:uyCETk9tEL7TTrnNlVd6bA==,type:str]
    NB_EXTRA_DNS_LABELS: ENC[AES256_GCM,data:LSN2Rp69pIFy0CrBHjF0O90v,iv:5EaOr4q1rM5K+gJ6JJuz0fkcR8R3driEUfHjyhehX8Y=,tag:N8xuSGats6fCWdgbNGgWYQ==,type:str]
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTm1PV0JIMTN2QUFUak9J
            L2lRZ3FZNVRBS3Bsa1hBVS9LTHVOZWZnU0c0CitUSVZHNW1vMFpHSWVQWmpWTTBR
            czBQTHVMMit2ZGNneHlST1pGdmNRTWMKLS0tIHhJOTFjMGJFN2ZOZTJTbEJuR0dX
            YUZMdDBGZU04KytQWS80WW9mWG9aWE0KKX0Jxje+j5U3dr/2rXSA5TgN62w512CK
            GHBIZVPBSb0sn0JdShwXZqjG4IOwgxrfAoe3J7XjJdR6Rn5Y+7cmqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-06T16:03:36Z"
    mac: ENC[AES256_GCM,data:8P/KiCVxnsLa+BMf7dOgBzRAKfwgDBxkNdyzVxxFDB06MXdgdh8EXBBQP8VkJ1imGVzHi3MCqSb1Le17YhkNgsqhpZKvEfl2T08XgJolw3Pb3zruTxbTgZ0SUJcOwfx6o1xA/W9m7kvndO+C8IcqIsRM/UMYX8cWuRITw9KCB3E=,iv:7HoQCGLyWEuKoCQvXdjzSLGLNmPWFjWLfJ87HwXVDcQ=,tag:b+AtcCLcqYNC1tWCja9uFA==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: volsync-pinepods-secrets
    namespace: podcast
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:rojEswG/cDovonZJYQnpduYKdXy71QwsI0PdfVcAiTeHV7CP9krdRp8DannMBAoKLGjr9i0Q+w==,iv:gqzIEcw8Ooi3Lh0a6xzgy2kklCqTwS5LmpuUyoVsMVM=,tag:iLZfgLgyFCPnhDYnOh6SOQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:tpAjD93ixqSk6CmKlTWfaIruPXLTvKgI8Oji431iZVXUc+o/W9aTk3ry3zRrBc//Q3g=,iv:AYgx7B4TdyNaHk2J6a/vmoUxL8NorPqUeObuvlrT4BM=,tag:Ns23woJv1JQAVf51nY+j6w==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:hTEN/21LEElZs8tJ/MRsQg==,iv:DFWEZf8CkLR+/tpu3wgTj4LrkYIx5Qx0alDvXxzbiYw=,tag:V8DuZvtIClOMo84TX14o9A==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:4In4k7Uf1Nd/1ibudCGo19oMr1SkygLDOuFHSJC2QyKvxQCvbAVZP1jrsQqZaCb11yI=,iv:Wkl2zTMvFog4jtFxOc4dRah4T3UVcnheQVSMLeTEfGA=,tag:6pT/zhLShzZJl+mNKWxjmQ==,type:str]
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTm1PV0JIMTN2QUFUak9J
            L2lRZ3FZNVRBS3Bsa1hBVS9LTHVOZWZnU0c0CitUSVZHNW1vMFpHSWVQWmpWTTBR
            czBQTHVMMit2ZGNneHlST1pGdmNRTWMKLS0tIHhJOTFjMGJFN2ZOZTJTbEJuR0dX
            YUZMdDBGZU04KytQWS80WW9mWG9aWE0KKX0Jxje+j5U3dr/2rXSA5TgN62w512CK
            GHBIZVPBSb0sn0JdShwXZqjG4IOwgxrfAoe3J7XjJdR6Rn5Y+7cmqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-06T16:03:36Z"
    mac: ENC[AES256_GCM,data:8P/KiCVxnsLa+BMf7dOgBzRAKfwgDBxkNdyzVxxFDB06MXdgdh8EXBBQP8VkJ1imGVzHi3MCqSb1Le17YhkNgsqhpZKvEfl2T08XgJolw3Pb3zruTxbTgZ0SUJcOwfx6o1xA/W9m7kvndO+C8IcqIsRM/UMYX8cWuRITw9KCB3E=,iv:7HoQCGLyWEuKoCQvXdjzSLGLNmPWFjWLfJ87HwXVDcQ=,tag:b+AtcCLcqYNC1tWCja9uFA==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    version: 3.12.2
