apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-loopia-secrets
    namespace: cert-manager
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:VxTNVvtjpaiK+f7ujUqp9NY1,iv:qu1zuu4gdLU/I7v2b0bW118RTbbbEpriY4jWPM5kUpU=,tag:EwzJJRqOdCZvwn9y0hEdxQ==,type:str]
    password: ENC[AES256_GCM,data:V0r7tf9CSbUZagBBwW5LkkBDWHzdkuBQcgv8/p2TCMkzZBJMb1CcVfmpmY/DcQxmqCg=,iv:KgIVnFvqG7cGzr4fvULKik9PTVh+tJyk7Jal6gltMJc=,tag:XGtzeTVz6fZdMO/0M2W1XA==,type:str]
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJUFBRYnE3NEp2UEx0eDhj
            YkcxVzllVXErdTdDb0tkVk9XOFFUQU9VTkF3CkpuK3RwUzMwenRFMkRWakVpZ0tQ
            bE43bk1zQW9Hb29LSG5uMVhzU21wRVkKLS0tIDU5a2wyUDRwM1o3a1hBMm1HZXNs
            RVlPb3VkVURnaG43ZUxuc2NPeVNXNlEKtXagDI5kP/JComTrCWSKLgvpUNrSpUkh
            2RKyUC5XMa7qFDvzjwqm27NNAinq6bjpQWqO8OrVsGbKJFmeQQX/tg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-20T11:11:12Z"
    mac: ENC[AES256_GCM,data:6VM1hil7Py1YtHw7CqvLddsEET7s/7he31UwMt0j6TFCVsHdQ9zfwIWYdaUbMGND/PXOz4XhhCUhWeXbgqBMLUXd+twvJlr33e328NE9HcU6QIKZe3fqVJZL/6b5wyRXY06SUi9NmIEQ1NGo8nIn74U/og69cOrzUG1UhGUr0Gg=,iv:vKZiyRs25ewLGdfewXmY48sbK2Qg3mP5z2bTzHjWG5o=,tag:CtYsddSHYsagwM4GFN+dXA==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    version: 3.12.2
