apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-loopia-secrets
    namespace: cert-manager
type: Opaque
stringData:
    ACME_EMAIL: ENC[AES256_GCM,data:/4QSwl9jYpFkMhMKKQ==,iv:ZBH8NoObfXYXeXAX0Wo7+e9UDnCAPhL9VB+8peVWvWQ=,tag:UOToXlvj6FTwMeRvl8mIEQ==,type:str]
    username: ENC[AES256_GCM,data:VxTNVvtjpaiK+f7ujUqp9NY1,iv:qu1zuu4gdLU/I7v2b0bW118RTbbbEpriY4jWPM5kUpU=,tag:EwzJJRqOdCZvwn9y0hEdxQ==,type:str]
    password: ENC[AES256_GCM,data:V0r7tf9CSbUZagBBwW5LkkBDWHzdkuBQcgv8/p2TCMkzZBJMb1CcVfmpmY/DcQxmqCg=,iv:KgIVnFvqG7cGzr4fvULKik9PTVh+tJyk7Jal6gltMJc=,tag:XGtzeTVz6fZdMO/0M2W1XA==,type:str]
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJUFBRYnE3NEp2UEx0eDhj
            YkcxVzllVXErdTdDb0tkVk9XOFFUQU9VTkF3CkpuK3RwUzMwenRFMkRWakVpZ0tQ
            bE43bk1zQW9Hb29LSG5uMVhzU21wRVkKLS0tIDU5a2wyUDRwM1o3a1hBMm1HZXNs
            RVlPb3VkVURnaG43ZUxuc2NPeVNXNlEKtXagDI5kP/JComTrCWSKLgvpUNrSpUkh
            2RKyUC5XMa7qFDvzjwqm27NNAinq6bjpQWqO8OrVsGbKJFmeQQX/tg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-20T10:48:09Z"
    mac: ENC[AES256_GCM,data:NTMvLOdbIa3D87KhggTNO8Dp2lFrSXpXhfENKTudgcAVwQnmNhFxvORriCkneQEYIjj6Nraa5RT9eCzb+3bQl7vFfkEz3H0tOGyucln/0/2Pt2L4hxc2MU+1YsEhG91A+VZt+E7iceRNj0OHCwLy5QwtKj4xzAyBL4OaMdvGTiI=,iv:0T+kGBPA1GGBU0b/2B+1qSzc8qhRn9uIAGcS7cZ8k5g=,tag:/75roxslkyEXHbP3AU6Vig==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    version: 3.12.2
