# HDD - Replicated 2
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: hdd-object-r2
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: osd
    replicated:
      size: 2
      requireSafeReplicaSize: false
    deviceClass: hdd
  dataPool:
    failureDomain: osd
    replicated:
      size: 2
      requireSafeReplicaSize: false
    deviceClass: hdd
  preservePoolsOnDelete: true
  gateway:
    port: 80
    instances: 1
    priorityClassName: low-priority
    service:
      annotations:
        io.cilium/lb-ipam-ips: "192.168.201.102"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ceph-bucket-hdd-r2
provisioner: rook-ceph.ceph.rook.io/bucket
parameters:
  objectStoreName: hdd-object-r2
  objectStoreNamespace: rook-ceph
reclaimPolicy: Retain