---
# HDD - Replicated 2
apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: hdd-fs-r2
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: osd
    replicated:
      size: 2
      requireSafeReplicaSize: false
    deviceClass: hdd
  dataPools:
    - name: data
      failureDomain: osd
      replicated:
        size: 2
        requireSafeReplicaSize: false
      deviceClass: hdd
  preserveFilesystemOnDelete: true
  metadataServer:
    activeCount: 1
    activeStandby: false
    priorityClassName: low-priority
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ceph-fs-hdd-r2
provisioner: rook-ceph.cephfs.csi.ceph.com
parameters:
  clusterID: rook-ceph
  fsName: hdd-fs-r2
  pool: hdd-fs-r2-data
  csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
  csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
  csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
  csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
  csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
  csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
reclaimPolicy: Retain
allowVolumeExpansion: true
---
# # NVMe - Replicated 1
# apiVersion: ceph.rook.io/v1
# kind: CephFilesystem
# metadata:
#   name: nvme-fs-r1
#   namespace: rook-ceph
# spec:
#   metadataPool:
#     failureDomain: osd
#     replicated:
#       size: 1
#       requireSafeReplicaSize: false
#     deviceClass: nvme
#   dataPools:
#     - name: data
#       failureDomain: osd
#       replicated:
#         size: 1
#         requireSafeReplicaSize: false
#       deviceClass: nvme
#   preserveFilesystemOnDelete: true
#   metadataServer:
#     activeCount: 1
#     activeStandby: false
#     priorityClassName: low-priority
# ---
# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: ceph-fs-nvme-r1
# provisioner: rook-ceph.cephfs.csi.ceph.com
# parameters:
#   clusterID: rook-ceph
#   fsName: nvme-fs-r1
#   pool: nvme-fs-r1-data
#   csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
#   csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
#   csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
#   csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
#   csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
#   csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
# reclaimPolicy: Retain
# allowVolumeExpansion: true