apiVersion: v1
kind: Secret
metadata:
    name: desec-credentials
    namespace: external-dns
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:/axfc2bcVybfvXmUuC7jSwxK1rMAIZUvuyHo6Q==,iv:xIpQouT6q76yZ/XuJb39N4iaqrntljCx7orJjegVG54=,tag:DpM+cSONgWFuuS1a+A9T0w==,type:str]
    domain-filter: ENC[AES256_GCM,data:xdh2TjMwUh0bEuc=,iv:iPqBqrQQS4rJHtTwT2kL7q4LTG1QBgjYWdxnxS+ayoQ=,tag:nzRpz7NfqhoLViN6XIBavw==,type:str]
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5NkJ4aFh4MnZucWt5UWlq
            Q3Vkd1BWNVhVaXgxMjdUZnhSWWtqVk5zMWhnCm1QTkdvM0YwNjlmR3pkYlp4QVJL
            TEZoLzNtYUtOOVo3a1dnMm1aTjYzWW8KLS0tIFJHeDJvSUEzWTJpTEJKdmJ1Zy9L
            Tm1LdjNNa2VNVmgrQWZKZERFNEZycVEKg0QGB2LO4rVKIc3OzYuAJNxMLOkGEUJr
            PVQuE47KMDcFHAVvH+FBTXwrA1iryrHUVHaiubFUbvPTYLVHE/whlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-26T09:23:34Z"
    mac: ENC[AES256_GCM,data:udKeavFZu05gS16mJ4waL1kKmayk/N1uIJiDQMFutk0hXJcEY6tdwcWlsOFgdkJNDrkQfKdCf6aGbWknzJou7EZAmcfjQt3ChDQUnamSU5uG17wxqY3janyqYdN5tMv26orVQEVCSpVwA8K4RTqv4SZk1HaxtLnKMl7BdJTU7ow=,iv:o5w7HE603Fw/ab0xIBmCYh/nemcvIZPfCE3aJ1vGeko=,tag:Lf14y1fXWyKQZmC9P3GPBQ==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    version: 3.12.2
