apiVersion: v1
kind: Secret
metadata:
    name: desec-credentials
    namespace: external-dns
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:w6sGBq6nn8apv6KXCZ8Viq5hHdd04kZX/j8/uQ==,iv:gQ5LZ0pxZBsBy/TmVjrnTS5tWXa3UrdCm1tC22hWnWM=,tag:OdQLjbWlv4KIcYrUW3MaMQ==,type:str]
    domain-filter: ENC[AES256_GCM,data:xdh2TjMwUh0bEuc=,iv:iPqBqrQQS4rJHtTwT2kL7q4LTG1QBgjYWdxnxS+ayoQ=,tag:nzRpz7NfqhoLViN6XIBavw==,type:str]
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5NkJ4aFh4MnZucWt5UWlq
            Q3Vkd1BWNVhVaXgxMjdUZnhSWWtqVk5zMWhnCm1QTkdvM0YwNjlmR3pkYlp4QVJL
            TEZoLzNtYUtOOVo3a1dnMm1aTjYzWW8KLS0tIFJHeDJvSUEzWTJpTEJKdmJ1Zy9L
            Tm1LdjNNa2VNVmgrQWZKZERFNEZycVEKg0QGB2LO4rVKIc3OzYuAJNxMLOkGEUJr
            PVQuE47KMDcFHAVvH+FBTXwrA1iryrHUVHaiubFUbvPTYLVHE/whlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-25T11:51:13Z"
    mac: ENC[AES256_GCM,data:e6wEMquZAvLFuq+O3iAYYqnlUm6ubUOzDTk/UiGT6Q5yIOgE30r0s8dCCNn+3M6D0JviyCzg98UcPItm+71B/2jkljLKOY+BsnOes9Z9nLzsSrkwXuDjKkz405NcA+ti9ouce+fO0e2/VFb30jP57QB1ivoPPNtxTu/pVMEQLvI=,iv:37i/TAVIuCHF0f/s+fUBnCInYV7VRMjfsSGTMdzkphE=,tag:RGDWsBXzggHdwW0RVWmEig==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    version: 3.12.2
