---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: svtplay-dl-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: rook-ceph.cephfs.csi.ceph.com
    volumeHandle: svtplay-dl-pv
    nodeStageSecretRef:
      name: rook-csi-cephfs-node
      namespace: rook-ceph
    controllerExpandSecretRef:
      name: rook-csi-cephfs-provisioner
      namespace: rook-ceph
    volumeAttributes:
      clusterID: rook-ceph
      fsName: hdd-fs-r2
      staticVolume: "true"
      rootPath: /volumes/svtplay-dl
# -> ceph-tools -> mkdir -p /volumes/svtplay-dl