---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rook-ceph-admin-keyring-secret.enc.yaml
  - rook-ceph-mon-secret.enc.yaml
  - rook-ceph-mons-keyring-secret.enc.yaml
  - luks-secret.enc.yaml
  - luks-restore-job.yaml