apiVersion: v1
kind: Secret
metadata:
    name: ceph-luks-keys
    namespace: rook-ceph
stringData:
    keys.sh: ENC[AES256_GCM,data:FQWKpELmDZfCxa06MKouATGQHoVQ5KId9n3YP1jQMeAFLjyIoUvjXpHxlbpeO/gPC72FbfUlZf8J89FqrQfkx9EQnFZWB6pa/XYAmzXLxvnjl/l2Rk9qhpMII1ZVBVppbM4ziyOPrexQUd1seLgkOmgrEIu01JzX5ZRBwp2C0Zd92q5q5I6ZmF2DjkWe+c0xA8EJNwIJT1qMcP879Ww1UCcDY7XDMHokkmRjVb3VWGb8vx/4iAyM+fC5d2l1P9+hAy8Zk0yrwk7tzNYoxuWoMI7pIqQUoYoQKW4yGSHqa2uSB7HaKFt2RcIAsOnZJ4kuQFPxFLKkXcxZ2+Y2oy7taGgI0egozsWS/B72YIEnDEfgCPbcB/AFLktvQvDBBVlBZHimZDXpmjLGzoBCUtLIprWGSks1SjKrKLCN/qHMuUCXPLsxJ49Uxm1m1dWfAYet8EB6sKm1gDeF2/U9a5K/DJbLxJw7lQBczuCpxODqKbocyC5opXM56y9r5A0+oVR6NemcQhL2i/fHzqq859W17sHO07Y7RhGTANTCuQGRJxl9TGn9Bg0To4Hzj+LT6z69fkwNsJz3UXpAgTICu0pEMdXu6I+HJ5ZjMAahX6liakHaE6i9OZBOL6tp0k4OZp1+KbIsY50obRtBIFTr0P9cz3b32DmxfKEhKaT5w9m6IlfUJDzH1elvE0EV8NWO87I4uSEhoLa7Y4S7rNgpLhGjl+x4Rb3w/VN1ioeS8Kz1zEZkXIGjXjQNXvope8ZFDQ2xWWAiozPdZUbgrUQXe3dGSysfneMbR4+XeXltUxrbgNC16G9uEGLbgmBJh87BRKOz8AbomkMcAQrBhvjbP4tEyuyTBQDhcytmxS5wATHGylTho1oLRRrVBel+ImHmaTLl9kIBur72xJU2EI3PyccxYtdK24Mxiih5H7j6JjmqyiUPdD6/sedIDTXZWUznCJNyBFEtLDJIPWDggldcLHqboN27aBzk6g9pfsncyo4L,iv:A/C6/+M2ohzg1xNY+yb4SgILnIFRiTFGdgitJztuh5g=,tag:7Y0nRsOWghznYUFlh1k00w==,type:str]
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNNzlxVGJzNUQzbW9iUzlY
            RmZtcGJPS0d2VExnVmhUdTdlSnN1aThoTUIwCkZmVElwTGJNeXNVTlVQM0h5ampp
            SW5zWXpGNndVYVFXVThLQW9aYzVxNjAKLS0tIENxQzNrTGxacW05dWdZMXdpT0RD
            cmUybUxQamZBMjg5YW9zbHVnUVllWEkKfH9XJu0AYTYRqhxd8JNlUZpRcpIBbyQo
            cQHabWxQHkLQ9R7YpN/tk/dDKId5/W+pFM/dayRB1OgGLTXQ2jwp4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-21T09:18:00Z"
    mac: ENC[AES256_GCM,data:teHHB7NcJqbT2OHNQs/ujlyBNwuaprHm3tnUy/Ff3B4VNvXRmPJ3zZ4f42CvSElv7oh1r2PIc3xnS+I/CeKnHlnUHhD4EVBiNPI7nCMTite/l6+2vVNcAQGoV9k5/tHijDI189k+xHUyiMX/yZZMjU4Fu8Y7gNsQk70V1M7Cz2s=,iv:alXPr3DbkFgDj/DCdajiyXDFgZUEL4sGL2LV3r4V8Rs=,tag:HBhiXDOX0KZUmXdwvJtc3Q==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|keys.sh)$
    version: 3.12.2
