apiVersion: v1
kind: Secret
metadata:
    name: 3d9c8dd1-bc28-4f18-920b-47ba489dba0f
    namespace: rook-ceph
    labels:
        ceph.rook.io/backup-kms: k8s
type: Opaque
stringData:
    dm-crypt-key: ENC[AES256_GCM,data:0yXDfvoB1mxdYuHe2OPVyG6m1C16vMJRx/YHD/U1/1cxBLCGdjJJTKTAnst2gsNKmCVnbAJHOJkqpuEw5DhH1ccQxS/aBIVi/DzOjOOEGyQBxxRel5ub8dGcY+ETyFkMehdM1aA7F/vzIgsZVuVOftIFmpsdIk5Yk6ngKeTBamx6IXLe6ZfYkAYFm1rNJN1SUfYs4e6AkwTTURnhMXeQHwVfpRVLXSvbqOIuaw==,iv:w8cJChy8JX2DU9haCYL1MA+KKk9zHIvsyUrB90soOhM=,tag:6aD8ux/2CvoSQjqwPfmC1A==,type:str]
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6TW9VZHNkamVWbkJJSWlq
            M3Ntc1p2OTdFMWYyVk9Pb3FWMS9DYTlrc3owCnkwVWZ3ZHFBL1Z5VnlwQmF4OTBN
            VEZwS1FhTG1EYXovRmJLeU9Yc1ZqakEKLS0tIDNqdjQyQ3diTkFvQkRrbVFrZDBm
            cnBEeGJJVE8ySDBUV1pBZFZCb2lSYzgKFkk+JzwMYpM1bwNRiABIyh7QqxZKB6tC
            +tq/jUweWFvwDKPAvlwtCNbpzamDJhvU3erA0kkNAvxNuI2w+OgTNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-20T17:58:18Z"
    mac: ENC[AES256_GCM,data:7CS00tSUaKmn94EWv4vY04fhVHPd93/OS9fPkIz1QN6ZGxooRudMtiKdmoknpACsDBohoHbSkz5FNJJzFJM0ITrB45OzwuhYb+V+epm9spw/v+34TtQ4jwr6PnDb8XZQ0gTFpM0pBo3LbNtWit4DiB+HQiKEGns/8UtERZA2Qew=,iv:554eCLVcyxk0LU82nk8dTHu/RucN2upesyD9d2G+534=,tag:7chx3wHAbb/PuXmd9H5L3g==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|mon_host|mon_initial_members|ceph-secret|ceph-username|fsid|mon-secret|dm-crypt-key)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: 433c9cc7-fe17-4d06-be59-f2d88c10431a
    namespace: rook-ceph
    labels:
        ceph.rook.io/backup-kms: k8s
type: Opaque
stringData:
    dm-crypt-key: ENC[AES256_GCM,data:OAD+/HsVu/DJyqU7VZ/48i4FshjYXaC/vqNAOukE0ymeV5S0ldLXs0aGOh/NzvLWm+BjCMTxRnb8DW2QJplTQ05jmiV6D3NWHGcpBgF5KqXmTYLtbwcJiJrk4yPvRUrDDUPE1/zLSa1ZNXVJf6RNo+3d0y4RysuXkEiBP73Fk0vejkMfDym6UPvDXDidDbY/X977gfCaIlM2OW7fjJ36jbMFMvwqNzZcMuwOng==,iv:RorruHw8Mvl0Ph0VL3iDYvC5Pq72aPEFir1xFITQkGs=,tag:5WAVyt32LSO7llD+UB3fbA==,type:str]
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6TW9VZHNkamVWbkJJSWlq
            M3Ntc1p2OTdFMWYyVk9Pb3FWMS9DYTlrc3owCnkwVWZ3ZHFBL1Z5VnlwQmF4OTBN
            VEZwS1FhTG1EYXovRmJLeU9Yc1ZqakEKLS0tIDNqdjQyQ3diTkFvQkRrbVFrZDBm
            cnBEeGJJVE8ySDBUV1pBZFZCb2lSYzgKFkk+JzwMYpM1bwNRiABIyh7QqxZKB6tC
            +tq/jUweWFvwDKPAvlwtCNbpzamDJhvU3erA0kkNAvxNuI2w+OgTNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-20T17:58:18Z"
    mac: ENC[AES256_GCM,data:7CS00tSUaKmn94EWv4vY04fhVHPd93/OS9fPkIz1QN6ZGxooRudMtiKdmoknpACsDBohoHbSkz5FNJJzFJM0ITrB45OzwuhYb+V+epm9spw/v+34TtQ4jwr6PnDb8XZQ0gTFpM0pBo3LbNtWit4DiB+HQiKEGns/8UtERZA2Qew=,iv:554eCLVcyxk0LU82nk8dTHu/RucN2upesyD9d2G+534=,tag:7chx3wHAbb/PuXmd9H5L3g==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|mon_host|mon_initial_members|ceph-secret|ceph-username|fsid|mon-secret|dm-crypt-key)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: f03a9644-34b2-4095-986d-b1a015440d33
    namespace: rook-ceph
    labels:
        ceph.rook.io/backup-kms: k8s
type: Opaque
stringData:
    dm-crypt-key: ENC[AES256_GCM,data:2bNYMqVXYnUS7Mv3ToXSqyyO4Fal9xv/jyBMa5QRA6hb0hoEG9dBlMVwSaOB3N6aQfUwAVpYvves/O6YvGVe1wtNky1SGm+B5AgWineO5tzhdjnxYLkalUcVU1VvmqetWRz23os3+7bEjRjESAL+sxD1eGX622+Mi4u/7M4Z1wksdqwV/qQF4yguxRFrk4USlMjnaSE5bKeM+4ykKrZvQFy4izkycfc444+t3Q==,iv:YpZsIiIqtbLkIsAFfNMrN1e0tdcrcbQUkjATYwE8Xp8=,tag:Q3HlEvybpkgVKA8D8W9S5Q==,type:str]
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6TW9VZHNkamVWbkJJSWlq
            M3Ntc1p2OTdFMWYyVk9Pb3FWMS9DYTlrc3owCnkwVWZ3ZHFBL1Z5VnlwQmF4OTBN
            VEZwS1FhTG1EYXovRmJLeU9Yc1ZqakEKLS0tIDNqdjQyQ3diTkFvQkRrbVFrZDBm
            cnBEeGJJVE8ySDBUV1pBZFZCb2lSYzgKFkk+JzwMYpM1bwNRiABIyh7QqxZKB6tC
            +tq/jUweWFvwDKPAvlwtCNbpzamDJhvU3erA0kkNAvxNuI2w+OgTNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-20T17:58:18Z"
    mac: ENC[AES256_GCM,data:7CS00tSUaKmn94EWv4vY04fhVHPd93/OS9fPkIz1QN6ZGxooRudMtiKdmoknpACsDBohoHbSkz5FNJJzFJM0ITrB45OzwuhYb+V+epm9spw/v+34TtQ4jwr6PnDb8XZQ0gTFpM0pBo3LbNtWit4DiB+HQiKEGns/8UtERZA2Qew=,iv:554eCLVcyxk0LU82nk8dTHu/RucN2upesyD9d2G+534=,tag:7chx3wHAbb/PuXmd9H5L3g==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|mon_host|mon_initial_members|ceph-secret|ceph-username|fsid|mon-secret|dm-crypt-key)$
    version: 3.12.2
