apiVersion: v1
data:
    keyring: ENC[AES256_GCM,data:111UJ+rgodbGmliNPGnMf9WaH4d1p1pMQhFbxFZYSvdGuwMwi1RIar648Fo2HSUmJ/BYfskzTD8dGQ0BbuuYnqHXWLI/U5d8+sCCjGLFJEcV0GR55a+8wbx+nHDFB++YodMzKc2xEk8wokQTiPlmLIIwadth7l1y2NPmaITPimPqriecpSyUEQ+OUiVO/ua4trselCGb5GndVzpjJK4Pi9o8Ftw4kwHxZ7xAHDyiLxJXPh7RQg5d6tIDiHg6QlWhDn+FKNlrE9Kq33Hh447A0CpMSrNXWfShPjILvsytVGr8IE8ytsiQBOTfh5/vFxA5VkZb54UijhyHHlY/gX4YOIfmJNU5Er+bnCp3Ag6VtxdGGqYKMqDozZHMD0XQsbd9cJBVyX1zhXzbr4Usd7KTQXhsXtc=,iv:Z2/dpkG1lvVuNfrQGlrJXlwlRmGwTtYiDZ4gtvHYMsM=,tag:u+Vg73ufjELnU2tGnOaFHA==,type:str]
kind: Secret
metadata:
    name: rook-ceph-mons-keyring
    namespace: rook-ceph
type: kubernetes.io/rook
sops:
    age:
        - recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGWnF2bW1oZW5QbGl0NHps
            eHdubEQyMW9pcGZmZno3dGJJTllsN1o2WkdzCjVtZ0liVHliS2d6Y08vUnB6am5W
            T0NmYjJ6RnFuWnA4S0dmM2VyTGYrV3MKLS0tIEJiV2FoV0dXUWRmZnV6SG1pR2M0
            ODJHWkVvTWgrYnVqbU5EUEVydmlmTXcKGQvvjRBPTW6QKPbfBtbJcRC9PFRbRU6A
            CqMwvbZxD13Px6n/vMOCf30QHYndZRWQ5rWJenqnvG4UI32z9NfnCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-17T12:50:25Z"
    mac: ENC[AES256_GCM,data:+6O3THqlEhIW6sxHN6239OBG7HPNIvqLA+pm3+bGqDsqtk7fbDiTYtW4JChLbb6/eq0M5VDMjKPMrb3yJWy5KLHyw++ogyGt80La1vd/yl3QKsLyN+0Po2aAi6mdx/EI4+E1iqIgNJBs60npjAfIGHWOQDCwiYAKya9clwtikmc=,iv:V1ePKEVEqBB3hIsogYIJimaN1IhJD4Ow+7l3IXiZy/I=,tag:mnBjBT75xpnQ1C59saYZtg==,type:str]
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|mon_host|mon_initial_members|ceph-secret|ceph-username|fsid|mon-secret)$
    version: 3.12.2
