---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: svtplay-dl
  namespace: svtplay-dl
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  volumeName: svtplay-dl-pv
  storageClassName: ""