apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
  namespace: streaming
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd-hdd-r2
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media
  namespace: streaming
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd-hdd-r2
  resources:
    requests:
      storage: 1000Gi
