apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: jellyfin-config-backup
  namespace: streaming
spec:
  sourcePVC: jellyfin-config
  trigger:
    schedule: "15 5 * * *"
  restic:
    repository: volsync-jellyfin-config-secrets
    copyMethod: Snapshot
    volumeSnapshotClassName: csi-cephrbdplugin-snapclass
    cacheStorageClassName: ceph-rbd-hdd-r2  # ceph-rbd-nvme-r1
    cacheAccessModes:
      - ReadWriteOnce
    cacheCapacity: 5Gi
    storageClassName: ceph-rbd-hdd-r2
    pruneIntervalDays: 14
    moverSecurityContext:
      fsGroupChangePolicy: OnRootMismatch
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    retain:
      hourly: 24
      daily: 7
      weekly: 4
      monthly: 12

---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: jellyfin-media-backup
  namespace: streaming
spec:
  sourcePVC: jellyfin-media
  trigger:
    schedule: "30 5 * * *"
  restic:
    repository: volsync-jellyfin-media-secrets
    copyMethod: Snapshot
    volumeSnapshotClassName: csi-cephrbdplugin-snapclass
    cacheStorageClassName: ceph-rbd-hdd-r2  # ceph-rbd-nvme-r1
    cacheAccessModes:
      - ReadWriteOnce
    cacheCapacity: 5Gi
    storageClassName: ceph-rbd-hdd-r2
    pruneIntervalDays: 28
    moverSecurityContext:
      fsGroupChangePolicy: OnRootMismatch
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    retain:
      daily: 7
      weekly: 4
      monthly: 6