apiVersion: v1
kind: Secret
metadata:
    name: jellyfin-netbird-secrets
    namespace: streaming
type: Opaque
stringData:
    NB_SETUP_KEY: ENC[AES256_GCM,data:ySFVx6xL9FSbh5myx9hphDiAwl1vABSavXDeRrvksq6kvy3n,iv:9ukwm0y2UG+XWFtoigX4MmsgONWTqVVJhxHoRjsSjdc=,tag:dk/QDGGEW/CryoBOU2JzAQ==,type:str]
    NB_MANAGEMENT_URL: ENC[AES256_GCM,data:EtaiScYTzk5FDbzzd7amyK+9ag==,iv:zdruLpfytQpYkqSANEXF6gomcXh9nTvE3L9hmyhq0tM=,tag:DYNN9UjkBuUmeQmRQLDJbA==,type:str]
    NB_EXTRA_DNS_LABELS: ENC[AES256_GCM,data:qTOxu5Dm0B5WWrqjhwv4lLsY,iv:5yYAw9Ytd459W03bgsNNXsBvLL5G1cEFuT06JRsFrZ0=,tag:Pt7AmIv0ZymOi/noXkwtgg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RUtWaE9lZDk5VC9uYmMw
            a0ZoRkluMk9BZUlndGxQVlNQQkF2MTR4c3o4CmJxdFU4TDBYbnArU0xsZTNQSklu
            NFY2SWhuTms0ckY1NGI3d2Ezd0xtMkEKLS0tIHdCUWhWdzRJTVp0WXlQeFhheTFX
            MzhMQXEzYTFCUHhyWko3NGc0ZnJZcmsKSLBm/lka0yvmtXUMONkq4+SbHNJS+6FN
            L4NPufnt1JDuyYAMJiuX7eM0McO1F+5ikwFWmMqIfyv/fPPpOynFiw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    lastmodified: "2026-09-08T17:59:44Z"
    mac: ENC[AES256_GCM,data:DXr5XkUt5GwawsiWKrxCrr/kRKbkh+0oZyYCVfmTZACw+T0NsadHskvEtriv0sElHAj6mxCrsWT2x16OEkoEapFxQRc8R7W3KSbC/I/TcVumUmQB01ktKrSxL/zSqKM6SrV7M+x9f5jvkJ1t0K57QQyFAvgbO65CQOfsXVevrA4=,iv:MM7jFiaiMKZk2U/Vskt4Quzho239ppvsgojsEmtFTpg=,tag:WkVrnbgZ/qvpRQf/SL/CDA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: volsync-jellyfin-config-secrets
    namespace: streaming
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:Z/mgOaAEsAZ1+OYa3b5pwJka/e7nCiTJSp1qiNGD4XXKUQ/u8BAZmGzE/9rKk2n/dkPO8lHxQvb2UIuKERQ=,iv:cPTrNYGPb8guue8Uai0vd0pJYirFEUWSFPYzMG6ogHg=,tag:tBJTW3qltFRvoJHjp5LoOA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:qHyUwUQMu9o1xCGXKVoDk8nV5prPDOttyhoIMZLZPSiUedNpwYZRxqKfvwqbODi2GzA=,iv:b6QlJpmZrlaTKhsjAURgivNYlmNBHWFd69ymenWlEs8=,tag:4asulUGDrJpxCy5XjtOHxg==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:TlGdk0kxPWnPIzosCoYPBQ==,iv:0LPClEyRC1gKKPBWv2tzgujAWkLgER+c15rNVKXmBfE=,tag:SwaxlAa74aVSu4VX7TdmHg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:iFt3P9+j4KV8aFwuJtFykHrFu3JvVjNNrSXWunWdyqtlYozRm0Kr9Ak9mq6/GCAy3NA=,iv:c6oFIbG5VqxD+9mfevl+oKGzUA3HwNBPOmwpMUIFMW4=,tag:ObOHiXXnprwvDfLrc74GVg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RUtWaE9lZDk5VC9uYmMw
            a0ZoRkluMk9BZUlndGxQVlNQQkF2MTR4c3o4CmJxdFU4TDBYbnArU0xsZTNQSklu
            NFY2SWhuTms0ckY1NGI3d2Ezd0xtMkEKLS0tIHdCUWhWdzRJTVp0WXlQeFhheTFX
            MzhMQXEzYTFCUHhyWko3NGc0ZnJZcmsKSLBm/lka0yvmtXUMONkq4+SbHNJS+6FN
            L4NPufnt1JDuyYAMJiuX7eM0McO1F+5ikwFWmMqIfyv/fPPpOynFiw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    lastmodified: "2026-09-08T17:59:44Z"
    mac: ENC[AES256_GCM,data:DXr5XkUt5GwawsiWKrxCrr/kRKbkh+0oZyYCVfmTZACw+T0NsadHskvEtriv0sElHAj6mxCrsWT2x16OEkoEapFxQRc8R7W3KSbC/I/TcVumUmQB01ktKrSxL/zSqKM6SrV7M+x9f5jvkJ1t0K57QQyFAvgbO65CQOfsXVevrA4=,iv:MM7jFiaiMKZk2U/Vskt4Quzho239ppvsgojsEmtFTpg=,tag:WkVrnbgZ/qvpRQf/SL/CDA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: volsync-jellyfin-media-secrets
    namespace: streaming
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:fFhYnFps75kNUKa5M+Pw6ZCYAh7xpfCIsmAHRVwjcv3IudCIGe7sHI/hZhZYpGRlYBmwgVLVFHMrsBWeSA==,iv:44eyJM812A5by8g8m8/ArC2zT4GDSkgupeFb0AsSyAA=,tag:3ZA4kyaBqYWmzhOMJ9xb0g==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:qHyUwUQMu9o1xCGXKVoDk8nV5prPDOttyhoIMZLZPSiUedNpwYZRxqKfvwqbODi2GzA=,iv:b6QlJpmZrlaTKhsjAURgivNYlmNBHWFd69ymenWlEs8=,tag:4asulUGDrJpxCy5XjtOHxg==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:TlGdk0kxPWnPIzosCoYPBQ==,iv:0LPClEyRC1gKKPBWv2tzgujAWkLgER+c15rNVKXmBfE=,tag:SwaxlAa74aVSu4VX7TdmHg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:iFt3P9+j4KV8aFwuJtFykHrFu3JvVjNNrSXWunWdyqtlYozRm0Kr9Ak9mq6/GCAy3NA=,iv:c6oFIbG5VqxD+9mfevl+oKGzUA3HwNBPOmwpMUIFMW4=,tag:ObOHiXXnprwvDfLrc74GVg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RUtWaE9lZDk5VC9uYmMw
            a0ZoRkluMk9BZUlndGxQVlNQQkF2MTR4c3o4CmJxdFU4TDBYbnArU0xsZTNQSklu
            NFY2SWhuTms0ckY1NGI3d2Ezd0xtMkEKLS0tIHdCUWhWdzRJTVp0WXlQeFhheTFX
            MzhMQXEzYTFCUHhyWko3NGc0ZnJZcmsKSLBm/lka0yvmtXUMONkq4+SbHNJS+6FN
            L4NPufnt1JDuyYAMJiuX7eM0McO1F+5ikwFWmMqIfyv/fPPpOynFiw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    lastmodified: "2026-09-08T17:59:44Z"
    mac: ENC[AES256_GCM,data:DXr5XkUt5GwawsiWKrxCrr/kRKbkh+0oZyYCVfmTZACw+T0NsadHskvEtriv0sElHAj6mxCrsWT2x16OEkoEapFxQRc8R7W3KSbC/I/TcVumUmQB01ktKrSxL/zSqKM6SrV7M+x9f5jvkJ1t0K57QQyFAvgbO65CQOfsXVevrA4=,iv:MM7jFiaiMKZk2U/Vskt4Quzho239ppvsgojsEmtFTpg=,tag:WkVrnbgZ/qvpRQf/SL/CDA==,type:str]
    version: 3.13.3
