apiVersion: v1
kind: Secret
metadata:
    name: jellyfin-netbird-secrets
    namespace: streaming
type: Opaque
stringData:
    NB_SETUP_KEY: ENC[AES256_GCM,data:ySFVx6xL9FSbh5myx9hphDiAwl1vABSavXDeRrvksq6kvy3n,iv:9ukwm0y2UG+XWFtoigX4MmsgONWTqVVJhxHoRjsSjdc=,tag:dk/QDGGEW/CryoBOU2JzAQ==,type:str]
    NB_MANAGEMENT_URL: ENC[AES256_GCM,data:EtaiScYTzk5FDbzzd7amyK+9ag==,iv:zdruLpfytQpYkqSANEXF6gomcXh9nTvE3L9hmyhq0tM=,tag:DYNN9UjkBuUmeQmRQLDJbA==,type:str]
    NB_EXTRA_DNS_LABELS: ENC[AES256_GCM,data:qTOxu5Dm0B5WWrqjhwv4lLsY,iv:5yYAw9Ytd459W03bgsNNXsBvLL5G1cEFuT06JRsFrZ0=,tag:Pt7AmIv0ZymOi/noXkwtgg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RUtWaE9lZDk5VC9uYmMw
            a0ZoRkluMk9BZUlndGxQVlNQQkF2MTR4c3o4CmJxdFU4TDBYbnArU0xsZTNQSklu
            NFY2SWhuTms0ckY1NGI3d2Ezd0xtMkEKLS0tIHdCUWhWdzRJTVp0WXlQeFhheTFX
            MzhMQXEzYTFCUHhyWko3NGc0ZnJZcmsKSLBm/lka0yvmtXUMONkq4+SbHNJS+6FN
            L4NPufnt1JDuyYAMJiuX7eM0McO1F+5ikwFWmMqIfyv/fPPpOynFiw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    lastmodified: "2026-09-05T12:13:59Z"
    mac: ENC[AES256_GCM,data:bsymdEmDUoHP0pj3ijHAC5mvLNE/In5S5snRMkCFV26MybQ4lamRzG+rBSUjurHuH2yAnKbRXSleSdBHqzkgnWnmvYOUfphAc84CpwjIDXZwlkUZyM9tD3Ogqr3RJBmHfCV12L5ylRVWemSNMYc+/ns4RW2Kf/Akg5Zk7vmppMM=,iv:YBZdNdEwLg6mEI8nWkYOxSz8g5xtTYqx+LiHJm0zdNE=,tag:f3d1qNwKHBB87h7qO7MywQ==,type:str]
    version: 3.13.3
