apiVersion: v1
kind: Secret
metadata:
    name: jellyfin-netbird-secrets
    namespace: streaming
type: Opaque
stringData:
    NB_SETUP_KEY: ENC[AES256_GCM,data:ySFVx6xL9FSbh5myx9hphDiAwl1vABSavXDeRrvksq6kvy3n,iv:9ukwm0y2UG+XWFtoigX4MmsgONWTqVVJhxHoRjsSjdc=,tag:dk/QDGGEW/CryoBOU2JzAQ==,type:str]
    NB_MANAGEMENT_URL: ENC[AES256_GCM,data:EtaiScYTzk5FDbzzd7amyK+9ag==,iv:zdruLpfytQpYkqSANEXF6gomcXh9nTvE3L9hmyhq0tM=,tag:DYNN9UjkBuUmeQmRQLDJbA==,type:str]
    NB_EXTRA_DNS_LABELS: ENC[AES256_GCM,data:qTOxu5Dm0B5WWrqjhwv4lLsY,iv:5yYAw9Ytd459W03bgsNNXsBvLL5G1cEFuT06JRsFrZ0=,tag:Pt7AmIv0ZymOi/noXkwtgg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RUtWaE9lZDk5VC9uYmMw
            a0ZoRkluMk9BZUlndGxQVlNQQkF2MTR4c3o4CmJxdFU4TDBYbnArU0xsZTNQSklu
            NFY2SWhuTms0ckY1NGI3d2Ezd0xtMkEKLS0tIHdCUWhWdzRJTVp0WXlQeFhheTFX
            MzhMQXEzYTFCUHhyWko3NGc0ZnJZcmsKSLBm/lka0yvmtXUMONkq4+SbHNJS+6FN
            L4NPufnt1JDuyYAMJiuX7eM0McO1F+5ikwFWmMqIfyv/fPPpOynFiw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    lastmodified: "2026-09-08T17:57:19Z"
    mac: ENC[AES256_GCM,data:ukQdl8wTka8eCvsJJMqiJcmaSRIGbQ/N9rmkRy3o81TM4a7miA/QIgt1C42mbJlOXkXsrx7Q7x5Lba1WuArT9JQ86U44kpnQ8t+U97lWtfbLi+mBj5LEo1CvqiRd3QLK9V+yfChpx1rpvpH6M5pBNdhwlt/MZGSlJI/ybzxXXdg=,iv:9ThqnsscDIi0djS/+PJ+YmG85/VCa8dT12HG1z6DIlA=,tag:4/hKgbuFTX77xru9YifV6w==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: volsync-jellyfin-config-secrets
    namespace: streaming
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:Z/mgOaAEsAZ1+OYa3b5pwJka/e7nCiTJSp1qiNGD4XXKUQ/u8BAZmGzE/9rKk2n/dkPO8lHxQvb2UIuKERQ=,iv:cPTrNYGPb8guue8Uai0vd0pJYirFEUWSFPYzMG6ogHg=,tag:tBJTW3qltFRvoJHjp5LoOA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:tIEOIRidq3X7Xw5faEwK6jiKULWkkHZ16PAFbJkXFLanXoAJZCarh0LDMGnMDsGwCJ0=,iv:pprs9r8dQ0IP1l/w/YoqN8SOGMqD2BHTSCt1ghzUCCY=,tag:ct71ZRl+vmoOJpld1a2ydA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:f+mnfF3BpUah13TsYbTQAg==,iv:IWne35NRZTxBqKhNjYu3WuBLT37DmH4PNOaLWTRYclA=,tag:7JZPqcZ6uILy58kVx7kocw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:hRf6jQJcRIit4R2RMpiStz2MrPuyqwAFGdkSlTJa6igRJIeXKe9p10/YTENcNQtNuLs=,iv:uD5sVscbIwo5C+HMUfrW/7KKzjDGGFKfvcbs1LHEVbc=,tag:RjYLgEXHJ0CBuQxRfrcqcg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RUtWaE9lZDk5VC9uYmMw
            a0ZoRkluMk9BZUlndGxQVlNQQkF2MTR4c3o4CmJxdFU4TDBYbnArU0xsZTNQSklu
            NFY2SWhuTms0ckY1NGI3d2Ezd0xtMkEKLS0tIHdCUWhWdzRJTVp0WXlQeFhheTFX
            MzhMQXEzYTFCUHhyWko3NGc0ZnJZcmsKSLBm/lka0yvmtXUMONkq4+SbHNJS+6FN
            L4NPufnt1JDuyYAMJiuX7eM0McO1F+5ikwFWmMqIfyv/fPPpOynFiw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    lastmodified: "2026-09-08T17:57:19Z"
    mac: ENC[AES256_GCM,data:ukQdl8wTka8eCvsJJMqiJcmaSRIGbQ/N9rmkRy3o81TM4a7miA/QIgt1C42mbJlOXkXsrx7Q7x5Lba1WuArT9JQ86U44kpnQ8t+U97lWtfbLi+mBj5LEo1CvqiRd3QLK9V+yfChpx1rpvpH6M5pBNdhwlt/MZGSlJI/ybzxXXdg=,iv:9ThqnsscDIi0djS/+PJ+YmG85/VCa8dT12HG1z6DIlA=,tag:4/hKgbuFTX77xru9YifV6w==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: volsync-jellyfin-media-secrets
    namespace: streaming
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:fFhYnFps75kNUKa5M+Pw6ZCYAh7xpfCIsmAHRVwjcv3IudCIGe7sHI/hZhZYpGRlYBmwgVLVFHMrsBWeSA==,iv:44eyJM812A5by8g8m8/ArC2zT4GDSkgupeFb0AsSyAA=,tag:3ZA4kyaBqYWmzhOMJ9xb0g==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:qHyUwUQMu9o1xCGXKVoDk8nV5prPDOttyhoIMZLZPSiUedNpwYZRxqKfvwqbODi2GzA=,iv:b6QlJpmZrlaTKhsjAURgivNYlmNBHWFd69ymenWlEs8=,tag:4asulUGDrJpxCy5XjtOHxg==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:TlGdk0kxPWnPIzosCoYPBQ==,iv:0LPClEyRC1gKKPBWv2tzgujAWkLgER+c15rNVKXmBfE=,tag:SwaxlAa74aVSu4VX7TdmHg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:iFt3P9+j4KV8aFwuJtFykHrFu3JvVjNNrSXWunWdyqtlYozRm0Kr9Ak9mq6/GCAy3NA=,iv:c6oFIbG5VqxD+9mfevl+oKGzUA3HwNBPOmwpMUIFMW4=,tag:ObOHiXXnprwvDfLrc74GVg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RUtWaE9lZDk5VC9uYmMw
            a0ZoRkluMk9BZUlndGxQVlNQQkF2MTR4c3o4CmJxdFU4TDBYbnArU0xsZTNQSklu
            NFY2SWhuTms0ckY1NGI3d2Ezd0xtMkEKLS0tIHdCUWhWdzRJTVp0WXlQeFhheTFX
            MzhMQXEzYTFCUHhyWko3NGc0ZnJZcmsKSLBm/lka0yvmtXUMONkq4+SbHNJS+6FN
            L4NPufnt1JDuyYAMJiuX7eM0McO1F+5ikwFWmMqIfyv/fPPpOynFiw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    lastmodified: "2026-09-08T17:57:19Z"
    mac: ENC[AES256_GCM,data:ukQdl8wTka8eCvsJJMqiJcmaSRIGbQ/N9rmkRy3o81TM4a7miA/QIgt1C42mbJlOXkXsrx7Q7x5Lba1WuArT9JQ86U44kpnQ8t+U97lWtfbLi+mBj5LEo1CvqiRd3QLK9V+yfChpx1rpvpH6M5pBNdhwlt/MZGSlJI/ybzxXXdg=,iv:9ThqnsscDIi0djS/+PJ+YmG85/VCa8dT12HG1z6DIlA=,tag:4/hKgbuFTX77xru9YifV6w==,type:str]
    version: 3.13.3
---
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RUtWaE9lZDk5VC9uYmMw
            a0ZoRkluMk9BZUlndGxQVlNQQkF2MTR4c3o4CmJxdFU4TDBYbnArU0xsZTNQSklu
            NFY2SWhuTms0ckY1NGI3d2Ezd0xtMkEKLS0tIHdCUWhWdzRJTVp0WXlQeFhheTFX
            MzhMQXEzYTFCUHhyWko3NGc0ZnJZcmsKSLBm/lka0yvmtXUMONkq4+SbHNJS+6FN
            L4NPufnt1JDuyYAMJiuX7eM0McO1F+5ikwFWmMqIfyv/fPPpOynFiw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2cvg7fc40lvdnuu98glfhmp3mq2yz0vv28sqekqmw2nqmgmpduqpwc4u9
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|auths|endpoint|wwid|SMB_USER|SMB_PASS|keyring|ceph-secret|ceph-username|fsid|mon-secret|stringData)$
    lastmodified: "2026-09-08T17:57:19Z"
    mac: ENC[AES256_GCM,data:ukQdl8wTka8eCvsJJMqiJcmaSRIGbQ/N9rmkRy3o81TM4a7miA/QIgt1C42mbJlOXkXsrx7Q7x5Lba1WuArT9JQ86U44kpnQ8t+U97lWtfbLi+mBj5LEo1CvqiRd3QLK9V+yfChpx1rpvpH6M5pBNdhwlt/MZGSlJI/ybzxXXdg=,iv:9ThqnsscDIi0djS/+PJ+YmG85/VCa8dT12HG1z6DIlA=,tag:4/hKgbuFTX77xru9YifV6w==,type:str]
    version: 3.13.3
