---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podcast-ad-remover
  namespace: podcast
  labels:
    app: podcast-ad-remover
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: podcast-ad-remover
  template:
    metadata:
      labels:
        app: podcast-ad-remover
    spec:
      priorityClassName: low-priority
      nodeSelector:
        kubernetes.io/hostname: s1-main01-cpwr11
      containers:
        - name: podcast-ad-remover
          image: jdcb4/podcast-ad-remover:1.3.1
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: podcast-ad-remover-secret
                  key: GEMINI_API_KEY
            - name: BASE_URL
              value: "http://192.168.201.110"
            - name: CHECK_INTERVAL_MINUTES
              value: "15"
            - name: WHISPER_MODEL
              value: "large-v3-turbo"
            - name: KUBERNETES_MEMORY_LIMIT
              valueFrom:
                resourceFieldRef:
                  containerName: podcast-ad-remover
                  resource: limits.memory
            # - name: PORT
            #   value: "80"
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              cpu: "4000m"
              memory: "5Gi"
          volumeMounts:
            - name: data-volume
              mountPath: /data
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: podcast-ad-remover